## 1. Imports

In [1]:
import os
import warnings

import pandas as pd

warnings.filterwarnings("ignore")

## 2. Paths

In [2]:
PROJECT_PATH = "/content/drive/MyDrive/FinSight_AI"

DATA_PATH = os.path.join(
    PROJECT_PATH,
    "data"
)

PROCESSED_PATH = os.path.join(
    DATA_PATH,
    "processed"
)

CLASSIFICATION_PATH = os.path.join(
    DATA_PATH,
    "classification"
)

HYBRID_PATH = os.path.join(
    CLASSIFICATION_PATH,
    "hybrid_classification"
)

INTELLIGENCE_PATH = os.path.join(
    PROCESSED_PATH,
    "financial_intelligence"
)

os.makedirs(
    INTELLIGENCE_PATH,
    exist_ok=True
)

## 3. Load Financial News

In [3]:
financial_news = pd.read_parquet(

    os.path.join(

        PROCESSED_PATH,

        "financial_news_clean.parquet"

    )

)

print("="*70)
print("Financial News")
print("="*70)

print(financial_news.shape)

financial_news.head()

======================================================================
Financial News
======================================================================
(3215296, 18)

,news_id,headline,url,publisher,published_date,ticker,source,year,month,day,weekday,hour,headline_length,word_count,has_time,original_headline,clean_character_count,clean_word_count
0,1,Stocks That Hit 52-Week Highs On Friday,https://www.benzinga.com/news/20/06/16190091/s...,Benzinga Insights,2020-06-05 14:30:54+00:00,A,analyst,2020,6,5,Friday,14,39,7,True,Stocks That Hit 52-Week Highs On Friday,39,7
1,2,Stocks That Hit 52-Week Highs On Wednesday,https://www.benzinga.com/news/20/06/16170189/s...,Benzinga Insights,2020-06-03 14:45:20+00:00,A,analyst,2020,6,3,Wednesday,14,42,7,True,Stocks That Hit 52-Week Highs On Wednesday,42,7
2,3,71 Biggest Movers From Friday,https://www.benzinga.com/news/20/05/16103463/7...,Lisa Levin,2020-05-26 08:30:07+00:00,A,analyst,2020,5,26,Tuesday,8,29,5,True,71 Biggest Movers From Friday,29,5
3,4,46 Stocks Moving In Friday's Mid-Day Session,https://www.benzinga.com/news/20/05/16095921/4...,Lisa Levin,2020-05-22 16:45:06+00:00,A,analyst,2020,5,22,Friday,16,44,7,True,46 Stocks Moving In Friday's Mid-Day Session,44,7
4,5,B of A Securities Maintains Neutral on Agilent...,https://www.benzinga.com/news/20/05/16095304/b...,Vick Meyer,2020-05-22 15:38:59+00:00,A,analyst,2020,5,22,Friday,15,87,14,True,B of A Securities Maintains Neutral on Agilent...,87,14

## 4. Load Hybrid Classification

In [4]:
classification = pd.read_parquet(

    os.path.join(

        HYBRID_PATH,

        "news_classification_final.parquet"

    )

)

print("Hybrid Classification")

print(classification.shape)

classification.head()

Hybrid Classification
(3215296, 11)

,news_id,headline,event,market_signal,confidence,matched_keywords,rule_score,method,final_event,final_confidence,classification_source
0,1,Stocks That Hit 52-Week Highs On Friday,Market Movement,Neutral,1.0,52[- ]week\s+highs?,5.0,Rule,Market Movement,1.0,Rule
1,2,Stocks That Hit 52-Week Highs On Wednesday,Market Movement,Neutral,1.0,52[- ]week\s+highs?,5.0,Rule,Market Movement,1.0,Rule
2,3,71 Biggest Movers From Friday,Market Movement,Neutral,1.0,"biggest movers, biggest\s+movers",10.0,Rule,Market Movement,1.0,Rule
3,4,46 Stocks Moving In Friday's Mid-Day Session,Market Movement,Neutral,1.0,"mid-day session, mid[- ]day\s+session, stocks ...",14.0,Rule,Market Movement,1.0,Rule
4,5,B of A Securities Maintains Neutral on Agilent...,Analyst Rating,Bullish,1.0,"maintains, maintains?\s+\w+\s+on, neutral, pri...",13.0,Rule,Analyst Rating,1.0,Rule

## 5. Validate Merge Keys

In [5]:
print("Validation")

print("Financial News")

print("Rows :", len(financial_news))

print("Unique news_id :", financial_news["news_id"].nunique())

print()

print("Classification")

print("Rows :", len(classification))

print("Unique news_id :", classification["news_id"].nunique())

Validation
Financial News
Rows : 3215296
Unique news_id : 3215296

Classification
Rows : 3215296
Unique news_id : 3215296

## 6. Merge Financial News and Classification

In [6]:
intelligence_df = financial_news.merge(

    classification[

        [

            "news_id",

            "final_event",

            "market_signal",

            "final_confidence",

            "classification_source"

        ]

    ],

    on="news_id",

    how="left",

    validate="one_to_one"

)

print("Financial Intelligence Dataset Created")

print(intelligence_df.shape)

intelligence_df.head()

Financial Intelligence Dataset Created
(3215296, 22)

,news_id,headline,url,publisher,published_date,ticker,source,year,month,day,...,headline_length,word_count,has_time,original_headline,clean_character_count,clean_word_count,final_event,market_signal,final_confidence,classification_source
0,1,Stocks That Hit 52-Week Highs On Friday,https://www.benzinga.com/news/20/06/16190091/s...,Benzinga Insights,2020-06-05 14:30:54+00:00,A,analyst,2020,6,5,...,39,7,True,Stocks That Hit 52-Week Highs On Friday,39,7,Market Movement,Neutral,1.0,Rule
1,2,Stocks That Hit 52-Week Highs On Wednesday,https://www.benzinga.com/news/20/06/16170189/s...,Benzinga Insights,2020-06-03 14:45:20+00:00,A,analyst,2020,6,3,...,42,7,True,Stocks That Hit 52-Week Highs On Wednesday,42,7,Market Movement,Neutral,1.0,Rule
2,3,71 Biggest Movers From Friday,https://www.benzinga.com/news/20/05/16103463/7...,Lisa Levin,2020-05-26 08:30:07+00:00,A,analyst,2020,5,26,...,29,5,True,71 Biggest Movers From Friday,29,5,Market Movement,Neutral,1.0,Rule
3,4,46 Stocks Moving In Friday's Mid-Day Session,https://www.benzinga.com/news/20/05/16095921/4...,Lisa Levin,2020-05-22 16:45:06+00:00,A,analyst,2020,5,22,...,44,7,True,46 Stocks Moving In Friday's Mid-Day Session,44,7,Market Movement,Neutral,1.0,Rule
4,5,B of A Securities Maintains Neutral on Agilent...,https://www.benzinga.com/news/20/05/16095304/b...,Vick Meyer,2020-05-22 15:38:59+00:00,A,analyst,2020,5,22,...,87,14,True,B of A Securities Maintains Neutral on Agilent...,87,14,Analyst Rating,Bullish,1.0,Rule

## 7. Data Validation

In [7]:
print("Validation")

print(f"Rows                : {len(intelligence_df):,}")

print(f"Unique News IDs     : {intelligence_df['news_id'].nunique():,}")

print()

print("Missing Values")

print()

print(

    intelligence_df[

        [

            "final_event",

            "market_signal",

            "final_confidence",

            "classification_source"

        ]

    ]

    .isna()

    .sum()

)

Validation
Rows                : 3,215,296
Unique News IDs     : 3,215,296

Missing Values

final_event              0
market_signal            0
final_confidence         0
classification_source    0
dtype: int64

## 8. Save Final Intelligence Dataset

In [8]:
OUTPUT_FILE = os.path.join(

    INTELLIGENCE_PATH,

    "financial_intelligence_dataset.parquet"

)

intelligence_df.to_parquet(

    OUTPUT_FILE,

    index=False

)

print("FINANCIAL INTELLIGENCE DATASET SAVED")

print(OUTPUT_FILE)

FINANCIAL INTELLIGENCE DATASET SAVED
/content/drive/MyDrive/FinSight_AI/data/processed/financial_intelligence/financial_intelligence_dataset.parquet

## 9. Evaluation

In [9]:
event_summary = (

    intelligence_df

    .groupby("final_event")

    .agg(

        headlines=("news_id", "count"),

        avg_confidence=("final_confidence", "mean")

    )

    .sort_values(

        "headlines",

        ascending=False

    )

    .reset_index()

)

display(event_summary)

             final_event  headlines  avg_confidence
0         Product Launch     654857        0.758737
1               Earnings     567435        0.944125
2        Market Movement     469086        0.833923
3         Analyst Rating     277248        0.899277
4   Merger & Acquisition     231793        0.790391
5              Commodity     176547        0.840405
6                  Other     137156        0.678070
7     Technical Analysis     113179        0.786142
8               Dividend     110494        0.956925
9       Executive Change      45456        0.917445
10      Options Activity      43010        0.860409
11           Partnership      40699        0.882667
12         Credit Rating      36358        0.956756
13                   ESG      34695        0.746687
14      Revenue Guidance      34374        0.864971
15               Layoffs      32802        0.745874
16               Funding      32578        0.863721
17       Monetary Policy      26738        0.864893
18   Regulatory Approval      24951        0.921823
19         Share Buyback      19410        0.812230
20                   IPO      17891        0.875808
21            Litigation      17450        0.839660
22         Economic Data      14319        0.859742
23        Cryptocurrency      13739        0.773372
24          Trading Halt      11208        0.848943
25       Insider Trading       9530        0.942794
26         Cybersecurity       7612        0.803114
27           Stock Split       6946        0.760280
28                 Fraud       4692        0.839715
29            Bankruptcy       3043        0.904568

## 10. Summary

In [10]:
summary = pd.DataFrame({

    "Metric": [

        "Rows",

        "Columns",

        "Companies",

        "Publishers",

        "Event Types",

        "Output File"

    ],

    "Value": [

        len(intelligence_df),

        intelligence_df.shape[1],

        intelligence_df["ticker"].nunique(),

        intelligence_df["publisher"].nunique(),

        intelligence_df["final_event"].nunique(),

        os.path.basename(OUTPUT_FILE)

    ]

})

display(summary)

        Metric                                   Value
0         Rows                                 3215296
1      Columns                                      22
2    Companies                                    6619
3   Publishers                                    1047
4  Event Types                                      30
5  Output File  financial_intelligence_dataset.parquet