## 1. Imports

In [1]:
import os
import warnings

import numpy as np
import pandas as pd

warnings.filterwarnings("ignore")

## 2. Paths

In [2]:
PROJECT_PATH = "/content/drive/MyDrive/FinSight_AI"

DATA_PATH = os.path.join(
    PROJECT_PATH,
    "data"
)

PROCESSED_PATH = os.path.join(
    DATA_PATH,
    "processed"
)

INTELLIGENCE_PATH = os.path.join(
    PROCESSED_PATH,
    "financial_intelligence"
)

TIMELINE_PATH = os.path.join(
    PROCESSED_PATH,
    "company_timeline"
)

os.makedirs(
    TIMELINE_PATH,
    exist_ok=True
)

## 3. Load Financial Intelligence Dataset

In [4]:
timeline_df = pd.read_parquet(

    os.path.join(

        INTELLIGENCE_PATH,

        "financial_intelligence_dataset.parquet"

    )

)

print("Financial Intelligence Dataset")

print(timeline_df.shape)

timeline_df.head()

Financial Intelligence Dataset
(3215296, 22)

,news_id,headline,url,publisher,published_date,ticker,source,year,month,day,...,headline_length,word_count,has_time,original_headline,clean_character_count,clean_word_count,final_event,market_signal,final_confidence,classification_source
0,1,Stocks That Hit 52-Week Highs On Friday,https://www.benzinga.com/news/20/06/16190091/s...,Benzinga Insights,2020-06-05 14:30:54+00:00,A,analyst,2020,6,5,...,39,7,True,Stocks That Hit 52-Week Highs On Friday,39,7,Market Movement,Neutral,1.0,Rule
1,2,Stocks That Hit 52-Week Highs On Wednesday,https://www.benzinga.com/news/20/06/16170189/s...,Benzinga Insights,2020-06-03 14:45:20+00:00,A,analyst,2020,6,3,...,42,7,True,Stocks That Hit 52-Week Highs On Wednesday,42,7,Market Movement,Neutral,1.0,Rule
2,3,71 Biggest Movers From Friday,https://www.benzinga.com/news/20/05/16103463/7...,Lisa Levin,2020-05-26 08:30:07+00:00,A,analyst,2020,5,26,...,29,5,True,71 Biggest Movers From Friday,29,5,Market Movement,Neutral,1.0,Rule
3,4,46 Stocks Moving In Friday's Mid-Day Session,https://www.benzinga.com/news/20/05/16095921/4...,Lisa Levin,2020-05-22 16:45:06+00:00,A,analyst,2020,5,22,...,44,7,True,46 Stocks Moving In Friday's Mid-Day Session,44,7,Market Movement,Neutral,1.0,Rule
4,5,B of A Securities Maintains Neutral on Agilent...,https://www.benzinga.com/news/20/05/16095304/b...,Vick Meyer,2020-05-22 15:38:59+00:00,A,analyst,2020,5,22,...,87,14,True,B of A Securities Maintains Neutral on Agilent...,87,14,Analyst Rating,Bullish,1.0,Rule

## 4. Select Timeline Columns

In [5]:
timeline_df = timeline_df[

    [

        "news_id",

        "ticker",

        "published_date",

        "headline",

        "publisher",

        "final_event",

        "market_signal",

        "final_confidence"

    ]

].copy()

timeline_df.head()

,news_id,ticker,published_date,headline,publisher,final_event,market_signal,final_confidence
0,1,A,2020-06-05 14:30:54+00:00,Stocks That Hit 52-Week Highs On Friday,Benzinga Insights,Market Movement,Neutral,1.0
1,2,A,2020-06-03 14:45:20+00:00,Stocks That Hit 52-Week Highs On Wednesday,Benzinga Insights,Market Movement,Neutral,1.0
2,3,A,2020-05-26 08:30:07+00:00,71 Biggest Movers From Friday,Lisa Levin,Market Movement,Neutral,1.0
3,4,A,2020-05-22 16:45:06+00:00,46 Stocks Moving In Friday's Mid-Day Session,Lisa Levin,Market Movement,Neutral,1.0
4,5,A,2020-05-22 15:38:59+00:00,B of A Securities Maintains Neutral on Agilent...,Vick Meyer,Analyst Rating,Bullish,1.0

## 5. Data Preparation

In [7]:
timeline_df["published_date"] = pd.to_datetime(

    timeline_df["published_date"]

)

timeline_df = timeline_df.sort_values(

    [

        "ticker",

        "published_date"

    ]

).reset_index(

    drop=True

)

print("Timeline Prepared")

timeline_df.head()

Timeline Prepared

,news_id,ticker,published_date,headline,publisher,final_event,market_signal,final_confidence
0,1417,A,2009-04-29 00:00:00+00:00,Going Against the Herd,Charles Lewis Sizemore CFA,Product Launch,Neutral,0.7433
1,1416,A,2009-06-01 00:00:00+00:00,super-trades - Two 52 week highs and others ab...,superman,Market Movement,Neutral,1.0000
2,1415,A,2009-07-14 00:00:00+00:00,Skystar Bio-Pharmaceutical Announces Expansion...,superman,Product Launch,Bullish,1.0000
3,1414,A,2009-07-30 00:00:00+00:00,The Gold/Silver Ratio From 1300 to 1900...And Now,prudentinvestor,Commodity,Neutral,1.0000
4,1413,A,2009-08-04 00:00:00+00:00,"A Simulation of China's 2,$$$,$$$,$$$,$$$ Dive...",prudentinvestor,Market Movement,Neutral,0.7445

## 6. Event Sequence Number

In [8]:
# Event Sequence
timeline_df["event_number"] = (

    timeline_df

    .groupby("ticker")

    .cumcount()

    + 1

)

timeline_df.head()

,news_id,ticker,published_date,headline,publisher,final_event,market_signal,final_confidence,event_number
0,1417,A,2009-04-29 00:00:00+00:00,Going Against the Herd,Charles Lewis Sizemore CFA,Product Launch,Neutral,0.7433,1
1,1416,A,2009-06-01 00:00:00+00:00,super-trades - Two 52 week highs and others ab...,superman,Market Movement,Neutral,1.0000,2
2,1415,A,2009-07-14 00:00:00+00:00,Skystar Bio-Pharmaceutical Announces Expansion...,superman,Product Launch,Bullish,1.0000,3
3,1414,A,2009-07-30 00:00:00+00:00,The Gold/Silver Ratio From 1300 to 1900...And Now,prudentinvestor,Commodity,Neutral,1.0000,4
4,1413,A,2009-08-04 00:00:00+00:00,"A Simulation of China's 2,$$$,$$$,$$$,$$$ Dive...",prudentinvestor,Market Movement,Neutral,0.7445,5

## 7. Previous & Next Event Dates

In [9]:
# Previous & Next Event
timeline_df["previous_event_date"] = (

    timeline_df

    .groupby("ticker")["published_date"]

    .shift(1)

)

timeline_df["next_event_date"] = (

    timeline_df

    .groupby("ticker")["published_date"]

    .shift(-1)

)

timeline_df.head()

,news_id,ticker,published_date,headline,publisher,final_event,market_signal,final_confidence,event_number,previous_event_date,next_event_date
0,1417,A,2009-04-29 00:00:00+00:00,Going Against the Herd,Charles Lewis Sizemore CFA,Product Launch,Neutral,0.7433,1,NaT,2009-06-01 00:00:00+00:00
1,1416,A,2009-06-01 00:00:00+00:00,super-trades - Two 52 week highs and others ab...,superman,Market Movement,Neutral,1.0000,2,2009-04-29 00:00:00+00:00,2009-07-14 00:00:00+00:00
2,1415,A,2009-07-14 00:00:00+00:00,Skystar Bio-Pharmaceutical Announces Expansion...,superman,Product Launch,Bullish,1.0000,3,2009-06-01 00:00:00+00:00,2009-07-30 00:00:00+00:00
3,1414,A,2009-07-30 00:00:00+00:00,The Gold/Silver Ratio From 1300 to 1900...And Now,prudentinvestor,Commodity,Neutral,1.0000,4,2009-07-14 00:00:00+00:00,2009-08-04 00:00:00+00:00
4,1413,A,2009-08-04 00:00:00+00:00,"A Simulation of China's 2,$$$,$$$,$$$,$$$ Dive...",prudentinvestor,Market Movement,Neutral,0.7445,5,2009-07-30 00:00:00+00:00,2009-08-06 00:00:00+00:00

## 8. Days Between Events

In [10]:
# Time Gap Features
timeline_df["days_since_previous_event"] = (

    timeline_df["published_date"]

    -

    timeline_df["previous_event_date"]

).dt.days

timeline_df["days_until_next_event"] = (

    timeline_df["next_event_date"]

    -

    timeline_df["published_date"]

).dt.days

timeline_df.head()

,news_id,ticker,published_date,headline,publisher,final_event,market_signal,final_confidence,event_number,previous_event_date,next_event_date,days_since_previous_event,days_until_next_event
0,1417,A,2009-04-29 00:00:00+00:00,Going Against the Herd,Charles Lewis Sizemore CFA,Product Launch,Neutral,0.7433,1,NaT,2009-06-01 00:00:00+00:00,NaN,33.0
1,1416,A,2009-06-01 00:00:00+00:00,super-trades - Two 52 week highs and others ab...,superman,Market Movement,Neutral,1.0000,2,2009-04-29 00:00:00+00:00,2009-07-14 00:00:00+00:00,33.0,43.0
2,1415,A,2009-07-14 00:00:00+00:00,Skystar Bio-Pharmaceutical Announces Expansion...,superman,Product Launch,Bullish,1.0000,3,2009-06-01 00:00:00+00:00,2009-07-30 00:00:00+00:00,43.0,16.0
3,1414,A,2009-07-30 00:00:00+00:00,The Gold/Silver Ratio From 1300 to 1900...And Now,prudentinvestor,Commodity,Neutral,1.0000,4,2009-07-14 00:00:00+00:00,2009-08-04 00:00:00+00:00,16.0,5.0
4,1413,A,2009-08-04 00:00:00+00:00,"A Simulation of China's 2,$$$,$$$,$$$,$$$ Dive...",prudentinvestor,Market Movement,Neutral,0.7445,5,2009-07-30 00:00:00+00:00,2009-08-06 00:00:00+00:00,5.0,2.0

## 9. Rolling Event Count

In [11]:
# Rolling Total Events
timeline_df["events_so_far"] = (

    timeline_df

    .groupby("ticker")

    .cumcount()

    + 1

)

timeline_df.head()

,news_id,ticker,published_date,headline,publisher,final_event,market_signal,final_confidence,event_number,previous_event_date,next_event_date,days_since_previous_event,days_until_next_event,events_so_far
0,1417,A,2009-04-29 00:00:00+00:00,Going Against the Herd,Charles Lewis Sizemore CFA,Product Launch,Neutral,0.7433,1,NaT,2009-06-01 00:00:00+00:00,NaN,33.0,1
1,1416,A,2009-06-01 00:00:00+00:00,super-trades - Two 52 week highs and others ab...,superman,Market Movement,Neutral,1.0000,2,2009-04-29 00:00:00+00:00,2009-07-14 00:00:00+00:00,33.0,43.0,2
2,1415,A,2009-07-14 00:00:00+00:00,Skystar Bio-Pharmaceutical Announces Expansion...,superman,Product Launch,Bullish,1.0000,3,2009-06-01 00:00:00+00:00,2009-07-30 00:00:00+00:00,43.0,16.0,3
3,1414,A,2009-07-30 00:00:00+00:00,The Gold/Silver Ratio From 1300 to 1900...And Now,prudentinvestor,Commodity,Neutral,1.0000,4,2009-07-14 00:00:00+00:00,2009-08-04 00:00:00+00:00,16.0,5.0,4
4,1413,A,2009-08-04 00:00:00+00:00,"A Simulation of China's 2,$$$,$$$,$$$,$$$ Dive...",prudentinvestor,Market Movement,Neutral,0.7445,5,2009-07-30 00:00:00+00:00,2009-08-06 00:00:00+00:00,5.0,2.0,5

## 10. Rolling Risk Events

In [12]:
# Risk Events
RISK_EVENTS = [

    "Fraud",

    "Bankruptcy",

    "Cybersecurity",

    "Litigation",

    "Layoffs"

]

timeline_df["risk_event"] = (

    timeline_df["final_event"]

    .isin(RISK_EVENTS)

).astype(int)

timeline_df["risk_events_so_far"] = (

    timeline_df

    .groupby("ticker")["risk_event"]

    .cumsum()

)

timeline_df.head()

,news_id,ticker,published_date,headline,publisher,final_event,market_signal,final_confidence,event_number,previous_event_date,next_event_date,days_since_previous_event,days_until_next_event,events_so_far,risk_event,risk_events_so_far
0,1417,A,2009-04-29 00:00:00+00:00,Going Against the Herd,Charles Lewis Sizemore CFA,Product Launch,Neutral,0.7433,1,NaT,2009-06-01 00:00:00+00:00,NaN,33.0,1,0,0
1,1416,A,2009-06-01 00:00:00+00:00,super-trades - Two 52 week highs and others ab...,superman,Market Movement,Neutral,1.0000,2,2009-04-29 00:00:00+00:00,2009-07-14 00:00:00+00:00,33.0,43.0,2,0,0
2,1415,A,2009-07-14 00:00:00+00:00,Skystar Bio-Pharmaceutical Announces Expansion...,superman,Product Launch,Bullish,1.0000,3,2009-06-01 00:00:00+00:00,2009-07-30 00:00:00+00:00,43.0,16.0,3,0,0
3,1414,A,2009-07-30 00:00:00+00:00,The Gold/Silver Ratio From 1300 to 1900...And Now,prudentinvestor,Commodity,Neutral,1.0000,4,2009-07-14 00:00:00+00:00,2009-08-04 00:00:00+00:00,16.0,5.0,4,0,0
4,1413,A,2009-08-04 00:00:00+00:00,"A Simulation of China's 2,$$$,$$$,$$$,$$$ Dive...",prudentinvestor,Market Movement,Neutral,0.7445,5,2009-07-30 00:00:00+00:00,2009-08-06 00:00:00+00:00,5.0,2.0,5,0,0

## 11. Rolling Bullish / Bearish Counts

In [13]:
# Rolling Market Signals
timeline_df["bullish_event"] = (

    timeline_df["market_signal"]

    == "Bullish"

).astype(int)

timeline_df["bearish_event"] = (

    timeline_df["market_signal"]

    == "Bearish"

).astype(int)

timeline_df["bullish_events_so_far"] = (

    timeline_df

    .groupby("ticker")["bullish_event"]

    .cumsum()

)

timeline_df["bearish_events_so_far"] = (

    timeline_df

    .groupby("ticker")["bearish_event"]

    .cumsum()

)

timeline_df.head()

,news_id,ticker,published_date,headline,publisher,final_event,market_signal,final_confidence,event_number,previous_event_date,next_event_date,days_since_previous_event,days_until_next_event,events_so_far,risk_event,risk_events_so_far,bullish_event,bearish_event,bullish_events_so_far,bearish_events_so_far
0,1417,A,2009-04-29 00:00:00+00:00,Going Against the Herd,Charles Lewis Sizemore CFA,Product Launch,Neutral,0.7433,1,NaT,2009-06-01 00:00:00+00:00,NaN,33.0,1,0,0,0,0,0,0
1,1416,A,2009-06-01 00:00:00+00:00,super-trades - Two 52 week highs and others ab...,superman,Market Movement,Neutral,1.0000,2,2009-04-29 00:00:00+00:00,2009-07-14 00:00:00+00:00,33.0,43.0,2,0,0,0,0,0,0
2,1415,A,2009-07-14 00:00:00+00:00,Skystar Bio-Pharmaceutical Announces Expansion...,superman,Product Launch,Bullish,1.0000,3,2009-06-01 00:00:00+00:00,2009-07-30 00:00:00+00:00,43.0,16.0,3,0,0,1,0,1,0
3,1414,A,2009-07-30 00:00:00+00:00,The Gold/Silver Ratio From 1300 to 1900...And Now,prudentinvestor,Commodity,Neutral,1.0000,4,2009-07-14 00:00:00+00:00,2009-08-04 00:00:00+00:00,16.0,5.0,4,0,0,0,0,1,0
4,1413,A,2009-08-04 00:00:00+00:00,"A Simulation of China's 2,$$$,$$$,$$$,$$$ Dive...",prudentinvestor,Market Movement,Neutral,0.7445,5,2009-07-30 00:00:00+00:00,2009-08-06 00:00:00+00:00,5.0,2.0,5,0,0,0,0,1,0

## 12. Event Importance Score

In [15]:
# Event Importance Score
EVENT_IMPORTANCE = {

    "Bankruptcy": 10,
    "Fraud": 10,
    "Merger & Acquisition": 9,
    "Earnings": 9,
    "Regulatory Approval": 8,
    "Cybersecurity": 8,
    "Monetary Policy": 8,
    "Layoffs": 7,
    "Share Buyback": 7,
    "Product Launch": 7,
    "Revenue Guidance": 7,
    "Dividend": 6,
    "Funding": 6,
    "IPO": 6,
    "Litigation": 6,
    "Credit Rating": 5,
    "Analyst Rating": 5,
    "Executive Change": 5,
    "Commodity": 4,
    "Economic Data": 4,
    "Partnership": 4,
    "Stock Split": 4,
    "Insider Trading": 4,
    "Cryptocurrency": 3,
    "Market Movement": 3,
    "ESG": 3,
    "Options Activity": 2,
    "Technical Analysis": 2,
    "Trading Halt": 2,
    "Other": 1

}

timeline_df["event_importance"] = (

    timeline_df["final_event"]

    .map(EVENT_IMPORTANCE)

    .fillna(1)

    .astype(int)

)

timeline_df.head()

,news_id,ticker,published_date,headline,publisher,final_event,market_signal,final_confidence,event_number,previous_event_date,...,days_since_previous_event,days_until_next_event,events_so_far,risk_event,risk_events_so_far,bullish_event,bearish_event,bullish_events_so_far,bearish_events_so_far,event_importance
0,1417,A,2009-04-29 00:00:00+00:00,Going Against the Herd,Charles Lewis Sizemore CFA,Product Launch,Neutral,0.7433,1,NaT,...,NaN,33.0,1,0,0,0,0,0,0,7
1,1416,A,2009-06-01 00:00:00+00:00,super-trades - Two 52 week highs and others ab...,superman,Market Movement,Neutral,1.0000,2,2009-04-29 00:00:00+00:00,...,33.0,43.0,2,0,0,0,0,0,0,3
2,1415,A,2009-07-14 00:00:00+00:00,Skystar Bio-Pharmaceutical Announces Expansion...,superman,Product Launch,Bullish,1.0000,3,2009-06-01 00:00:00+00:00,...,43.0,16.0,3,0,0,1,0,1,0,7
3,1414,A,2009-07-30 00:00:00+00:00,The Gold/Silver Ratio From 1300 to 1900...And Now,prudentinvestor,Commodity,Neutral,1.0000,4,2009-07-14 00:00:00+00:00,...,16.0,5.0,4,0,0,0,0,1,0,4
4,1413,A,2009-08-04 00:00:00+00:00,"A Simulation of China's 2,$$$,$$$,$$$,$$$ Dive...",prudentinvestor,Market Movement,Neutral,0.7445,5,2009-07-30 00:00:00+00:00,...,5.0,2.0,5,0,0,0,0,1,0,3

## 13. Event Severity Level

In [16]:
# Event Severity
def get_event_severity(score):

    if score >= 9:
        return "Critical"

    elif score >= 7:
        return "High"

    elif score >= 4:
        return "Medium"

    else:
        return "Low"


timeline_df["event_severity"] = (

    timeline_df["event_importance"]

    .apply(get_event_severity)

)

timeline_df.head()

,news_id,ticker,published_date,headline,publisher,final_event,market_signal,final_confidence,event_number,previous_event_date,...,days_until_next_event,events_so_far,risk_event,risk_events_so_far,bullish_event,bearish_event,bullish_events_so_far,bearish_events_so_far,event_importance,event_severity
0,1417,A,2009-04-29 00:00:00+00:00,Going Against the Herd,Charles Lewis Sizemore CFA,Product Launch,Neutral,0.7433,1,NaT,...,33.0,1,0,0,0,0,0,0,7,High
1,1416,A,2009-06-01 00:00:00+00:00,super-trades - Two 52 week highs and others ab...,superman,Market Movement,Neutral,1.0000,2,2009-04-29 00:00:00+00:00,...,43.0,2,0,0,0,0,0,0,3,Low
2,1415,A,2009-07-14 00:00:00+00:00,Skystar Bio-Pharmaceutical Announces Expansion...,superman,Product Launch,Bullish,1.0000,3,2009-06-01 00:00:00+00:00,...,16.0,3,0,0,1,0,1,0,7,High
3,1414,A,2009-07-30 00:00:00+00:00,The Gold/Silver Ratio From 1300 to 1900...And Now,prudentinvestor,Commodity,Neutral,1.0000,4,2009-07-14 00:00:00+00:00,...,5.0,4,0,0,0,0,1,0,4,Medium
4,1413,A,2009-08-04 00:00:00+00:00,"A Simulation of China's 2,$$$,$$$,$$$,$$$ Dive...",prudentinvestor,Market Movement,Neutral,0.7445,5,2009-07-30 00:00:00+00:00,...,2.0,5,0,0,0,0,1,0,3,Low

## 14. Daily Event Count

In [17]:
# Daily Event Count
timeline_df["event_date"] = (

    timeline_df["published_date"]

    .dt.date

)

timeline_df["daily_event_count"] = (

    timeline_df

    .groupby(

        [

            "ticker",

            "event_date"

        ]

    )["news_id"]

    .transform("count")

)

timeline_df.head()

,news_id,ticker,published_date,headline,publisher,final_event,market_signal,final_confidence,event_number,previous_event_date,...,risk_event,risk_events_so_far,bullish_event,bearish_event,bullish_events_so_far,bearish_events_so_far,event_importance,event_severity,event_date,daily_event_count
0,1417,A,2009-04-29 00:00:00+00:00,Going Against the Herd,Charles Lewis Sizemore CFA,Product Launch,Neutral,0.7433,1,NaT,...,0,0,0,0,0,0,7,High,2009-04-29,1
1,1416,A,2009-06-01 00:00:00+00:00,super-trades - Two 52 week highs and others ab...,superman,Market Movement,Neutral,1.0000,2,2009-04-29 00:00:00+00:00,...,0,0,0,0,0,0,3,Low,2009-06-01,1
2,1415,A,2009-07-14 00:00:00+00:00,Skystar Bio-Pharmaceutical Announces Expansion...,superman,Product Launch,Bullish,1.0000,3,2009-06-01 00:00:00+00:00,...,0,0,1,0,1,0,7,High,2009-07-14,1
3,1414,A,2009-07-30 00:00:00+00:00,The Gold/Silver Ratio From 1300 to 1900...And Now,prudentinvestor,Commodity,Neutral,1.0000,4,2009-07-14 00:00:00+00:00,...,0,0,0,0,1,0,4,Medium,2009-07-30,1
4,1413,A,2009-08-04 00:00:00+00:00,"A Simulation of China's 2,$$$,$$$,$$$,$$$ Dive...",prudentinvestor,Market Movement,Neutral,0.7445,5,2009-07-30 00:00:00+00:00,...,0,0,0,0,1,0,3,Low,2009-08-04,1

## 15. Company Activity Level

In [18]:
# Company Activity Level
def get_activity_level(count):

    if count >= 20:
        return "Very High"

    elif count >= 10:
        return "High"

    elif count >= 5:
        return "Medium"

    elif count >= 2:
        return "Low"

    else:
        return "Very Low"


timeline_df["activity_level"] = (

    timeline_df["daily_event_count"]

    .apply(get_activity_level)

)

timeline_df.head()

,news_id,ticker,published_date,headline,publisher,final_event,market_signal,final_confidence,event_number,previous_event_date,...,risk_events_so_far,bullish_event,bearish_event,bullish_events_so_far,bearish_events_so_far,event_importance,event_severity,event_date,daily_event_count,activity_level
0,1417,A,2009-04-29 00:00:00+00:00,Going Against the Herd,Charles Lewis Sizemore CFA,Product Launch,Neutral,0.7433,1,NaT,...,0,0,0,0,0,7,High,2009-04-29,1,Very Low
1,1416,A,2009-06-01 00:00:00+00:00,super-trades - Two 52 week highs and others ab...,superman,Market Movement,Neutral,1.0000,2,2009-04-29 00:00:00+00:00,...,0,0,0,0,0,3,Low,2009-06-01,1,Very Low
2,1415,A,2009-07-14 00:00:00+00:00,Skystar Bio-Pharmaceutical Announces Expansion...,superman,Product Launch,Bullish,1.0000,3,2009-06-01 00:00:00+00:00,...,0,1,0,1,0,7,High,2009-07-14,1,Very Low
3,1414,A,2009-07-30 00:00:00+00:00,The Gold/Silver Ratio From 1300 to 1900...And Now,prudentinvestor,Commodity,Neutral,1.0000,4,2009-07-14 00:00:00+00:00,...,0,0,0,1,0,4,Medium,2009-07-30,1,Very Low
4,1413,A,2009-08-04 00:00:00+00:00,"A Simulation of China's 2,$$$,$$$,$$$,$$$ Dive...",prudentinvestor,Market Movement,Neutral,0.7445,5,2009-07-30 00:00:00+00:00,...,0,0,0,1,0,3,Low,2009-08-04,1,Very Low

## 16. Is Latest Event

In [19]:
# Latest Event Flag
latest_dates = (

    timeline_df

    .groupby("ticker")["published_date"]

    .transform("max")

)

timeline_df["is_latest_event"] = (

    timeline_df["published_date"]

    == latest_dates

)

timeline_df.head()

,news_id,ticker,published_date,headline,publisher,final_event,market_signal,final_confidence,event_number,previous_event_date,...,bullish_event,bearish_event,bullish_events_so_far,bearish_events_so_far,event_importance,event_severity,event_date,daily_event_count,activity_level,is_latest_event
0,1417,A,2009-04-29 00:00:00+00:00,Going Against the Herd,Charles Lewis Sizemore CFA,Product Launch,Neutral,0.7433,1,NaT,...,0,0,0,0,7,High,2009-04-29,1,Very Low,False
1,1416,A,2009-06-01 00:00:00+00:00,super-trades - Two 52 week highs and others ab...,superman,Market Movement,Neutral,1.0000,2,2009-04-29 00:00:00+00:00,...,0,0,0,0,3,Low,2009-06-01,1,Very Low,False
2,1415,A,2009-07-14 00:00:00+00:00,Skystar Bio-Pharmaceutical Announces Expansion...,superman,Product Launch,Bullish,1.0000,3,2009-06-01 00:00:00+00:00,...,1,0,1,0,7,High,2009-07-14,1,Very Low,False
3,1414,A,2009-07-30 00:00:00+00:00,The Gold/Silver Ratio From 1300 to 1900...And Now,prudentinvestor,Commodity,Neutral,1.0000,4,2009-07-14 00:00:00+00:00,...,0,0,1,0,4,Medium,2009-07-30,1,Very Low,False
4,1413,A,2009-08-04 00:00:00+00:00,"A Simulation of China's 2,$$$,$$$,$$$,$$$ Dive...",prudentinvestor,Market Movement,Neutral,0.7445,5,2009-07-30 00:00:00+00:00,...,0,0,1,0,3,Low,2009-08-04,1,Very Low,False

## 17. Save Company Event Timeline

In [20]:
# Save Company Event Timeline
OUTPUT_FILE = os.path.join(

    TIMELINE_PATH,

    "company_event_timeline.parquet"

)

timeline_df.to_parquet(

    OUTPUT_FILE,

    index=False

)

print("COMPANY EVENT TIMELINE SAVED")
print(OUTPUT_FILE)

COMPANY EVENT TIMELINE SAVED
/content/drive/MyDrive/FinSight_AI/data/processed/company_timeline/company_event_timeline.parquet

## 18. Event Distribution

In [21]:
# Event Distribution
event_summary = (

    timeline_df

    .groupby("final_event")

    .agg(

        headlines=("news_id", "count"),

        avg_confidence=("final_confidence", "mean")

    )

    .sort_values(

        "headlines",

        ascending=False

    )

    .reset_index()

)

display(event_summary)

             final_event  headlines  avg_confidence
0         Product Launch     654857        0.758737
1               Earnings     567435        0.944125
2        Market Movement     469086        0.833923
3         Analyst Rating     277248        0.899277
4   Merger & Acquisition     231793        0.790391
5              Commodity     176547        0.840405
6                  Other     137156        0.678070
7     Technical Analysis     113179        0.786142
8               Dividend     110494        0.956925
9       Executive Change      45456        0.917445
10      Options Activity      43010        0.860409
11           Partnership      40699        0.882667
12         Credit Rating      36358        0.956756
13                   ESG      34695        0.746687
14      Revenue Guidance      34374        0.864971
15               Layoffs      32802        0.745874
16               Funding      32578        0.863721
17       Monetary Policy      26738        0.864893
18   Regulatory Approval      24951        0.921823
19         Share Buyback      19410        0.812230
20                   IPO      17891        0.875808
21            Litigation      17450        0.839660
22         Economic Data      14319        0.859742
23        Cryptocurrency      13739        0.773372
24          Trading Halt      11208        0.848943
25       Insider Trading       9530        0.942794
26         Cybersecurity       7612        0.803114
27           Stock Split       6946        0.760280
28                 Fraud       4692        0.839715
29            Bankruptcy       3043        0.904568

## 19. Severity Distribution

In [22]:
# Event Severity Distribution

severity_summary = (

    timeline_df

    .groupby("event_severity")

    .agg(

        headlines=("news_id", "count")

    )

    .sort_values(

        "headlines",

        ascending=False

    )

    .reset_index()

)

display(severity_summary)

  event_severity  headlines
0            Low     822073
1       Critical     806963
2           High     800744
3         Medium     785516

## 20. Market Signal Distribution

In [23]:
# Market Signal Distribution
signal_summary = (

    timeline_df

    .groupby("market_signal")

    .agg(

        headlines=("news_id", "count"),

        avg_confidence=("final_confidence", "mean")

    )

    .sort_values(

        "headlines",

        ascending=False

    )

    .reset_index()

)

display(signal_summary)

  market_signal  headlines  avg_confidence
0       Neutral    2749781        0.826292
1       Bullish     353631        0.928791
2       Bearish      83267        0.894229
3         Mixed      28617        0.934903

## 21. Most Active Companies

In [24]:
# Most Active Companies
top_companies = (

    timeline_df

    .groupby("ticker")

    .agg(

        total_events=("news_id", "count"),

        latest_event=("published_date", "max"),

        avg_confidence=("final_confidence", "mean")

    )

    .sort_values(

        "total_events",

        ascending=False

    )

    .head(20)

    .reset_index()

)

display(top_companies)

   ticker  total_events              latest_event  avg_confidence
0      KR          5061 2020-06-11 16:04:32+00:00        0.827025
1    GILD          4938 2020-06-10 17:44:51+00:00        0.820607
2    DISH          4544 2020-06-10 14:47:32+00:00        0.823487
3     EWJ          4483 2020-06-08 14:13:53+00:00        0.752543
4     MDT          4421 2020-06-11 14:22:31+00:00        0.851852
5     MYL          4416 2020-06-08 15:41:28+00:00        0.830914
6      HD          4415 2020-06-10 12:14:08+00:00        0.829553
7     JWN          4361 2020-06-11 14:34:01+00:00        0.823712
8     FDX          4358 2020-06-09 14:41:45+00:00        0.831489
9    FCAU          4318 2020-06-10 17:23:41+00:00        0.800658
10    FCX          4253 2020-06-09 11:58:18+00:00        0.816144
11    WDC          4177 2020-06-09 14:45:53+00:00        0.837468
12   AVGO          4130 2020-06-08 13:35:32+00:00        0.834512
13    TWX          4077 2019-11-25 00:00:00+00:00        0.804357
14   GRPN          4020 2020-06-10 14:36:34+00:00        0.828431
15    VMW          4002 2020-06-11 14:25:52+00:00        0.840013
16    SLV          3968 2020-06-03 00:00:00+00:00        0.849060
17    CSX          3931 2020-06-05 14:18:13+00:00        0.842038
18     EA          3909 2020-06-10 20:41:25+00:00        0.829336
19    BLK          3886 2020-06-03 13:14:12+00:00        0.837077

## 22. Highest Importance Events

In [25]:
# Highest Importance Events
important_events = (

    timeline_df

    .sort_values(

        [

            "event_importance",

            "final_confidence"

        ],

        ascending=[

            False,

            False

        ]

    )

    [

        [

            "ticker",

            "published_date",

            "headline",

            "final_event",

            "event_importance",

            "event_severity",

            "market_signal",

            "final_confidence"

        ]

    ]

    .head(20)

)

display(important_events)

,ticker,published_date,headline,final_event,event_importance,event_severity,market_signal,final_confidence
61,A,2009-08-07 00:00:00+00:00,British Columbia Securities Commission: Commis...,Fraud,10,Critical,Bearish,1.0
749,A,2012-01-23 00:00:00+00:00,UPDATE: Successfactors Says Received Cfius Not...,Fraud,10,Critical,Bearish,1.0
4589,AA,2017-11-28 00:00:00+00:00,UPDATE: Trump Admin. Probe Into Chinese Alumin...,Fraud,10,Critical,Neutral,1.0
4590,AA,2017-11-28 00:00:00+00:00,UPDATE: Trump Admin. Probe Into Chinese Alumin...,Fraud,10,Critical,Neutral,1.0
4591,AA,2017-11-28 00:00:00+00:00,UPDATE: Trump Admin. Has Opened Probe Into Pos...,Fraud,10,Critical,Neutral,1.0
4628,AA,2018-02-16 00:00:00+00:00,U.S. Commerce Dept. Recommends Trump Impose 24...,Fraud,10,Critical,Neutral,1.0
4873,AA,2019-02-25 00:00:00+00:00,Dissecting The IPS Worldwide Bankruptcy,Bankruptcy,10,Critical,Bearish,1.0
6110,AAL,2020-05-28 00:00:00+00:00,American Airlines (AAL) Clears Doubts Over Ban...,Bankruptcy,10,Critical,Bearish,1.0
7559,AAN,2020-03-24 00:00:00+00:00,AAN Stock: Berger Montague Investigates Securi...,Fraud,10,Critical,Bearish,1.0
10973,AAPL,2020-05-14 00:00:00+00:00,Report: FBI Seizes Sen. Richard Burr's Phone I...,Fraud,10,Critical,Bearish,1.0
13772,ABB,2017-02-10 00:00:00+00:00,SFO opens probe into ABB's U.K. subsidiaries,Fraud,10,Critical,Neutral,1.0
13785,ABB,2017-03-13 00:00:00+00:00,Fraud at ABB trims 2016 profit,Fraud,10,Critical,Mixed,1.0
15900,ABC,2019-11-26 00:00:00+00:00,Brooklyn Federal Prosecutors Open Criminal Pro...,Fraud,10,Critical,Neutral,1.0
16171,ABCO,2012-01-13 00:00:00+00:00,"In Hot, Digital Pursuit of Medicare, Medicaid ...",Fraud,10,Critical,Bearish,1.0
16644,ABDC,2019-04-16 00:00:00+00:00,Alcentra +1.4% after activist urges sale or li...,Bankruptcy,10,Critical,Neutral,1.0
16936,ABEV,2019-08-08 00:00:00+00:00,Ambev lower amid corruption scandal developments,Fraud,10,Critical,Bearish,1.0
16949,ABEV,2019-10-25 00:00:00+00:00,UPDATE: Indian Probe Finds 15-20 Co. Execs Inv...,Fraud,10,Critical,Neutral,1.0
16950,ABEV,2019-10-25 00:00:00+00:00,"India Antitrust Probe Finds AB InBev, Carlsber...",Fraud,10,Critical,Neutral,1.0
17463,ABGB,2015-11-25 00:00:00+00:00,Abengoa threatens to become Spain's largest ev...,Bankruptcy,10,Critical,Bearish,1.0
17466,ABGB,2015-11-27 00:00:00+00:00,Abengoa files for bankruptcy,Bankruptcy,10,Critical,Bearish,1.0

## 23. Timeline Statistics

In [26]:
# Timeline Statistics
timeline_statistics = pd.DataFrame({

    "Metric":[

        "Total Timeline Events",

        "Companies",

        "Publishers",

        "Unique Events",

        "Critical Events",

        "High Events",

        "Average Confidence",

        "Output File"

    ],

    "Value":[

        len(timeline_df),

        timeline_df["ticker"].nunique(),

        timeline_df["publisher"].nunique(),

        timeline_df["final_event"].nunique(),

        (timeline_df["event_severity"]=="Critical").sum(),

        (timeline_df["event_severity"]=="High").sum(),

        round(

            timeline_df["final_confidence"].mean(),

            4

        ),

        os.path.basename(

            OUTPUT_FILE

        )

    ]

})

display(timeline_statistics)

                  Metric                           Value
0  Total Timeline Events                         3215296
1              Companies                            6619
2             Publishers                            1047
3          Unique Events                              30
4        Critical Events                          806963
5            High Events                          800744
6     Average Confidence                          0.8403
7            Output File  company_event_timeline.parquet

## 24. Quick Timeline Example

In [27]:
# Example Timeline
example_company = "A"

display(

    timeline_df[

        timeline_df["ticker"] == example_company

    ]

    [

        [

            "published_date",

            "headline",

            "final_event",

            "market_signal",

            "event_importance",

            "event_severity"

        ]

    ]

    .head(20)

)

,published_date,headline,final_event,market_signal,event_importance,event_severity
0,2009-04-29 00:00:00+00:00,Going Against the Herd,Product Launch,Neutral,7,High
1,2009-06-01 00:00:00+00:00,super-trades - Two 52 week highs and others ab...,Market Movement,Neutral,3,Low
2,2009-07-14 00:00:00+00:00,Skystar Bio-Pharmaceutical Announces Expansion...,Product Launch,Bullish,7,High
3,2009-07-30 00:00:00+00:00,The Gold/Silver Ratio From 1300 to 1900...And Now,Commodity,Neutral,4,Medium
4,2009-08-04 00:00:00+00:00,"A Simulation of China's 2,$$$,$$$,$$$,$$$ Dive...",Market Movement,Neutral,3,Low
5,2009-08-06 00:00:00+00:00,Fairborne Energy Ltd. Announces 2009 Second Qu...,Earnings,Neutral,9,Critical
6,2009-08-06 00:00:00+00:00,Connecticut Shop To Earn Shares Eco Friendly B...,ESG,Neutral,3,Low
7,2009-08-06 00:00:00+00:00,Brampton Brick Reports Results for the Second ...,Earnings,Neutral,9,Critical
8,2009-08-06 00:00:00+00:00,Pengrowth Energy Trust Announces Second Quarte...,Earnings,Neutral,9,Critical
9,2009-08-06 00:00:00+00:00,Supertel Hospitality Reports 2009 Second Quart...,Earnings,Neutral,9,Critical
10,2009-08-06 00:00:00+00:00,GLG Life Tech Corporation to Announce Second Q...,Earnings,Neutral,9,Critical
11,2009-08-06 00:00:00+00:00,SRS Class Action Lawsuit filed 08/05/2009,Litigation,Bearish,6,Medium
12,2009-08-07 00:00:00+00:00,WesternZagros Announces 2009 Second Quarter Re...,Earnings,Neutral,9,Critical
13,2009-08-07 00:00:00+00:00,Constellation Software Inc. Acquisition of Com...,Merger & Acquisition,Neutral,9,Critical
14,2009-08-07 00:00:00+00:00,OneMove(TM) Records its Best Month Ever in July,Market Movement,Neutral,3,Low
15,2009-08-07 00:00:00+00:00,Seacliff Announces Timing of Second Quarter 20...,Earnings,Neutral,9,Critical
16,2009-08-07 00:00:00+00:00,City of Irondale Sues Trinity Medical Center a...,Litigation,Neutral,6,Medium
17,2009-08-07 00:00:00+00:00,Hastings Entertainment Incorporated: Character...,Other,Neutral,1,Low
18,2009-08-07 00:00:00+00:00,Government of Canada Helps Merritt Youth Prepa...,Layoffs,Neutral,7,High
19,2009-08-07 00:00:00+00:00,Golconda Provides Update,Product Launch,Neutral,7,High