## 1. Imports

In [1]:
import os
import gc
import warnings

import numpy as np
import pandas as pd

import networkx as nx

from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics.pairwise import cosine_similarity

from tqdm.auto import tqdm

warnings.filterwarnings("ignore")

tqdm.pandas()

## 2. Paths

In [2]:
PROJECT_PATH = "/content/drive/MyDrive/FinSight_AI"

DATA_PATH = os.path.join(
    PROJECT_PATH,
    "data"
)

PROCESSED_PATH = os.path.join(
    DATA_PATH,
    "processed"
)

EVENT_PATH = os.path.join(
    PROCESSED_PATH,
    "event_propagation"
)

os.makedirs(
    EVENT_PATH,
    exist_ok=True
)

## 3. Load Datasets

In [3]:
FINANCIAL_DATASET = os.path.join(
    PROCESSED_PATH,
    "financial_intelligence",
    "financial_intelligence_dataset.parquet"
)

COMPANY_ANALYTICS = os.path.join(
    PROCESSED_PATH,
    "company_analytics",
    "company_analytics.parquet"
)

TIMELINE_DATA = os.path.join(
    PROCESSED_PATH,
    "company_timeline",
    "company_event_timeline.parquet"
)

ENTITY_DATA = os.path.join(
    PROCESSED_PATH,
    "entities",
    "news_entities.parquet"
)

financial_df = pd.read_parquet(
    FINANCIAL_DATASET,
    columns=[
        "news_id",
        "ticker",
        "publisher",
        "published_date",
        "final_event",
        "market_signal",
        "final_confidence"
    ]
)

analytics_df = pd.read_parquet(
    COMPANY_ANALYTICS
)

timeline_df = pd.read_parquet(
    TIMELINE_DATA
)

entity_df = pd.read_parquet(
    ENTITY_DATA,
    columns=[
        "news_id",
        "entity",
        "entity_label"
    ]
)

print("Financial :", financial_df.shape)
print("Analytics :", analytics_df.shape)
print("Timeline :", timeline_df.shape)
print("Entities :", entity_df.shape)

Financial : (3215296, 7)
Analytics : (6619, 70)
Timeline : (3215296, 26)
Entities : (7345743, 3)

## 4. Validation

In [4]:
print()

print("Companies :", financial_df["ticker"].nunique())

print("Publishers :", financial_df["publisher"].nunique())

print("Events :", financial_df["final_event"].nunique())

print("Market Signals :", financial_df["market_signal"].nunique())

print("Entity Types :", entity_df["entity_label"].nunique())

Companies : 6619
Publishers : 1047
Events : 30
Market Signals : 4
Entity Types : 21

## 5. Event Statistics

In [5]:
event_statistics = (

    financial_df

    .groupby(

        "final_event"

    )

    .agg(

        total_news=("news_id","count"),

        companies=("ticker","nunique"),

        publishers=("publisher","nunique"),

        avg_confidence=("final_confidence","mean"),

        bullish=(

            "market_signal",

            lambda x:(x=="Bullish").sum()

        ),

        bearish=(

            "market_signal",

            lambda x:(x=="Bearish").sum()

        ),

        neutral=(

            "market_signal",

            lambda x:(x=="Neutral").sum()

        )

    )

    .reset_index()

)

display(event_statistics)

,final_event,total_news,companies,publishers,avg_confidence,bullish,bearish,neutral
0,Analyst Rating,277248,5178,311,0.899277,78310,12691,184055
1,Bankruptcy,3043,1142,93,0.904568,37,1826,1062
2,Commodity,176547,4965,450,0.840405,9460,7778,157888
3,Credit Rating,36358,3955,208,0.956756,2697,1122,32488
4,Cryptocurrency,13739,2556,187,0.773372,119,74,13543
5,Cybersecurity,7612,1817,171,0.803114,155,928,6485
6,Dividend,110494,3981,172,0.956925,107799,39,1144
7,ESG,34695,4120,250,0.746687,118,26,34550
8,Earnings,567435,5694,396,0.944125,109435,45312,390842
9,Economic Data,14319,2222,172,0.859742,0,0,14319
10,Executive Change,45456,4348,216,0.917445,1451,507,43475
11,Fraud,4692,1499,115,0.839715,95,2486,2012
12,Funding,32578,4571,226,0.863721,3207,763,28445
13,IPO,17891,3362,184,0.875808,834,237,16764
14,Insider Trading,9530,2453,73,0.942794,118,17,9395
15,Layoffs,32802,4324,264,0.745874,14,857,31873
16,Litigation,17450,2792,163,0.839660,555,3104,13652
17,Market Movement,469086,6367,532,0.833923,0,0,469086
18,Merger & Acquisition,231793,5653,397,0.790391,4517,925,226261
19,Monetary Policy,26738,3405,186,0.864893,0,0,26738
20,Options Activity,43010,3651,190,0.860409,302,95,42603
21,Other,137156,5660,300,0.678070,0,0,137156
22,Partnership,40699,4291,184,0.882667,2166,467,38032
23,Product Launch,654857,6466,787,0.758737,6757,287,647785
24,Regulatory Approval,24951,2559,176,0.921823,10505,662,13594
25,Revenue Guidance,34374,4417,220,0.864971,5011,2707,26227
26,Share Buyback,19410,3703,184,0.812230,8162,6,11154
27,Stock Split,6946,2490,121,0.760280,173,11,6761
28,Technical Analysis,113179,5734,433,0.786142,1557,298,111304
29,Trading Halt,11208,3145,118,0.848943,77,42,11088

## 6. Event Timeline Statistics

In [6]:
financial_df["event_date"] = pd.to_datetime(

    financial_df["published_date"]

).dt.date

event_timeline = (

    financial_df

    .groupby(

        [

            "event_date",

            "final_event"

        ]

    )

    .size()

    .reset_index(

        name="news_count"

    )

)

display(event_timeline.head())

   event_date      final_event  news_count
0  2009-02-14   Cryptocurrency           1
1  2009-04-27   Product Launch           2
2  2009-04-29   Product Launch           1
3  2009-05-22   Product Launch           1
4  2009-05-27  Market Movement           3

## 7. Event Diversity

In [7]:
event_diversity = (

    financial_df

    .groupby(

        "final_event"

    )

    .agg(

        companies=("ticker","nunique"),

        publishers=("publisher","nunique"),

        signals=("market_signal","nunique")

    )

    .reset_index()

)

display(event_diversity)

             final_event  companies  publishers  signals
0         Analyst Rating       5178         311        4
1             Bankruptcy       1142          93        4
2              Commodity       4965         450        4
3          Credit Rating       3955         208        4
4         Cryptocurrency       2556         187        4
5          Cybersecurity       1817         171        4
6               Dividend       3981         172        4
7                    ESG       4120         250        4
8               Earnings       5694         396        4
9          Economic Data       2222         172        1
10      Executive Change       4348         216        4
11                 Fraud       1499         115        4
12               Funding       4571         226        4
13                   IPO       3362         184        4
14       Insider Trading       2453          73        3
15               Layoffs       4324         264        4
16            Litigation       2792         163        4
17       Market Movement       6367         532        1
18  Merger & Acquisition       5653         397        4
19       Monetary Policy       3405         186        1
20      Options Activity       3651         190        4
21                 Other       5660         300        1
22           Partnership       4291         184        4
23        Product Launch       6466         787        4
24   Regulatory Approval       2559         176        4
25      Revenue Guidance       4417         220        4
26         Share Buyback       3703         184        4
27           Stock Split       2490         121        4
28    Technical Analysis       5734         433        4
29          Trading Halt       3145         118        4

## 8. Merge Statistics

In [8]:
event_statistics = event_statistics.merge(

    event_diversity,

    on="final_event",

    suffixes=(

        "",

        "_check"

    )

)

event_statistics = event_statistics.loc[

    :,

    ~event_statistics.columns.str.endswith(

        "_check"

    )

]

display(event_statistics.head())

,final_event,total_news,companies,publishers,avg_confidence,bullish,bearish,neutral,signals
0,Analyst Rating,277248,5178,311,0.899277,78310,12691,184055,4
1,Bankruptcy,3043,1142,93,0.904568,37,1826,1062,4
2,Commodity,176547,4965,450,0.840405,9460,7778,157888,4
3,Credit Rating,36358,3955,208,0.956756,2697,1122,32488,4
4,Cryptocurrency,13739,2556,187,0.773372,119,74,13543,4

## 9. Save

In [9]:
event_statistics.to_parquet(

    os.path.join(

        EVENT_PATH,

        "event_statistics.parquet"

    ),

    index=False

)

event_timeline.to_parquet(

    os.path.join(

        EVENT_PATH,

        "event_timeline.parquet"

    ),

    index=False

)

gc.collect()

print("Saved.")

Saved.

## 10. Event -> Company Graph

In [10]:
event_company_graph = (

    financial_df

    .groupby(

        [

            "final_event",

            "ticker"

        ],

        observed=True

    )

    .agg(

        news_count=("news_id", "count"),

        avg_confidence=("final_confidence", "mean")

    )

    .reset_index()

)

event_company_graph["source"] = (

    "EVENT_"

    + event_company_graph["final_event"]

        .str.replace(" ", "_", regex=False)

)

event_company_graph["target"] = (

    "COMP_"

    + event_company_graph["ticker"].astype(str)

)

event_company_graph["relation"] = "AFFECTS"

event_company_graph = event_company_graph[

    [

        "source",

        "target",

        "relation",

        "news_count",

        "avg_confidence"

    ]

]

print(event_company_graph.shape)

display(event_company_graph.head())

(116520, 5)

                 source     target relation  news_count  avg_confidence
0  EVENT_Analyst_Rating     COMP_A  AFFECTS         207        0.904322
1  EVENT_Analyst_Rating    COMP_AA  AFFECTS         301        0.948551
2  EVENT_Analyst_Rating   COMP_AAC  AFFECTS          18        0.865650
3  EVENT_Analyst_Rating   COMP_AAL  AFFECTS         114        0.920354
4  EVENT_Analyst_Rating  COMP_AAMC  AFFECTS           2        0.851250

## 11. Save Company Graph

In [12]:
event_company_graph.to_parquet(

    os.path.join(

        EVENT_PATH,

        "event_company_graph.parquet"

    ),

    index=False

)

print("Saved Event -> Company Graph")

Saved Event -> Company Graph

## 12. Event -> Publisher Graph

In [13]:
event_publisher_graph = (

    financial_df

    .groupby(

        [

            "final_event",

            "publisher"

        ],

        observed=True

    )

    .agg(

        news_count=("news_id", "count"),

        avg_confidence=("final_confidence", "mean")

    )

    .reset_index()

)

event_publisher_graph["source"] = (

    "EVENT_"

    + event_publisher_graph["final_event"]

        .str.replace(" ", "_", regex=False)

)

event_publisher_graph["target"] = (

    "PUB_"

    + event_publisher_graph["publisher"]

        .astype(str)

        .str.replace(" ", "_", regex=False)

)

event_publisher_graph["relation"] = "REPORTED_BY"

event_publisher_graph = event_publisher_graph[

    [

        "source",

        "target",

        "relation",

        "news_count",

        "avg_confidence"

    ]

]

print(event_publisher_graph.shape)

display(event_publisher_graph.head())

(7479, 5)

,source,target,relation,news_count,avg_confidence
0,EVENT_Analyst_Rating,PUB_ABNNewswire,REPORTED_BY,2,1.000000
1,EVENT_Analyst_Rating,PUB_Aaron_Levitt,REPORTED_BY,4,0.787300
2,EVENT_Analyst_Rating,PUB_Abe_Raymond,REPORTED_BY,16,0.827619
3,EVENT_Analyst_Rating,PUB_Accesswire,REPORTED_BY,211,0.829685
4,EVENT_Analyst_Rating,PUB_Adam_Parker,REPORTED_BY,6,0.833333

## 13. Save Publisher Graph

In [15]:
event_publisher_graph.to_parquet(

    os.path.join(

        EVENT_PATH,

        "event_publisher_graph.parquet"

    ),

    index=False

)

print("Saved Event -> Publisher Graph")

Saved Event -> Publisher Graph

## 14. Event -> Entity Graph

In [16]:
event_entity = (

    financial_df

    [

        [

            "news_id",

            "final_event"

        ]

    ]

    .merge(

        entity_df,

        on="news_id",

        how="inner"

    )

)

In [17]:
print(event_entity.shape)

display(event_entity.head())

(7345743, 4)

   news_id      final_event               entity      entity_label
0        3  Market Movement       Biggest Movers               ORG
1        5   Analyst Rating         Price Target  FINANCIAL_METRIC
2        5   Analyst Rating            Maintains    ANALYST_ACTION
3        5   Analyst Rating              Neutral    ANALYST_ACTION
4        5   Analyst Rating  Price Target to $88      PRICE_TARGET

## 15. Build Event -> Entity Graph

In [18]:
event_entity_graph = (

    event_entity

    .groupby(

        [

            "final_event",

            "entity",

            "entity_label"

        ],

        observed=True

    )

    .size()

    .reset_index(name="mentions")

)

event_entity_graph["source"] = (

    "EVENT_"

    + event_entity_graph["final_event"]

        .str.replace(" ", "_", regex=False)

)

event_entity_graph["target"] = (

    "ENTITY_"

    + event_entity_graph["entity"]

        .astype(str)

        .str.replace(" ", "_", regex=False)

)

event_entity_graph["relation"] = "MENTIONS"

event_entity_graph = event_entity_graph[

    [

        "source",

        "target",

        "relation",

        "mentions",

        "entity_label"

    ]

]

print(event_entity_graph.shape)

display(event_entity_graph.head())

(1198728, 5)

                 source              target  relation  mentions entity_label
0  EVENT_Analyst_Rating  ENTITY_#1_Customer  MENTIONS         1        MONEY
1  EVENT_Analyst_Rating  ENTITY_#1_Priority  MENTIONS         1        MONEY
2  EVENT_Analyst_Rating      ENTITY_#1_Rank  MENTIONS         4        MONEY
3  EVENT_Analyst_Rating         ENTITY_$_32  MENTIONS         1        MONEY
4  EVENT_Analyst_Rating          ENTITY_$_7  MENTIONS         1        MONEY

## 16. Save Entity Graph

In [20]:
event_entity_graph.to_parquet(

    os.path.join(

        EVENT_PATH,

        "event_entity_graph.parquet"

    ),

    index=False

)

print("Saved Event -> Entity Graph")

Saved Event -> Entity Graph

## 17. Free Memory

In [21]:
del event_entity

gc.collect()

print("Memory Cleared")

Memory Cleared

## 18. Event Influence Score

In [22]:
event_statistics["timeline_days"] = (

    event_timeline

    .groupby("final_event")["event_date"]

    .nunique()

    .reindex(event_statistics["final_event"])

    .values

)

scaler = MinMaxScaler()

scaled = scaler.fit_transform(

    event_statistics[

        [

            "companies",

            "publishers",

            "avg_confidence",

            "timeline_days"

        ]

    ]

)

scaled = pd.DataFrame(

    scaled,

    columns=[

        "companies_score",

        "publishers_score",

        "confidence_score",

        "timeline_score"

    ]

)

event_statistics = pd.concat(

    [

        event_statistics,

        scaled

    ],

    axis=1

)

event_statistics["influence_score"] = (

      0.35 * event_statistics["companies_score"]

    + 0.25 * event_statistics["publishers_score"]

    + 0.25 * event_statistics["confidence_score"]

    + 0.15 * event_statistics["timeline_score"]

)

event_statistics["influence_score"] *= 100

event_statistics["influence_score"] = (

    event_statistics["influence_score"]

    .round(2)

)

display(

    event_statistics[

        [

            "final_event",

            "influence_score"

        ]

    ]

    .sort_values(

        "influence_score",

        ascending=False

    )

)

             final_event  influence_score
23        Product Launch            82.23
17       Market Movement            78.84
8               Earnings            78.41
2              Commodity            66.03
0         Analyst Rating            65.78
28    Technical Analysis            65.30
18  Merger & Acquisition            64.38
6               Dividend            59.04
10      Executive Change            58.01
3          Credit Rating            57.10
12               Funding            54.17
22           Partnership            52.71
25      Revenue Guidance            52.62
21                 Other            50.53
20      Options Activity            46.43
13                   IPO            44.20
15               Layoffs            43.75
24   Regulatory Approval            43.26
19       Monetary Policy            42.95
7                    ESG            42.19
26         Share Buyback            40.91
14       Insider Trading            37.16
16            Litigation            36.74
29          Trading Halt            36.22
9          Economic Data            33.56
4         Cryptocurrency            28.60
5          Cybersecurity            22.69
27           Stock Split            22.21
11                 Fraud            21.11
1             Bankruptcy            21.01

## 19. Event Impact Category

In [23]:
event_statistics["impact_category"] = pd.qcut(

    event_statistics["influence_score"],

    q=4,

    labels=[

        "Low",

        "Medium",

        "High",

        "Very High"

    ]

)

display(

    event_statistics[

        [

            "final_event",

            "influence_score",

            "impact_category"

        ]

    ]

    .sort_values(

        "influence_score",

        ascending=False

    )

)

             final_event  influence_score impact_category
23        Product Launch            82.23       Very High
17       Market Movement            78.84       Very High
8               Earnings            78.41       Very High
2              Commodity            66.03       Very High
0         Analyst Rating            65.78       Very High
28    Technical Analysis            65.30       Very High
18  Merger & Acquisition            64.38       Very High
6               Dividend            59.04       Very High
10      Executive Change            58.01            High
3          Credit Rating            57.10            High
12               Funding            54.17            High
22           Partnership            52.71            High
25      Revenue Guidance            52.62            High
21                 Other            50.53            High
20      Options Activity            46.43            High
13                   IPO            44.20          Medium
15               Layoffs            43.75          Medium
24   Regulatory Approval            43.26          Medium
19       Monetary Policy            42.95          Medium
7                    ESG            42.19          Medium
26         Share Buyback            40.91          Medium
14       Insider Trading            37.16          Medium
16            Litigation            36.74             Low
29          Trading Halt            36.22             Low
9          Economic Data            33.56             Low
4         Cryptocurrency            28.60             Low
5          Cybersecurity            22.69             Low
27           Stock Split            22.21             Low
11                 Fraud            21.11             Low
1             Bankruptcy            21.01             Low

## 20. Save Influence Dataset

In [24]:
event_statistics.to_parquet(

    os.path.join(

        EVENT_PATH,

        "event_influence.parquet"

    ),

    index=False

)

print("Saved Event Influence")

Saved Event Influence

## 21. Company Influence Score

In [25]:
company_influence = (

    financial_df

    .groupby("ticker")

    .agg(

        total_news=("news_id","count"),

        event_types=("final_event","nunique"),

        publishers=("publisher","nunique"),

        avg_confidence=("final_confidence","mean")

    )

    .reset_index()

)

## 22. Normalize Company Influence

In [26]:
scaled = MinMaxScaler().fit_transform(

    company_influence[

        [

            "total_news",

            "event_types",

            "publishers",

            "avg_confidence"

        ]

    ]

)

scaled = pd.DataFrame(

    scaled,

    columns=[

        "news_score",

        "event_score",

        "publisher_score",

        "confidence_score"

    ]

)

company_influence = pd.concat(

    [

        company_influence,

        scaled

    ],

    axis=1

)

company_influence["company_influence_score"] = (

      0.35 * company_influence["news_score"]

    + 0.30 * company_influence["event_score"]

    + 0.20 * company_influence["publisher_score"]

    + 0.15 * company_influence["confidence_score"]

)

company_influence["company_influence_score"] *= 100

company_influence["company_influence_score"] = (

    company_influence["company_influence_score"]

    .round(2)

)

display(

    company_influence

    .sort_values(

        "company_influence_score",

        ascending=False

    )

    .head(20)

)

,ticker,total_news,event_types,publishers,avg_confidence,news_score,event_score,publisher_score,confidence_score,company_influence_score
2746,HD,4415,30,232,0.829553,0.872332,1.000000,0.927711,0.659106,88.97
3486,KR,5061,30,168,0.827025,1.000000,1.000000,0.670683,0.654051,88.22
2523,GILD,4938,30,169,0.820607,0.975692,1.000000,0.674699,0.641213,87.26
2159,FDX,4358,30,209,0.831489,0.861067,1.000000,0.835341,0.662979,86.79
1555,DISH,4544,30,153,0.823487,0.897826,1.000000,0.610442,0.646974,83.34
3386,JWN,4361,30,162,0.823712,0.861660,1.000000,0.646586,0.647424,82.80
3778,MDT,4421,30,134,0.851852,0.873518,1.000000,0.534137,0.703704,81.81
2144,FCX,4253,30,160,0.816144,0.840316,1.000000,0.638554,0.632288,81.67
1711,EA,3909,30,176,0.829336,0.772332,1.000000,0.702811,0.658672,80.97
2633,GRPN,4020,30,165,0.828431,0.794269,1.000000,0.658635,0.656862,80.83
505,AXP,3741,30,188,0.828504,0.739130,1.000000,0.751004,0.657008,80.74
6008,TWX,4077,30,158,0.804357,0.805534,1.000000,0.630522,0.608714,79.93
4067,MYL,4416,30,118,0.830914,0.872530,1.000000,0.469880,0.661828,79.86
693,BLK,3886,30,160,0.837077,0.767787,1.000000,0.638554,0.674153,79.76
3471,KO,2848,30,250,0.827965,0.562648,1.000000,1.000000,0.655929,79.53
6382,WDC,4177,29,143,0.837468,0.825296,0.965517,0.570281,0.674937,79.38
6267,VMW,4002,29,156,0.840013,0.790711,0.965517,0.622490,0.680027,79.29
3982,MS,3157,29,224,0.839638,0.623715,0.965517,0.895582,0.679277,78.90
1335,CSX,3931,30,139,0.842038,0.776680,1.000000,0.554217,0.684076,78.53
2709,HAL,3608,30,166,0.836695,0.712846,1.000000,0.662651,0.673389,78.30

## 23. Save Company Influence

In [27]:
company_influence.to_parquet(

    os.path.join(

        EVENT_PATH,

        "company_influence.parquet"

    ),

    index=False

)

print("Saved Company Influence")

Saved Company Influence

## 24. Event Fingerprints

In [28]:
def build_event_fingerprint(row):

    fp = []

    if row["impact_category"] == "Very High":
        fp.append("High Impact")

    if row["avg_confidence"] > 0.90:
        fp.append("Reliable")

    if row["companies"] > event_statistics["companies"].median():
        fp.append("Broad Coverage")

    if row["publishers"] > event_statistics["publishers"].median():
        fp.append("Widely Reported")

    return ", ".join(fp)

event_statistics["event_fingerprint"] = (

    event_statistics.apply(

        build_event_fingerprint,

        axis=1

    )

)

display(

    event_statistics[

        [

            "final_event",

            "event_fingerprint"

        ]

    ]

)

             final_event                                  event_fingerprint
0         Analyst Rating       High Impact, Broad Coverage, Widely Reported
1             Bankruptcy                                           Reliable
2              Commodity       High Impact, Broad Coverage, Widely Reported
3          Credit Rating                          Reliable, Widely Reported
4         Cryptocurrency
5          Cybersecurity
6               Dividend              High Impact, Reliable, Broad Coverage
7                    ESG                    Broad Coverage, Widely Reported
8               Earnings  High Impact, Reliable, Broad Coverage, Widely ...
9          Economic Data
10      Executive Change          Reliable, Broad Coverage, Widely Reported
11                 Fraud
12               Funding                    Broad Coverage, Widely Reported
13                   IPO
14       Insider Trading                                           Reliable
15               Layoffs                    Broad Coverage, Widely Reported
16            Litigation
17       Market Movement       High Impact, Broad Coverage, Widely Reported
18  Merger & Acquisition       High Impact, Broad Coverage, Widely Reported
19       Monetary Policy
20      Options Activity                                    Widely Reported
21                 Other                    Broad Coverage, Widely Reported
22           Partnership                                     Broad Coverage
23        Product Launch       High Impact, Broad Coverage, Widely Reported
24   Regulatory Approval                                           Reliable
25      Revenue Guidance                    Broad Coverage, Widely Reported
26         Share Buyback
27           Stock Split
28    Technical Analysis       High Impact, Broad Coverage, Widely Reported
29          Trading Halt

## 25. Explainability

In [29]:
event_statistics["explanation"] = (

    "Companies: "

    + event_statistics["companies"].astype(str)

    + " | Publishers: "

    + event_statistics["publishers"].astype(str)

    + " | Confidence: "

    + event_statistics["avg_confidence"]

        .round(2)

        .astype(str)

    + " | Timeline Days: "

    + event_statistics["timeline_days"].astype(str)

)

display(

    event_statistics[

        [

            "final_event",

            "explanation"

        ]

    ]

)

             final_event                                        explanation
0         Analyst Rating  Companies: 5178 | Publishers: 311 | Confidence...
1             Bankruptcy  Companies: 1142 | Publishers: 93 | Confidence:...
2              Commodity  Companies: 4965 | Publishers: 450 | Confidence...
3          Credit Rating  Companies: 3955 | Publishers: 208 | Confidence...
4         Cryptocurrency  Companies: 2556 | Publishers: 187 | Confidence...
5          Cybersecurity  Companies: 1817 | Publishers: 171 | Confidence...
6               Dividend  Companies: 3981 | Publishers: 172 | Confidence...
7                    ESG  Companies: 4120 | Publishers: 250 | Confidence...
8               Earnings  Companies: 5694 | Publishers: 396 | Confidence...
9          Economic Data  Companies: 2222 | Publishers: 172 | Confidence...
10      Executive Change  Companies: 4348 | Publishers: 216 | Confidence...
11                 Fraud  Companies: 1499 | Publishers: 115 | Confidence...
12               Funding  Companies: 4571 | Publishers: 226 | Confidence...
13                   IPO  Companies: 3362 | Publishers: 184 | Confidence...
14       Insider Trading  Companies: 2453 | Publishers: 73 | Confidence:...
15               Layoffs  Companies: 4324 | Publishers: 264 | Confidence...
16            Litigation  Companies: 2792 | Publishers: 163 | Confidence...
17       Market Movement  Companies: 6367 | Publishers: 532 | Confidence...
18  Merger & Acquisition  Companies: 5653 | Publishers: 397 | Confidence...
19       Monetary Policy  Companies: 3405 | Publishers: 186 | Confidence...
20      Options Activity  Companies: 3651 | Publishers: 190 | Confidence...
21                 Other  Companies: 5660 | Publishers: 300 | Confidence...
22           Partnership  Companies: 4291 | Publishers: 184 | Confidence...
23        Product Launch  Companies: 6466 | Publishers: 787 | Confidence...
24   Regulatory Approval  Companies: 2559 | Publishers: 176 | Confidence...
25      Revenue Guidance  Companies: 4417 | Publishers: 220 | Confidence...
26         Share Buyback  Companies: 3703 | Publishers: 184 | Confidence...
27           Stock Split  Companies: 2490 | Publishers: 121 | Confidence...
28    Technical Analysis  Companies: 5734 | Publishers: 433 | Confidence...
29          Trading Halt  Companies: 3145 | Publishers: 118 | Confidence...

## 26. Save Updated Statistics

In [30]:
event_statistics.to_parquet(

    os.path.join(

        EVENT_PATH,

        "event_statistics.parquet"

    ),

    index=False

)

gc.collect()

print("Updated Event Statistics Saved")

Updated Event Statistics Saved

## 27. Build Event Graph (NetworkX)

In [37]:
event_company = (

    financial_df

    .groupby(

        [

            "final_event",

            "ticker"

        ]

    )

    .size()

    .reset_index(name="count")

)

In [47]:
event_matrix = (

    event_company

    .pivot_table(

        index="ticker",

        columns="final_event",

        values="count",

        fill_value=0

    )

)

In [48]:
from sklearn.metrics.pairwise import cosine_similarity

similarity = cosine_similarity(

    event_matrix.T

)

similarity = pd.DataFrame(

    similarity,

    index=event_matrix.columns,

    columns=event_matrix.columns

)

In [49]:
edges = []

threshold = 0.35

for i in similarity.index:

    for j in similarity.columns:

        if i >= j:
            continue

        score = similarity.loc[i, j]

        if score >= threshold:

            edges.append(

                [

                    i,

                    j,

                    score

                ]

            )

event_edge_df = pd.DataFrame(

    edges,

    columns=[

        "event_a",

        "event_b",

        "weight"

    ]

)

## 28. Build NetworkX Graph

In [50]:
G = nx.Graph()

for row in event_edge_df.itertuples(index=False):

    G.add_edge(

        row.event_a,

        row.event_b,

        weight=row.weight

    )

print("Nodes :", G.number_of_nodes())

print("Edges :", G.number_of_edges())

Nodes : 29
Edges : 221

In [58]:
all_events = sorted(
    financial_df["final_event"].unique()
)

for event in all_events:

    if event not in G:

        G.add_node(event)

print("Nodes :", G.number_of_nodes())
print("Edges :", G.number_of_edges())

Nodes : 30
Edges : 221

In [59]:
all_events = set(financial_df["final_event"].unique())

graph_events = set(G.nodes())

missing = all_events - graph_events

print("Missing Events:")
print(missing)

Missing Events:
set()

## 29. Degree Centrality

In [60]:
degree = nx.degree_centrality(G)

degree = (

    pd.DataFrame(

        degree.items(),

        columns=[

            "final_event",

            "degree_centrality"

        ]

    )

)

display(

    degree.sort_values(

        "degree_centrality",

        ascending=False

    )

)

             final_event  degree_centrality
17        Product Launch           0.896552
12       Market Movement           0.827586
18      Revenue Guidance           0.827586
21    Technical Analysis           0.793103
10               Layoffs           0.793103
0         Analyst Rating           0.758621
15                 Other           0.758621
4               Earnings           0.758621
5       Executive Change           0.724138
13  Merger & Acquisition           0.724138
14      Options Activity           0.689655
16           Partnership           0.655172
19         Share Buyback           0.655172
11            Litigation           0.586207
22          Trading Halt           0.586207
8                    IPO           0.551724
7                Funding           0.551724
20           Stock Split           0.448276
1          Credit Rating           0.448276
6                  Fraud           0.413793
2               Dividend           0.413793
26         Economic Data           0.310345
27       Monetary Policy           0.310345
9        Insider Trading           0.241379
3                    ESG           0.172414
25        Cryptocurrency           0.137931
28   Regulatory Approval           0.137931
23            Bankruptcy           0.034483
24             Commodity           0.034483
29         Cybersecurity           0.000000

In [61]:
event_centrality["isolated"] = (
    event_centrality["degree_centrality"] == 0
)

event_centrality["graph_status"] = np.where(
    event_centrality["isolated"],
    "Isolated Event",
    "Connected Event"
)

display(event_centrality)

,final_event,degree_centrality,betweenness,closeness,eigenvector,isolated,graph_status
0,Analyst Rating,0.785714,0.026455,0.823529,0.266636,False,Connected Event
1,Credit Rating,0.464286,0.000000,0.651163,0.133294,False,Connected Event
2,Dividend,0.428571,0.000000,0.636364,0.129534,False,Connected Event
3,ESG,0.178571,0.021164,0.538462,0.051468,False,Connected Event
4,Earnings,0.785714,0.007937,0.823529,0.268049,False,Connected Event
5,Executive Change,0.750000,0.000000,0.800000,0.248416,False,Connected Event
6,Fraud,0.428571,0.000000,0.636364,0.122930,False,Connected Event
7,Funding,0.571429,0.005291,0.700000,0.170663,False,Connected Event
8,IPO,0.571429,0.002646,0.700000,0.163523,False,Connected Event
9,Insider Trading,0.250000,0.000000,0.549020,0.077390,False,Connected Event
10,Layoffs,0.821429,0.095238,0.848485,0.232177,False,Connected Event
11,Litigation,0.607143,0.021164,0.717949,0.172034,False,Connected Event
12,Market Movement,0.857143,0.018519,0.875000,0.281306,False,Connected Event
13,Merger & Acquisition,0.750000,0.000000,0.800000,0.249418,False,Connected Event
14,Options Activity,0.714286,0.042328,0.777778,0.228927,False,Connected Event
15,Other,0.785714,0.039683,0.823529,0.221208,False,Connected Event
16,Partnership,0.678571,0.026455,0.756757,0.190745,False,Connected Event
17,Product Launch,0.928571,0.037037,0.933333,0.286729,False,Connected Event
18,Revenue Guidance,0.857143,0.082011,0.875000,0.253643,False,Connected Event
19,Share Buyback,0.678571,0.010582,0.756757,0.216684,False,Connected Event
20,Stock Split,0.464286,0.000000,0.651163,0.139502,False,Connected Event
21,Technical Analysis,0.821429,0.037037,0.848485,0.247655,False,Connected Event
22,Trading Halt,0.607143,0.039683,0.717949,0.169261,False,Connected Event
23,Bankruptcy,0.035714,0.000000,0.466667,0.008141,False,Connected Event
24,Commodity,0.035714,0.000000,0.474576,0.011938,False,Connected Event
25,Cryptocurrency,0.142857,0.000000,0.518519,0.027792,False,Connected Event
26,Economic Data,0.321429,0.018519,0.595745,0.077391,False,Connected Event
27,Monetary Policy,0.321429,0.000000,0.595745,0.086450,False,Connected Event
28,Regulatory Approval,0.142857,0.000000,0.518519,0.035007,False,Connected Event

## 30. Betweenness Centrality

In [62]:
betweenness = nx.betweenness_centrality(

    G,

    weight="weight"

)

betweenness = (

    pd.DataFrame(

        betweenness.items(),

        columns=[

            "final_event",

            "betweenness"

        ]

    )

)

display(

    betweenness.sort_values(

        "betweenness",

        ascending=False

    )

)

             final_event  betweenness
10               Layoffs     0.088670
18      Revenue Guidance     0.076355
14      Options Activity     0.039409
15                 Other     0.036946
22          Trading Halt     0.036946
21    Technical Analysis     0.034483
17        Product Launch     0.034483
16           Partnership     0.024631
0         Analyst Rating     0.024631
11            Litigation     0.019704
3                    ESG     0.019704
26         Economic Data     0.017241
12       Market Movement     0.017241
19         Share Buyback     0.009852
4               Earnings     0.007389
7                Funding     0.004926
8                    IPO     0.002463
9        Insider Trading     0.000000
2               Dividend     0.000000
1          Credit Rating     0.000000
6                  Fraud     0.000000
5       Executive Change     0.000000
13  Merger & Acquisition     0.000000
20           Stock Split     0.000000
24             Commodity     0.000000
23            Bankruptcy     0.000000
25        Cryptocurrency     0.000000
27       Monetary Policy     0.000000
28   Regulatory Approval     0.000000
29         Cybersecurity     0.000000

## 31. Closeness Centrality

In [63]:
closeness = nx.closeness_centrality(G)

closeness = (

    pd.DataFrame(

        closeness.items(),

        columns=[

            "final_event",

            "closeness"

        ]

    )

)

display(

    closeness.sort_values(

        "closeness",

        ascending=False

    )

)

             final_event  closeness
17        Product Launch   0.901149
12       Market Movement   0.844828
18      Revenue Guidance   0.844828
21    Technical Analysis   0.819227
10               Layoffs   0.819227
0         Analyst Rating   0.795132
15                 Other   0.795132
4               Earnings   0.795132
5       Executive Change   0.772414
13  Merger & Acquisition   0.772414
14      Options Activity   0.750958
16           Partnership   0.730662
19         Share Buyback   0.730662
11            Litigation   0.693192
22          Trading Halt   0.693192
8                    IPO   0.675862
7                Funding   0.675862
20           Stock Split   0.628709
1          Credit Rating   0.628709
6                  Fraud   0.614420
2               Dividend   0.614420
26         Economic Data   0.575202
27       Monetary Policy   0.575202
9        Insider Trading   0.530088
3                    ESG   0.519894
25        Cryptocurrency   0.500639
28   Regulatory Approval   0.500639
24             Commodity   0.458212
23            Bankruptcy   0.450575
29         Cybersecurity   0.000000

## 32. Eigenvector Centrality

In [64]:
eigen = nx.eigenvector_centrality(

    G,

    max_iter=1000,

    weight="weight"

)

eigen = (

    pd.DataFrame(

        eigen.items(),

        columns=[

            "final_event",

            "eigenvector"

        ]

    )

)

display(

    eigen.sort_values(

        "eigenvector",

        ascending=False

    )

)

             final_event   eigenvector
17        Product Launch  2.867286e-01
12       Market Movement  2.813059e-01
4               Earnings  2.680494e-01
0         Analyst Rating  2.666363e-01
18      Revenue Guidance  2.536433e-01
13  Merger & Acquisition  2.494183e-01
5       Executive Change  2.484163e-01
21    Technical Analysis  2.476549e-01
10               Layoffs  2.321773e-01
14      Options Activity  2.289272e-01
15                 Other  2.212083e-01
19         Share Buyback  2.166844e-01
16           Partnership  1.907450e-01
11            Litigation  1.720337e-01
7                Funding  1.706629e-01
22          Trading Halt  1.692612e-01
8                    IPO  1.635231e-01
20           Stock Split  1.395020e-01
1          Credit Rating  1.332943e-01
2               Dividend  1.295340e-01
6                  Fraud  1.229300e-01
27       Monetary Policy  8.644980e-02
26         Economic Data  7.739147e-02
9        Insider Trading  7.739037e-02
3                    ESG  5.146788e-02
28   Regulatory Approval  3.500707e-02
25        Cryptocurrency  2.779175e-02
24             Commodity  1.193799e-02
23            Bankruptcy  8.140618e-03
29         Cybersecurity  7.158006e-11

## 33. Merge All Centralities

In [65]:
event_centrality = (

    degree

    .merge(

        betweenness,

        on="final_event"

    )

    .merge(

        closeness,

        on="final_event"

    )

    .merge(

        eigen,

        on="final_event"

    )

)

display(event_centrality)

,final_event,degree_centrality,betweenness,closeness,eigenvector
0,Analyst Rating,0.758621,0.024631,0.795132,2.666363e-01
1,Credit Rating,0.448276,0.000000,0.628709,1.332943e-01
2,Dividend,0.413793,0.000000,0.614420,1.295340e-01
3,ESG,0.172414,0.019704,0.519894,5.146788e-02
4,Earnings,0.758621,0.007389,0.795132,2.680494e-01
5,Executive Change,0.724138,0.000000,0.772414,2.484163e-01
6,Fraud,0.413793,0.000000,0.614420,1.229300e-01
7,Funding,0.551724,0.004926,0.675862,1.706629e-01
8,IPO,0.551724,0.002463,0.675862,1.635231e-01
9,Insider Trading,0.241379,0.000000,0.530088,7.739037e-02
10,Layoffs,0.793103,0.088670,0.819227,2.321773e-01
11,Litigation,0.586207,0.019704,0.693192,1.720337e-01
12,Market Movement,0.827586,0.017241,0.844828,2.813059e-01
13,Merger & Acquisition,0.724138,0.000000,0.772414,2.494183e-01
14,Options Activity,0.689655,0.039409,0.750958,2.289272e-01
15,Other,0.758621,0.036946,0.795132,2.212083e-01
16,Partnership,0.655172,0.024631,0.730662,1.907450e-01
17,Product Launch,0.896552,0.034483,0.901149,2.867286e-01
18,Revenue Guidance,0.827586,0.076355,0.844828,2.536433e-01
19,Share Buyback,0.655172,0.009852,0.730662,2.166844e-01
20,Stock Split,0.448276,0.000000,0.628709,1.395020e-01
21,Technical Analysis,0.793103,0.034483,0.819227,2.476549e-01
22,Trading Halt,0.586207,0.036946,0.693192,1.692612e-01
23,Bankruptcy,0.034483,0.000000,0.450575,8.140618e-03
24,Commodity,0.034483,0.000000,0.458212,1.193799e-02
25,Cryptocurrency,0.137931,0.000000,0.500639,2.779175e-02
26,Economic Data,0.310345,0.017241,0.575202,7.739147e-02
27,Monetary Policy,0.310345,0.000000,0.575202,8.644980e-02
28,Regulatory Approval,0.137931,0.000000,0.500639,3.500707e-02
29,Cybersecurity,0.000000,0.000000,0.000000,7.158006e-11

## 34. Save

In [66]:
event_centrality.to_parquet(

    os.path.join(

        EVENT_PATH,

        "event_centrality.parquet"

    ),

    index=False

)

print("Saved Event Centrality")

Saved Event Centrality

## 35. Graph Importance Score

In [67]:
from sklearn.preprocessing import MinMaxScaler

graph_scores = event_centrality[
    [
        "degree_centrality",
        "betweenness",
        "closeness",
        "eigenvector"
    ]
]

scaled = MinMaxScaler().fit_transform(graph_scores)

scaled = pd.DataFrame(

    scaled,

    columns=[

        "degree_scaled",

        "betweenness_scaled",

        "closeness_scaled",

        "eigenvector_scaled"

    ]

)

event_centrality = pd.concat(

    [

        event_centrality,

        scaled

    ],

    axis=1

)

event_centrality["graph_importance"] = (

      0.30 * event_centrality["degree_scaled"]
    + 0.20 * event_centrality["betweenness_scaled"]
    + 0.20 * event_centrality["closeness_scaled"]
    + 0.30 * event_centrality["eigenvector_scaled"]

) * 100

event_centrality["graph_importance"] = (
    event_centrality["graph_importance"]
    .round(2)
)

display(

    event_centrality

    .sort_values(

        "graph_importance",

        ascending=False

    )
)

,final_event,degree_centrality,betweenness,closeness,eigenvector,degree_scaled,betweenness_scaled,closeness_scaled,eigenvector_scaled,graph_importance
18,Revenue Guidance,0.827586,0.076355,0.844828,2.536433e-01,0.923077,0.861111,0.937500,0.884611,90.20
10,Layoffs,0.793103,0.088670,0.819227,2.321773e-01,0.884615,1.000000,0.909091,0.809746,89.01
17,Product Launch,0.896552,0.034483,0.901149,2.867286e-01,1.000000,0.388889,1.000000,1.000000,87.78
12,Market Movement,0.827586,0.017241,0.844828,2.813059e-01,0.923077,0.194444,0.937500,0.981088,79.76
21,Technical Analysis,0.793103,0.034483,0.819227,2.476549e-01,0.884615,0.388889,0.909091,0.863726,78.41
0,Analyst Rating,0.758621,0.024631,0.795132,2.666363e-01,0.846154,0.277778,0.882353,0.929926,76.49
15,Other,0.758621,0.036946,0.795132,2.212083e-01,0.846154,0.416667,0.882353,0.771490,74.51
4,Earnings,0.758621,0.007389,0.795132,2.680494e-01,0.846154,0.083333,0.882353,0.934854,72.74
14,Options Activity,0.689655,0.039409,0.750958,2.289272e-01,0.769231,0.444444,0.833333,0.798411,72.58
13,Merger & Acquisition,0.724138,0.000000,0.772414,2.494183e-01,0.807692,0.000000,0.857143,0.869876,67.47
5,Executive Change,0.724138,0.000000,0.772414,2.484163e-01,0.807692,0.000000,0.857143,0.866381,67.37
16,Partnership,0.655172,0.024631,0.730662,1.907450e-01,0.730769,0.277778,0.810811,0.665246,63.65
19,Share Buyback,0.655172,0.009852,0.730662,2.166844e-01,0.730769,0.111111,0.810811,0.755713,63.03
22,Trading Halt,0.586207,0.036946,0.693192,1.692612e-01,0.653846,0.416667,0.769231,0.590318,61.04
11,Litigation,0.586207,0.019704,0.693192,1.720337e-01,0.653846,0.222222,0.769231,0.599988,57.44
7,Funding,0.551724,0.004926,0.675862,1.706629e-01,0.615385,0.055556,0.750000,0.595207,52.43
8,IPO,0.551724,0.002463,0.675862,1.635231e-01,0.615385,0.027778,0.750000,0.570306,51.13
20,Stock Split,0.448276,0.000000,0.628709,1.395020e-01,0.500000,0.000000,0.697674,0.486530,43.55
1,Credit Rating,0.448276,0.000000,0.628709,1.332943e-01,0.500000,0.000000,0.697674,0.464880,42.90
2,Dividend,0.413793,0.000000,0.614420,1.295340e-01,0.461538,0.000000,0.681818,0.451765,41.04
6,Fraud,0.413793,0.000000,0.614420,1.229300e-01,0.461538,0.000000,0.681818,0.428733,40.34
26,Economic Data,0.310345,0.017241,0.575202,7.739147e-02,0.346154,0.194444,0.638298,0.269912,35.14
27,Monetary Policy,0.310345,0.000000,0.575202,8.644980e-02,0.346154,0.000000,0.638298,0.301504,32.20
9,Insider Trading,0.241379,0.000000,0.530088,7.739037e-02,0.269231,0.000000,0.588235,0.269908,27.94
3,ESG,0.172414,0.019704,0.519894,5.146788e-02,0.192308,0.222222,0.576923,0.179500,27.14
28,Regulatory Approval,0.137931,0.000000,0.500639,3.500707e-02,0.153846,0.000000,0.555556,0.122091,19.39
25,Cryptocurrency,0.137931,0.000000,0.500639,2.779175e-02,0.153846,0.000000,0.555556,0.096927,18.63
24,Commodity,0.034483,0.000000,0.458212,1.193799e-02,0.038462,0.000000,0.508475,0.041635,12.57
23,Bankruptcy,0.034483,0.000000,0.450575,8.140618e-03,0.038462,0.000000,0.500000,0.028391,12.01
29,Cybersecurity,0.000000,0.000000,0.000000,7.158006e-11,0.000000,0.000000,0.000000,0.000000,0.00

## 36. Event Connectivity Level

In [68]:
event_centrality["connectivity_level"] = pd.cut(

    event_centrality["graph_importance"],

    bins=[

        -1,
        20,
        40,
        60,
        80,
        100

    ],

    labels=[

        "Very Low",

        "Low",

        "Medium",

        "High",

        "Very High"

    ]

)

display(

    event_centrality[

        [

            "final_event",

            "graph_importance",

            "connectivity_level"

        ]

    ]

    .sort_values(

        "graph_importance",

        ascending=False

    )

)

             final_event  graph_importance connectivity_level
18      Revenue Guidance             90.20          Very High
10               Layoffs             89.01          Very High
17        Product Launch             87.78          Very High
12       Market Movement             79.76               High
21    Technical Analysis             78.41               High
0         Analyst Rating             76.49               High
15                 Other             74.51               High
4               Earnings             72.74               High
14      Options Activity             72.58               High
13  Merger & Acquisition             67.47               High
5       Executive Change             67.37               High
16           Partnership             63.65               High
19         Share Buyback             63.03               High
22          Trading Halt             61.04               High
11            Litigation             57.44             Medium
7                Funding             52.43             Medium
8                    IPO             51.13             Medium
20           Stock Split             43.55             Medium
1          Credit Rating             42.90             Medium
2               Dividend             41.04             Medium
6                  Fraud             40.34             Medium
26         Economic Data             35.14                Low
27       Monetary Policy             32.20                Low
9        Insider Trading             27.94                Low
3                    ESG             27.14                Low
28   Regulatory Approval             19.39           Very Low
25        Cryptocurrency             18.63           Very Low
24             Commodity             12.57           Very Low
23            Bankruptcy             12.01           Very Low
29         Cybersecurity              0.00           Very Low

## 37. Save Updated Centrality

In [69]:
event_centrality.to_parquet(

    os.path.join(

        EVENT_PATH,

        "event_centrality.parquet"

    ),

    index=False

)

print("Saved Event Centrality")

Saved Event Centrality

## 38. Community Detection

use NetworkX's Greedy Modularity algorithm.

In [70]:
from networkx.algorithms.community import greedy_modularity_communities

communities = list(

    greedy_modularity_communities(

        G,

        weight="weight"

    )

)

print("Communities Found :", len(communities))

Communities Found : 4

## 39. Create Community Table

In [71]:
community_rows = []

for community_id, community in enumerate(communities):

    for event in community:

        community_rows.append(

            {

                "final_event": event,

                "community_id": community_id

            }

        )

event_communities = pd.DataFrame(

    community_rows

)

display(

    event_communities

    .sort_values(

        "community_id"

    )

)

             final_event  community_id
0        Insider Trading             0
1       Options Activity             0
2            Stock Split             0
3        Market Movement             0
4                Funding             0
5               Dividend             0
6   Merger & Acquisition             0
7                    IPO             0
8          Share Buyback             0
9       Executive Change             0
10           Partnership             0
11              Earnings             0
12         Credit Rating             0
13        Analyst Rating             0
14        Product Launch             1
15    Technical Analysis             1
16         Economic Data             1
17               Layoffs             1
18       Monetary Policy             1
19                 Fraud             1
20          Trading Halt             1
21        Cryptocurrency             1
22                 Other             1
23            Litigation             1
24   Regulatory Approval             1
25            Bankruptcy             1
26      Revenue Guidance             2
27             Commodity             2
28                   ESG             2
29         Cybersecurity             3

## 40. Community Size

In [72]:
community_summary = (

    event_communities

    .groupby(

        "community_id"

    )

    .size()

    .reset_index(

        name="events"

    )

)

display(community_summary)

   community_id  events
0             0      14
1             1      12
2             2       3
3             3       1

## 41. Community Statistics

In [73]:
community_statistics = (

    event_communities

    .merge(

        event_statistics,

        on="final_event",

        how="left"

    )

)

display(

    community_statistics.head()

)

,final_event,community_id,total_news,companies,publishers,avg_confidence,bullish,bearish,neutral,signals,timeline_days,companies_score,publishers_score,confidence_score,timeline_score,influence_score,impact_category,event_fingerprint,explanation
0,Insider Trading,0,9530,2453,73,0.942794,118,17,9395,3,2011,0.246243,0.000000,0.949326,0.320513,37.16,Medium,Reliable,Companies: 2453 | Publishers: 73 | Confidence:...
1,Options Activity,0,43010,3651,190,0.860409,302,95,42603,4,2887,0.471262,0.163866,0.653886,0.632479,46.43,High,Widely Reported,Companies: 3651 | Publishers: 190 | Confidence...
2,Stock Split,0,6946,2490,121,0.760280,173,11,6761,4,1915,0.253193,0.067227,0.294815,0.286325,22.21,Low,,Companies: 2490 | Publishers: 121 | Confidence...
3,Market Movement,0,469086,6367,532,0.833923,0,0,469086,1,3816,0.981405,0.642857,0.558905,0.963319,78.84,Very High,"High Impact, Broad Coverage, Widely Reported",Companies: 6367 | Publishers: 532 | Confidence...
4,Funding,0,32578,4571,226,0.863721,3207,763,28445,4,2914,0.644065,0.214286,0.665762,0.642094,54.17,High,"Broad Coverage, Widely Reported",Companies: 4571 | Publishers: 226 | Confidence...

## 42. Automatically Name Communities

In [81]:
COMMUNITY_LABELS = {

    frozenset([
        "Earnings",
        "Revenue Guidance",
        "Analyst Rating"
    ]): "Corporate Performance",

    frozenset([
        "Merger & Acquisition",
        "Partnership",
        "Funding",
        "IPO"
    ]): "Corporate Growth",

    frozenset([
        "Fraud",
        "Bankruptcy",
        "Litigation"
    ]): "Legal & Financial Risk",

    frozenset([
        "Cybersecurity",
        "Cryptocurrency"
    ]): "Digital Assets & Security",

    frozenset([
        "Commodity",
        "Economic Data",
        "Monetary Policy"
    ]): "Macroeconomics",

    frozenset([
        "Dividend",
        "Share Buyback",
        "Stock Split"
    ]): "Capital Allocation"

}


def assign_community_name(events):

    event_set = set(events)

    for key, value in COMMUNITY_LABELS.items():

        if len(event_set & key) >= 2:

            return value

    return ", ".join(events[:3])


community_names = []

for cid, group in community_statistics.groupby("community_id"):

    events = (

        group

        .sort_values(

            "influence_score",

            ascending=False

        )["final_event"]

        .tolist()

    )

    community_names.append({

        "community_id": cid,

        "community_name": assign_community_name(events)

    })

community_names = pd.DataFrame(community_names)

display(community_names)

   community_id                    community_name
0             0             Corporate Performance
1             1            Legal & Financial Risk
2             2  Commodity, Revenue Guidance, ESG
3             3                     Cybersecurity

## 43. Merge Names

In [82]:
event_communities = (

    event_communities

    .merge(

        community_names,

        on="community_id"

    )

)

display(event_communities.head())

,final_event,community_id,community_name_x,community_name_y
0,Insider Trading,0,"Market Movement, Earnings, Analyst Rating",Corporate Performance
1,Options Activity,0,"Market Movement, Earnings, Analyst Rating",Corporate Performance
2,Stock Split,0,"Market Movement, Earnings, Analyst Rating",Corporate Performance
3,Market Movement,0,"Market Movement, Earnings, Analyst Rating",Corporate Performance
4,Funding,0,"Market Movement, Earnings, Analyst Rating",Corporate Performance

## 44. Save Communities

In [83]:
event_communities.to_parquet(

    os.path.join(

        EVENT_PATH,

        "event_communities.parquet"

    ),

    index=False

)

print("Saved Event Communities")

Saved Event Communities

## 45. Event Similarity Matrix

In [84]:
event_matrix = (

    financial_df

    .pivot_table(

        index="ticker",

        columns="final_event",

        values="news_id",

        aggfunc="count",

        fill_value=0

    )

)

print(event_matrix.shape)

(6619, 30)

## 46. Cosine Similarity

In [85]:
similarity = cosine_similarity(

    event_matrix.T

)

similarity = pd.DataFrame(

    similarity,

    index=event_matrix.columns,

    columns=event_matrix.columns

)

display(

    similarity.iloc[:5, :5]

)

final_event,Analyst Rating,Bankruptcy,Commodity,Credit Rating,Cryptocurrency
final_event,,,,,
Analyst Rating,1.000000,0.234433,0.294163,0.439871,0.215582
Bankruptcy,0.234433,1.000000,0.140134,0.140878,0.072553
Commodity,0.294163,0.140134,1.000000,0.189019,0.185245
Credit Rating,0.439871,0.140878,0.189019,1.000000,0.209010
Cryptocurrency,0.215582,0.072553,0.185245,0.209010,1.000000

## 47. Top Similar Events

In [86]:
rows = []

events = similarity.index.tolist()

for i in range(len(events)):

    for j in range(i + 1, len(events)):

        score = similarity.iloc[i, j]

        rows.append({

            "event_1": events[i],

            "event_2": events[j],

            "similarity": round(score, 4)

        })

event_similarity = (

    pd.DataFrame(rows)

    .sort_values(

        "similarity",

        ascending=False

    )

)

display(event_similarity.head(20))

                  event_1               event_2  similarity
7          Analyst Rating              Earnings      0.8929
362       Market Movement        Product Launch      0.8721
212              Earnings       Market Movement      0.8194
418        Product Launch    Technical Analysis      0.8126
16         Analyst Rating       Market Movement      0.7919
218              Earnings        Product Launch      0.7888
367       Market Movement    Technical Analysis      0.7797
415        Product Launch      Revenue Guidance      0.7715
205              Earnings      Executive Change      0.7707
22         Analyst Rating        Product Launch      0.7706
9          Analyst Rating      Executive Change      0.7656
17         Analyst Rating  Merger & Acquisition      0.7626
213              Earnings  Merger & Acquisition      0.7602
373  Merger & Acquisition        Product Launch      0.7563
234         Economic Data       Monetary Policy      0.7495
364       Market Movement      Revenue Guidance      0.7444
220              Earnings      Revenue Guidance      0.7415
359       Market Movement      Options Activity      0.7399
24         Analyst Rating      Revenue Guidance      0.7368
427      Revenue Guidance    Technical Analysis      0.7297

## 48. Save Similarity

In [87]:
event_similarity.to_parquet(

    os.path.join(

        EVENT_PATH,

        "event_similarity.parquet"

    ),

    index=False

)

print("Saved Event Similarity")

Saved Event Similarity

## 49. Event Fingerprints

In [88]:
def create_event_fingerprint(row):

    fp = []

    if row["impact_category"] == "Very High":

        fp.append("High Impact")

    if row["graph_importance"] > 70:

        fp.append("Highly Connected")

    if row["avg_confidence"] > 0.90:

        fp.append("Reliable")

    if row["companies"] > event_statistics["companies"].median():

        fp.append("Broad Coverage")

    if row["publishers"] > event_statistics["publishers"].median():

        fp.append("Widely Reported")

    if row["bullish"] > row["bearish"]:

        fp.append("Bullish")

    elif row["bearish"] > row["bullish"]:

        fp.append("Bearish")

    return ", ".join(fp)

In [89]:
event_statistics = (

    event_statistics

    .merge(

        event_centrality[

            [

                "final_event",

                "graph_importance"

            ]

        ],

        on="final_event"

    )

)

event_statistics["event_fingerprint"] = (

    event_statistics.apply(

        create_event_fingerprint,

        axis=1

    )

)

display(

    event_statistics[

        [

            "final_event",

            "event_fingerprint"

        ]

    ]

)

             final_event                                  event_fingerprint
0         Analyst Rating  High Impact, Highly Connected, Broad Coverage,...
1             Bankruptcy                                  Reliable, Bearish
2              Commodity  High Impact, Broad Coverage, Widely Reported, ...
3          Credit Rating                 Reliable, Widely Reported, Bullish
4         Cryptocurrency                                            Bullish
5          Cybersecurity                                            Bearish
6               Dividend     High Impact, Reliable, Broad Coverage, Bullish
7                    ESG           Broad Coverage, Widely Reported, Bullish
8               Earnings  High Impact, Highly Connected, Reliable, Broad...
9          Economic Data
10      Executive Change  Reliable, Broad Coverage, Widely Reported, Bul...
11                 Fraud                                            Bearish
12               Funding           Broad Coverage, Widely Reported, Bullish
13                   IPO                                            Bullish
14       Insider Trading                                  Reliable, Bullish
15               Layoffs  Highly Connected, Broad Coverage, Widely Repor...
16            Litigation                                            Bearish
17       Market Movement  High Impact, Highly Connected, Broad Coverage,...
18  Merger & Acquisition  High Impact, Broad Coverage, Widely Reported, ...
19       Monetary Policy
20      Options Activity         Highly Connected, Widely Reported, Bullish
21                 Other  Highly Connected, Broad Coverage, Widely Reported
22           Partnership                            Broad Coverage, Bullish
23        Product Launch  High Impact, Highly Connected, Broad Coverage,...
24   Regulatory Approval                                  Reliable, Bullish
25      Revenue Guidance  Highly Connected, Broad Coverage, Widely Repor...
26         Share Buyback                                            Bullish
27           Stock Split                                            Bullish
28    Technical Analysis  High Impact, Highly Connected, Broad Coverage,...
29          Trading Halt                                            Bullish

## 51. Event Lifecycle

In [90]:
timeline = (

    financial_df

    .assign(

        year=pd.to_datetime(

            financial_df["published_date"]

        ).dt.year

    )

)

event_lifecycle = (

    timeline

    .groupby(

        [

            "final_event",

            "year"

        ]

    )

    .size()

    .reset_index(name="news_count")

)

In [91]:
life = []

for event, group in event_lifecycle.groupby("final_event"):

    peak = group.loc[

        group["news_count"].idxmax()

    ]

    life.append({

        "final_event": event,

        "first_year": group["year"].min(),

        "last_year": group["year"].max(),

        "peak_year": peak["year"],

        "peak_news": peak["news_count"]

    })

event_lifecycle_summary = pd.DataFrame(life)

display(event_lifecycle_summary)

             final_event  first_year  last_year  peak_year  peak_news
0         Analyst Rating        2009       2020       2013      34554
1             Bankruptcy        2009       2020       2016        623
2              Commodity        2009       2020       2019      32577
3          Credit Rating        2009       2020       2019       7785
4         Cryptocurrency        2009       2020       2018       2482
5          Cybersecurity        2009       2020       2015       1461
6               Dividend        2009       2020       2018      24999
7                    ESG        2009       2020       2018       5507
8               Earnings        2009       2020       2019     100641
9          Economic Data        2009       2020       2018       2480
10      Executive Change        2009       2020       2012       8409
11                 Fraud        2009       2020       2019        977
12               Funding        2009       2020       2019       5808
13                   IPO        2009       2020       2014       3047
14       Insider Trading        2009       2020       2015       1852
15               Layoffs        2009       2020       2015       5214
16            Litigation        2009       2020       2019       3649
17       Market Movement        2009       2020       2018      83655
18  Merger & Acquisition        2009       2020       2019      33024
19       Monetary Policy        2009       2020       2019       6460
20      Options Activity        2009       2020       2017       8141
21                 Other        2009       2020       2019      19251
22           Partnership        2009       2020       2018       6169
23        Product Launch        2009       2020       2019      99624
24   Regulatory Approval        2009       2020       2018       4773
25      Revenue Guidance        2009       2020       2019       4542
26         Share Buyback        2009       2020       2015       2882
27           Stock Split        2009       2020       2015        967
28    Technical Analysis        2009       2020       2019      18479
29          Trading Halt        2009       2020       2018       1623

## 53. Event Heatmap

In [92]:
event_heatmap = (

    financial_df

    .assign(

        month=pd.to_datetime(

            financial_df["published_date"]

        ).dt.to_period("M").astype(str)

    )

    .pivot_table(

        index="month",

        columns="final_event",

        values="news_id",

        aggfunc="count",

        fill_value=0

    )

)

display(event_heatmap.head())

final_event,Analyst Rating,Bankruptcy,Commodity,Credit Rating,Cryptocurrency,Cybersecurity,Dividend,ESG,Earnings,Economic Data,...,Options Activity,Other,Partnership,Product Launch,Regulatory Approval,Revenue Guidance,Share Buyback,Stock Split,Technical Analysis,Trading Halt
month,,,,,,,,,,,,,,,,,,,,,
2009-02,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2009-04,0,0,0,0,0,0,0,0,0,0,...,0,0,0,3,0,0,0,0,0,0
2009-05,0,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,3,0
2009-06,0,0,0,0,0,0,0,0,4,0,...,0,5,0,10,0,0,0,0,2,0
2009-07,0,0,2,0,1,0,0,7,15,0,...,0,7,0,25,0,0,0,0,2,0

## 54. Event Knowledge Cards

In [93]:
knowledge_cards = (

    event_statistics

    .merge(

        event_lifecycle_summary,

        on="final_event"

    )

)

knowledge_cards["summary"] = (

    "Impact: "

    + knowledge_cards["impact_category"].astype(str)

    + " | Companies: "

    + knowledge_cards["companies"].astype(str)

    + " | Publishers: "

    + knowledge_cards["publishers"].astype(str)

    + " | Peak Year: "

    + knowledge_cards["peak_year"].astype(str)

)

display(

    knowledge_cards[

        [

            "final_event",

            "summary"

        ]

    ]

)

             final_event                                            summary
0         Analyst Rating  Impact: Very High | Companies: 5178 | Publishe...
1             Bankruptcy  Impact: Low | Companies: 1142 | Publishers: 93...
2              Commodity  Impact: Very High | Companies: 4965 | Publishe...
3          Credit Rating  Impact: High | Companies: 3955 | Publishers: 2...
4         Cryptocurrency  Impact: Low | Companies: 2556 | Publishers: 18...
5          Cybersecurity  Impact: Low | Companies: 1817 | Publishers: 17...
6               Dividend  Impact: Very High | Companies: 3981 | Publishe...
7                    ESG  Impact: Medium | Companies: 4120 | Publishers:...
8               Earnings  Impact: Very High | Companies: 5694 | Publishe...
9          Economic Data  Impact: Low | Companies: 2222 | Publishers: 17...
10      Executive Change  Impact: High | Companies: 4348 | Publishers: 2...
11                 Fraud  Impact: Low | Companies: 1499 | Publishers: 11...
12               Funding  Impact: High | Companies: 4571 | Publishers: 2...
13                   IPO  Impact: Medium | Companies: 3362 | Publishers:...
14       Insider Trading  Impact: Medium | Companies: 2453 | Publishers:...
15               Layoffs  Impact: Medium | Companies: 4324 | Publishers:...
16            Litigation  Impact: Low | Companies: 2792 | Publishers: 16...
17       Market Movement  Impact: Very High | Companies: 6367 | Publishe...
18  Merger & Acquisition  Impact: Very High | Companies: 5653 | Publishe...
19       Monetary Policy  Impact: Medium | Companies: 3405 | Publishers:...
20      Options Activity  Impact: High | Companies: 3651 | Publishers: 1...
21                 Other  Impact: High | Companies: 5660 | Publishers: 3...
22           Partnership  Impact: High | Companies: 4291 | Publishers: 1...
23        Product Launch  Impact: Very High | Companies: 6466 | Publishe...
24   Regulatory Approval  Impact: Medium | Companies: 2559 | Publishers:...
25      Revenue Guidance  Impact: High | Companies: 4417 | Publishers: 2...
26         Share Buyback  Impact: Medium | Companies: 3703 | Publishers:...
27           Stock Split  Impact: Low | Companies: 2490 | Publishers: 12...
28    Technical Analysis  Impact: Very High | Companies: 5734 | Publishe...
29          Trading Halt  Impact: Low | Companies: 3145 | Publishers: 11...

## 55. Propagation Risk Score

In [94]:
risk_lookup = analytics_df.set_index(

    "ticker"

)["normalized_risk_score"]

company_event = (

    financial_df

    .merge(

        analytics_df[

            [

                "ticker",

                "normalized_risk_score"

            ]

        ],

        on="ticker"

    )

)

propagation_risk = (

    company_event

    .groupby("final_event")

    .agg(

        avg_company_risk=(

            "normalized_risk_score",

            "mean"

        )

    )

    .reset_index()

)

propagation_risk = propagation_risk.merge(

    event_statistics[

        [

            "final_event",

            "influence_score"

        ]

    ],

    on="final_event"

)

propagation_risk["propagation_risk"] = (

    propagation_risk["avg_company_risk"]

    *

    propagation_risk["influence_score"]

    /100

).round(2)

display(

    propagation_risk.sort_values(

        "propagation_risk",

        ascending=False

    )

)

             final_event  avg_company_risk  influence_score  propagation_risk
23        Product Launch         35.165064            82.23             28.92
17       Market Movement         35.353410            78.84             27.87
8               Earnings         33.076500            78.41             25.94
2              Commodity         36.530256            66.03             24.12
28    Technical Analysis         35.732690            65.30             23.33
18  Merger & Acquisition         34.250956            64.38             22.05
0         Analyst Rating         33.450122            65.78             22.00
3          Credit Rating         38.415356            57.10             21.94
10      Executive Change         34.831527            58.01             20.21
12               Funding         34.475569            54.17             18.68
25      Revenue Guidance         34.931595            52.62             18.38
21                 Other         35.719252            50.53             18.05
22           Partnership         34.210788            52.71             18.03
6               Dividend         29.741408            59.04             17.56
19       Monetary Policy         39.679698            42.95             17.04
20      Options Activity         35.827401            46.43             16.63
15               Layoffs         37.642972            43.75             16.47
13                   IPO         35.567755            44.20             15.72
7                    ESG         35.382522            42.19             14.93
16            Litigation         38.071366            36.74             13.99
24   Regulatory Approval         31.955499            43.26             13.82
9          Economic Data         41.071549            33.56             13.78
26         Share Buyback         33.449713            40.91             13.68
29          Trading Halt         37.169829            36.22             13.46
14       Insider Trading         33.989872            37.16             12.63
4         Cryptocurrency         38.946219            28.60             11.14
5          Cybersecurity         45.421454            22.69             10.31
1             Bankruptcy         42.003904            21.01              8.83
11                 Fraud         40.052396            21.11              8.46
27           Stock Split         34.393519            22.21              7.64

## 56. Save

In [95]:
event_statistics.to_parquet(
    os.path.join(EVENT_PATH, "event_statistics.parquet"),
    index=False
)

event_communities.to_parquet(
    os.path.join(EVENT_PATH, "event_communities.parquet"),
    index=False
)

event_similarity.to_parquet(
    os.path.join(EVENT_PATH, "event_similarity.parquet"),
    index=False
)

event_lifecycle_summary.to_parquet(
    os.path.join(EVENT_PATH, "event_lifecycle.parquet"),
    index=False
)

event_heatmap.to_parquet(
    os.path.join(EVENT_PATH, "event_heatmap.parquet")
)

knowledge_cards.to_parquet(
    os.path.join(EVENT_PATH, "event_knowledge_cards.parquet"),
    index=False
)

propagation_risk.to_parquet(
    os.path.join(EVENT_PATH, "propagation_risk.parquet"),
    index=False
)

print("Event Propagation Analytics Saved Successfully")

Event Propagation Analytics Saved Successfully

## 57. Create Propagation Graph

In [108]:
import networkx as nx

propagation_graph = nx.Graph()

for row in event_edge_df.itertuples(index=False):

    propagation_graph.add_edge(

        row.event_a,

        row.event_b,

        weight=row.weight

    )

print("Nodes :", propagation_graph.number_of_nodes())
print("Edges :", propagation_graph.number_of_edges())

Nodes : 29
Edges : 221

In [109]:
for event in event_statistics["final_event"]:

    propagation_graph.add_node(event)

for row in event_edge_df.itertuples(index=False):

    propagation_graph.add_edge(

        row.event_a,

        row.event_b,

        weight=row.weight

    )

In [110]:
print("Nodes :", propagation_graph.number_of_nodes())
print("Edges :", propagation_graph.number_of_edges())

Nodes : 30
Edges : 221

## 58. Find Shortest Propagation Paths

In [111]:
propagation_paths = []

events = list(propagation_graph.nodes())

for source in events:

    for target in events:

        if source == target:
            continue

        try:

            path = nx.shortest_path(

                propagation_graph,

                source,

                target

            )

            propagation_paths.append({

                "source_event": source,

                "target_event": target,

                "path_length": len(path) - 1,

                "path": " --> ".join(path)

            })

        except nx.NetworkXNoPath:

            continue

propagation_paths = pd.DataFrame(propagation_paths)

print(propagation_paths.shape)

display(propagation_paths.head())

(812, 4)

,source_event,target_event,path_length,path
0,Analyst Rating,Credit Rating,1,Analyst Rating --> Credit Rating
1,Analyst Rating,Dividend,1,Analyst Rating --> Dividend
2,Analyst Rating,ESG,1,Analyst Rating --> ESG
3,Analyst Rating,Earnings,1,Analyst Rating --> Earnings
4,Analyst Rating,Executive Change,1,Analyst Rating --> Executive Change

## 59. Longest Interesting Paths

In [112]:
long_paths = (

    propagation_paths

    .sort_values(

        "path_length",

        ascending=False

    )

)

display(

    long_paths.head(20)

)

,source_event,target_event,path_length,path
647,Bankruptcy,ESG,3,Bankruptcy --> Layoffs --> Analyst Rating --> ESG
695,Commodity,Bankruptcy,3,Commodity --> Revenue Guidance --> Layoffs -->...
696,Commodity,Cryptocurrency,3,Commodity --> Revenue Guidance --> Economic Da...
699,Commodity,Regulatory Approval,3,Commodity --> Revenue Guidance --> Litigation ...
668,Bankruptcy,Cryptocurrency,3,Bankruptcy --> Layoffs --> Economic Data --> C...
671,Bankruptcy,Regulatory Approval,3,Bankruptcy --> Layoffs --> Litigation --> Regu...
667,Bankruptcy,Commodity,3,Bankruptcy --> Layoffs --> Revenue Guidance --...
807,Regulatory Approval,Bankruptcy,3,Regulatory Approval --> Litigation --> Layoffs...
274,Insider Trading,Bankruptcy,3,Insider Trading --> Analyst Rating --> Layoffs...
681,Commodity,Insider Trading,3,Commodity --> Revenue Guidance --> Analyst Rat...
275,Insider Trading,Commodity,3,Insider Trading --> Analyst Rating --> Revenue...
808,Regulatory Approval,Commodity,3,Regulatory Approval --> Litigation --> Revenue...
106,ESG,Bankruptcy,3,ESG --> Analyst Rating --> Layoffs --> Bankruptcy
723,Cryptocurrency,Bankruptcy,3,Cryptocurrency --> Economic Data --> Layoffs -...
653,Bankruptcy,Insider Trading,3,Bankruptcy --> Layoffs --> Analyst Rating --> ...
724,Cryptocurrency,Commodity,3,Cryptocurrency --> Economic Data --> Revenue G...
261,Insider Trading,Layoffs,2,Insider Trading --> Analyst Rating --> Layoffs
315,Litigation,Funding,2,Litigation --> Analyst Rating --> Funding
260,Insider Trading,IPO,2,Insider Trading --> Analyst Rating --> IPO
259,Insider Trading,Funding,2,Insider Trading --> Analyst Rating --> Funding

## 60. Event Reachability

In [113]:
reachability = []

for event in propagation_graph.nodes():

    reachable = nx.single_source_shortest_path_length(

        propagation_graph,

        event

    )

    reachability.append({

        "final_event": event,

        "reachable_events": len(reachable) - 1,

        "average_distance": round(

            np.mean(list(reachable.values())),

            2

        )

    })

reachability = pd.DataFrame(reachability)

display(

    reachability

    .sort_values(

        "reachable_events",

        ascending=False

    )

)

             final_event  reachable_events  average_distance
0         Analyst Rating                28              1.17
1          Credit Rating                28              1.48
2               Dividend                28              1.52
3                    ESG                28              1.79
4               Earnings                28              1.17
5       Executive Change                28              1.21
6                  Fraud                28              1.52
7                Funding                28              1.38
8                    IPO                28              1.38
9        Insider Trading                28              1.76
10               Layoffs                28              1.14
11            Litigation                28              1.34
12       Market Movement                28              1.10
13  Merger & Acquisition                28              1.21
14      Options Activity                28              1.24
15                 Other                28              1.17
16           Partnership                28              1.28
17        Product Launch                28              1.03
18      Revenue Guidance                28              1.10
19         Share Buyback                28              1.28
20           Stock Split                28              1.48
21    Technical Analysis                28              1.14
22          Trading Halt                28              1.34
23            Bankruptcy                28              2.07
24             Commodity                28              2.03
25        Cryptocurrency                28              1.86
26         Economic Data                28              1.62
27       Monetary Policy                28              1.62
28   Regulatory Approval                28              1.86
29         Cybersecurity                 0              0.00

## 61. Event Bridges

In [114]:
bridge_score = pd.DataFrame({

    "final_event": list(

        nx.betweenness_centrality(

            propagation_graph,

            weight="weight"

        ).keys()

    ),

    "bridge_score": list(

        nx.betweenness_centrality(

            propagation_graph,

            weight="weight"

        ).values()

    )

})

bridge_score = bridge_score.sort_values(

    "bridge_score",

    ascending=False

)

display(bridge_score.head(20))

           final_event  bridge_score
10             Layoffs      0.088670
18    Revenue Guidance      0.076355
14    Options Activity      0.039409
15               Other      0.036946
22        Trading Halt      0.036946
21  Technical Analysis      0.034483
17      Product Launch      0.034483
16         Partnership      0.024631
0       Analyst Rating      0.024631
11          Litigation      0.019704
3                  ESG      0.019704
26       Economic Data      0.017241
12     Market Movement      0.017241
19       Share Buyback      0.009852
4             Earnings      0.007389
7              Funding      0.004926
8                  IPO      0.002463
9      Insider Trading      0.000000
2             Dividend      0.000000
1        Credit Rating      0.000000

## 62. Event Hub Score

In [115]:
hub_scores = pd.DataFrame({

    "final_event": list(

        nx.degree_centrality(

            propagation_graph

        ).keys()

    ),

    "hub_score": list(

        nx.degree_centrality(

            propagation_graph

        ).values()

    )

})

display(

    hub_scores

    .sort_values(

        "hub_score",

        ascending=False

    )

)

             final_event  hub_score
17        Product Launch   0.896552
12       Market Movement   0.827586
18      Revenue Guidance   0.827586
21    Technical Analysis   0.793103
10               Layoffs   0.793103
0         Analyst Rating   0.758621
15                 Other   0.758621
4               Earnings   0.758621
5       Executive Change   0.724138
13  Merger & Acquisition   0.724138
14      Options Activity   0.689655
16           Partnership   0.655172
19         Share Buyback   0.655172
11            Litigation   0.586207
22          Trading Halt   0.586207
8                    IPO   0.551724
7                Funding   0.551724
20           Stock Split   0.448276
1          Credit Rating   0.448276
6                  Fraud   0.413793
2               Dividend   0.413793
26         Economic Data   0.310345
27       Monetary Policy   0.310345
9        Insider Trading   0.241379
3                    ESG   0.172414
25        Cryptocurrency   0.137931
28   Regulatory Approval   0.137931
23            Bankruptcy   0.034483
24             Commodity   0.034483
29         Cybersecurity   0.000000

## 63. Merge Graph Analytics

In [116]:
event_graph_summary = (

    event_statistics

    .merge(

        bridge_score,

        on="final_event",

        how="left"

    )

    .merge(

        hub_scores,

        on="final_event",

        how="left"

    )

    .merge(

        reachability,

        on="final_event",

        how="left"

    )

)

display(event_graph_summary.head())

,final_event,total_news,companies,publishers,avg_confidence,bullish,bearish,neutral,signals,timeline_days,...,timeline_score,influence_score,impact_category,event_fingerprint,explanation,graph_importance,bridge_score,hub_score,reachable_events,average_distance
0,Analyst Rating,277248,5178,311,0.899277,78310,12691,184055,4,3185,...,0.738604,65.78,Very High,"High Impact, Highly Connected, Broad Coverage,...",Companies: 5178 | Publishers: 311 | Confidence...,76.49,0.024631,0.758621,28,1.17
1,Bankruptcy,3043,1142,93,0.904568,37,1826,1062,4,1111,...,0.000000,21.01,Low,"Reliable, Bearish",Companies: 1142 | Publishers: 93 | Confidence:...,12.01,0.000000,0.034483,28,2.07
2,Commodity,176547,4965,450,0.840405,9460,7778,157888,4,3572,...,0.876425,66.03,Very High,"High Impact, Broad Coverage, Widely Reported, ...",Companies: 4965 | Publishers: 450 | Confidence...,12.57,0.000000,0.034483,28,2.03
3,Credit Rating,36358,3955,208,0.956756,2697,1122,32488,4,2777,...,0.593305,57.10,High,"Reliable, Widely Reported, Bullish",Companies: 3955 | Publishers: 208 | Confidence...,42.90,0.000000,0.448276,28,1.48
4,Cryptocurrency,13739,2556,187,0.773372,119,74,13543,4,2379,...,0.451567,28.60,Low,Bullish,Companies: 2556 | Publishers: 187 | Confidence...,18.63,0.000000,0.137931,28,1.86

## 64. Save Propagation Analytics

In [117]:
propagation_paths.to_parquet(

    os.path.join(

        EVENT_PATH,

        "event_propagation_paths.parquet"

    ),

    index=False

)

event_graph_summary.to_parquet(

    os.path.join(

        EVENT_PATH,

        "event_graph_summary.parquet"

    ),

    index=False

)

print("Event Propagation Analytics Saved")

Event Propagation Analytics Saved

## 65. Summary

In [118]:
summary = pd.DataFrame({

    "Metric": [

        "Events",
        "Event Communities",
        "Event Similarity Pairs",
        "Propagation Paths",
        "Graph Nodes",
        "Graph Edges"

    ],

    "Value": [

        len(event_statistics),
        event_communities["community_id"].nunique(),
        len(event_similarity),
        len(propagation_paths),
        propagation_graph.number_of_nodes(),
        propagation_graph.number_of_edges()

    ]

})

display(summary)

                   Metric  Value
0                  Events     30
1       Event Communities      4
2  Event Similarity Pairs    435
3       Propagation Paths    812
4             Graph Nodes     30
5             Graph Edges    221