# 1.Setup & Load Data

## 1.Imports

In [1]:
import os
import pickle
import warnings

import numpy as np
import pandas as pd

from tqdm.auto import tqdm

warnings.filterwarnings("ignore")

tqdm.pandas()

## 2.Project Paths

In [2]:
PROJECT_PATH = "/content/drive/MyDrive/FinSight_AI"

DATA_PATH = os.path.join(
    PROJECT_PATH,
    "data"
)

PROCESSED_PATH = os.path.join(
    DATA_PATH,
    "processed"
)

SECTOR_PATH = os.path.join(
    PROCESSED_PATH,
    "sector_intelligence"
)

os.makedirs(
    SECTOR_PATH,
    exist_ok=True
)

## 3.Dataset Paths

In [3]:
FINANCIAL_DATASET = os.path.join(
    PROCESSED_PATH,
    "financial_intelligence",
    "financial_intelligence_dataset.parquet"
)

COMPANY_ANALYTICS_PATH = os.path.join(
    PROCESSED_PATH,
    "company_analytics",
    "company_analytics.parquet"
)

TOPIC_PROFILE_PATH = os.path.join(
    PROCESSED_PATH,
    "topics",
    "topic_profiles.parquet"
)

EVENT_PROFILE_PATH = os.path.join(
    PROCESSED_PATH,
    "event_propagation",
    "event_knowledge_cards.parquet"
)

ENTITY_PATH = os.path.join(
    PROCESSED_PATH,
    "entities",
    "news_entities.parquet"
)

## 4.Load Datasets

In [4]:
financial_df = pd.read_parquet(
    FINANCIAL_DATASET
)

company_analytics = pd.read_parquet(
    COMPANY_ANALYTICS_PATH
)

topic_profiles = pd.read_parquet(
    TOPIC_PROFILE_PATH
)

event_profiles = pd.read_parquet(
    EVENT_PROFILE_PATH
)

entity_table = pd.read_parquet(
    ENTITY_PATH
)

## 5.Display Dataset Sizes

In [5]:
print("Financial Dataset :", financial_df.shape)

print("Company Analytics :", company_analytics.shape)

print("Topic Profiles :", topic_profiles.shape)

print("Event Profiles :", event_profiles.shape)

print("Entities :", entity_table.shape)

Financial Dataset : (3215296, 25)
Company Analytics : (6619, 70)
Topic Profiles : (20, 17)
Event Profiles : (30, 24)
Entities : (7345743, 8)

## 6. Preview

In [6]:
display(financial_df.head())

display(company_analytics.head())

display(topic_profiles.head())

display(event_profiles.head())

display(entity_table.head())

,news_id,headline,url,publisher,published_date,ticker,source,year,month,day,...,original_headline,clean_character_count,clean_word_count,final_event,market_signal,final_confidence,classification_source,topic_id,topic_name,topic_confidence
0,1,Stocks That Hit 52-Week Highs On Friday,https://www.benzinga.com/news/20/06/16190091/s...,Benzinga Insights,2020-06-05 14:30:54+00:00,A,analyst,2020,6,5,...,Stocks That Hit 52-Week Highs On Friday,39,7,Market Movement,Neutral,1.0,Rule,1,Market Movement 2,0.748863
1,2,Stocks That Hit 52-Week Highs On Wednesday,https://www.benzinga.com/news/20/06/16170189/s...,Benzinga Insights,2020-06-03 14:45:20+00:00,A,analyst,2020,6,3,...,Stocks That Hit 52-Week Highs On Wednesday,42,7,Market Movement,Neutral,1.0,Rule,1,Market Movement 2,0.748856
2,3,71 Biggest Movers From Friday,https://www.benzinga.com/news/20/05/16103463/7...,Lisa Levin,2020-05-26 08:30:07+00:00,A,analyst,2020,5,26,...,71 Biggest Movers From Friday,29,5,Market Movement,Neutral,1.0,Rule,10,News & Commentary 0,0.520242
3,4,46 Stocks Moving In Friday's Mid-Day Session,https://www.benzinga.com/news/20/05/16095921/4...,Lisa Levin,2020-05-22 16:45:06+00:00,A,analyst,2020,5,22,...,46 Stocks Moving In Friday's Mid-Day Session,44,7,Market Movement,Neutral,1.0,Rule,15,Earnings & Estimates 6,0.477931
4,5,B of A Securities Maintains Neutral on Agilent...,https://www.benzinga.com/news/20/05/16095304/b...,Vick Meyer,2020-05-22 15:38:59+00:00,A,analyst,2020,5,22,...,B of A Securities Maintains Neutral on Agilent...,87,14,Analyst Rating,Bullish,1.0,Rule,19,Analyst Ratings 0,0.788773

,ticker,total_news,first_news,latest_news,unique_publishers,avg_headline_length,avg_word_count,avg_confidence,median_confidence,min_confidence,...,normalized_risk_score,risk_level,event_diversity,market_stability_score,activity_score,composite_score,overall_rank,cluster,company_fingerprint,risk_explanation
0,GILD,4938,2009-09-11 00:00:00+00:00,2020-06-10 17:44:51+00:00,169,75.379911,11.686513,0.820607,0.7535,0.286,...,10.29,Very Low,30,96.41,83.09,89.41,1,3,"Stable, High Activity, Bullish, Diversified",Fraud: 3 | Bankruptcy: 1 | Cybersecurity: 8 | ...
1,HD,4415,2009-08-10 00:00:00+00:00,2020-06-10 12:14:08+00:00,232,64.542922,10.525481,0.829553,0.7599,0.333,...,29.29,Low,30,96.08,74.00,84.88,2,3,"High Activity, Bullish, Diversified",Fraud: 6 | Bankruptcy: 3 | Cybersecurity: 51 |...
2,MDT,4421,2009-08-07 00:00:00+00:00,2020-06-11 14:22:31+00:00,134,68.356254,10.373445,0.851852,0.7805,0.333,...,0.00,Very Low,30,97.71,57.43,83.69,3,3,"Stable, Bullish, Diversified",Fraud: 2 | Bankruptcy: 1 | Cybersecurity: 9 | ...
3,SLV,3968,2009-08-17 00:00:00+00:00,2020-06-03 00:00:00+00:00,119,50.743196,8.517137,0.849060,0.7861,0.250,...,41.21,Medium,28,92.37,72.31,81.65,4,11,"High Activity, Bullish, Diversified",Fraud: 1 | Bankruptcy: 4 | Cybersecurity: 8 | ...
4,LOW,3212,2009-08-13 00:00:00+00:00,2020-06-11 14:34:01+00:00,189,62.575965,10.007161,0.843545,0.7645,0.357,...,23.55,Low,29,96.09,59.47,80.88,5,3,"Bullish, Diversified",Bankruptcy: 6 | Cybersecurity: 9 | Litigation:...

,topic_id,topic_name,articles,topic_confidence,keywords,growth_score,lifecycle,diversity_score,diversity_category,community,popularity_score,impact_category,confidence_category,topic_fingerprint,summary,search_keywords,recommendation_score
0,8,Market Movement 0,15863,0.559584,"stocks, market, stock, china, cap, industry, h...",100.000000,Emerging,68.849178,Broad Coverage,1,63.246405,Very High,Moderate,"High Impact, Emerging, Broad Coverage",Articles: 15863 | Confidence: 0.56 | Lifecycle...,stocks market stock china cap industry h...,72.086074
1,16,Earnings & Estimates 0,19388,0.729797,"vs, est, eps, reports, sales, estimate, sees, ...",54.698497,Stable,18.799142,Focused,0,54.399571,High,Very Reliable,"Popular, Stable, Very Reliable",Articles: 19388 | Confidence: 0.73 | Lifecycle...,vs est eps reports sales estimate sees ...,60.063296
2,5,Dividends & Shareholder Returns 0,11261,0.514730,"dividend, declares, value, stock, investors, p...",52.559370,Stable,69.209979,Broad Coverage,2,48.929279,High,Moderate,"Popular, Stable, Broad Coverage",Articles: 11261 | Confidence: 0.51 | Lifecycle...,dividend declares value stock investors p...,50.781419
3,13,Market Movement 1,15264,0.533561,"says, term, long, market, hearing, shares, dea...",19.170184,Declining,54.960359,Moderately Diverse,1,53.650224,High,Moderate,Popular,Articles: 15264 | Confidence: 0.53 | Lifecycle...,says term long market hearing shares dea...,43.217971
4,3,Earnings & Estimates 2,9776,0.621764,"ceo, transcript, earnings transcript, results ...",41.779155,Stable,25.902315,Focused,0,28.754049,Medium,Reliable,"Stable, Reliable",Articles: 9776 | Confidence: 0.62 | Lifecycle:...,ceo transcript earnings transcript results ...,42.688292

,final_event,total_news,companies,publishers,avg_confidence,bullish,bearish,neutral,signals,timeline_days,...,influence_score,impact_category,event_fingerprint,explanation,graph_importance,first_year,last_year,peak_year,peak_news,summary
0,Analyst Rating,277248,5178,311,0.899277,78310,12691,184055,4,3185,...,65.78,Very High,"High Impact, Highly Connected, Broad Coverage,...",Companies: 5178 | Publishers: 311 | Confidence...,76.49,2009,2020,2013,34554,Impact: Very High | Companies: 5178 | Publishe...
1,Bankruptcy,3043,1142,93,0.904568,37,1826,1062,4,1111,...,21.01,Low,"Reliable, Bearish",Companies: 1142 | Publishers: 93 | Confidence:...,12.01,2009,2020,2016,623,Impact: Low | Companies: 1142 | Publishers: 93...
2,Commodity,176547,4965,450,0.840405,9460,7778,157888,4,3572,...,66.03,Very High,"High Impact, Broad Coverage, Widely Reported, ...",Companies: 4965 | Publishers: 450 | Confidence...,12.57,2009,2020,2019,32577,Impact: Very High | Companies: 4965 | Publishe...
3,Credit Rating,36358,3955,208,0.956756,2697,1122,32488,4,2777,...,57.10,High,"Reliable, Widely Reported, Bullish",Companies: 3955 | Publishers: 208 | Confidence...,42.90,2009,2020,2019,7785,Impact: High | Companies: 3955 | Publishers: 2...
4,Cryptocurrency,13739,2556,187,0.773372,119,74,13543,4,2379,...,28.60,Low,Bullish,Companies: 2556 | Publishers: 187 | Confidence...,18.63,2009,2020,2018,2482,Impact: Low | Companies: 2556 | Publishers: 18...

,news_id,ticker,published_date,publisher,headline,entity,entity_label,entity_source
0,2369716,LII,2018-10-22 00:00:00+00:00,Zacks,Lennox International (LII) Q3 Earnings and Rev...,Earnings,FINANCIAL_METRIC,Matcher
1,1007293,PNFP,2020-01-21 00:00:00+00:00,Lisa Levin,"Earnings Scheduled For January 21, 2020",Earnings,FINANCIAL_METRIC,Matcher
2,575742,GRT,2012-07-06 00:00:00+00:00,David Johnson,UPDATE: Bank of America Downgrades Glimcher Re...,Sales,FINANCIAL_METRIC,Matcher
3,36,A,2020-03-26 00:00:00+00:00,Vick Meyer,Barclays Maintains Equal-Weight on Agilent Tec...,Price Target,FINANCIAL_METRIC,Matcher
4,14,A,2020-05-21 00:00:00+00:00,Benzinga Newsdesk,Agilent Technologies shares are trading higher...,EPS,COMPANY,Matcher

## 7. Dataset Summary

In [7]:
summary = pd.DataFrame({

    "Dataset":[

        "Financial News",

        "Companies",

        "Topics",

        "Events",

        "Entities"

    ],

    "Rows":[

        len(financial_df),

        len(company_analytics),

        len(topic_profiles),

        len(event_profiles),

        len(entity_table)

    ]

})

display(summary)

          Dataset     Rows
0  Financial News  3215296
1       Companies     6619
2          Topics       20
3          Events       30
4        Entities  7345743

# 2. Financial Sector Taxonomy

## 8. Build Sector Dictionary

In [8]:
SECTOR_KEYWORDS = {

    "Artificial Intelligence":[

        "artificial intelligence","ai","machine learning",
        "deep learning","llm","chatgpt","generative ai",
        "neural network","foundation model"

    ],

    "Semiconductors":[

        "chip","chips","semiconductor","gpu","cpu",
        "processor","wafer","fab","tsmc","nvidia","amd","intel"

    ],

    "Cloud Computing":[

        "cloud","azure","aws","google cloud",
        "oracle cloud","saas","cloud platform"

    ],

    "Cybersecurity":[

        "cyber","cybersecurity","hack","hacker",
        "malware","ransomware","data breach",
        "security vulnerability"

    ],

    "Banking":[

        "bank","banking","loan","deposit",
        "credit","interest rate","mortgage",
        "jpmorgan","goldman","citigroup"

    ],

    "Insurance":[

        "insurance","insurer","life insurance",
        "property insurance","premium"

    ],

    "FinTech":[

        "fintech","digital payment","payment",
        "paypal","block","square","visa","mastercard"

    ],

    "Healthcare":[

        "healthcare","hospital","medical",
        "drug","medicine","treatment"

    ],

    "Biotechnology":[

        "biotech","biotechnology","clinical trial",
        "gene therapy","genomics","biopharma"

    ],

    "Pharmaceuticals":[

        "pharmaceutical","pharma","fda",
        "vaccine","drug approval"

    ],

    "Electric Vehicles":[

        "electric vehicle","ev","tesla",
        "battery","charging","autonomous driving"

    ],

    "Automotive":[

        "automobile","vehicle","car","truck",
        "ford","gm","toyota","honda"

    ],

    "Energy":[

        "oil","gas","crude","lng",
        "renewable","solar","wind",
        "energy"

    ],

    "Mining":[

        "gold","silver","copper","iron ore",
        "mining","miner"

    ],

    "Retail":[

        "retail","consumer","shopping",
        "store","ecommerce","amazon","walmart"

    ],

    "Consumer Goods":[

        "consumer goods","beverage","food",
        "coca cola","pepsi","procter"
    ],

    "Telecommunications":[

        "telecom","wireless","5g",
        "broadband","mobile network"

    ],

    "Media":[

        "streaming","media","television",
        "movie","entertainment","netflix","disney"

    ],

    "Real Estate":[

        "real estate","reit","housing",
        "property","commercial real estate"

    ],

    "Transportation":[

        "airline","shipping","railway",
        "logistics","cargo","air freight"

    ],

    "Cryptocurrency":[

        "bitcoin","ethereum","crypto",
        "blockchain","stablecoin","token"

    ],

    "Macroeconomics":[

        "inflation","recession","gdp",
        "cpi","ppi","employment",
        "federal reserve","interest rates"

    ],

    "Commodities":[

        "commodity","gold","silver",
        "oil","natural gas","wheat",
        "corn","soybean"

    ],

    "General Markets":[

        "stock market","stocks","shares",
        "nasdaq","dow","s&p 500",
        "market"

    ]

}

## 9. Count Sectors

In [9]:
print(len(SECTOR_KEYWORDS))

24

## 10. Build Keyword Lookup

In [10]:
keyword_to_sector = {}

for sector, keywords in SECTOR_KEYWORDS.items():

    for keyword in keywords:

        keyword_to_sector[keyword.lower()] = sector

## 11. Validation

In [11]:
print(len(keyword_to_sector))

166

## 12. Sector Summary

In [12]:
sector_summary = pd.DataFrame({

    "sector": list(SECTOR_KEYWORDS.keys()),

    "keywords": [

        len(v)

        for v in SECTOR_KEYWORDS.values()

    ]

})

display(sector_summary)

                     sector  keywords
0   Artificial Intelligence         9
1            Semiconductors        12
2           Cloud Computing         7
3             Cybersecurity         8
4                   Banking        10
5                 Insurance         5
6                   FinTech         8
7                Healthcare         6
8             Biotechnology         6
9           Pharmaceuticals         5
10        Electric Vehicles         6
11               Automotive         8
12                   Energy         8
13                   Mining         6
14                   Retail         7
15           Consumer Goods         6
16       Telecommunications         5
17                    Media         7
18              Real Estate         5
19           Transportation         6
20           Cryptocurrency         6
21           Macroeconomics         8
22              Commodities         8
23          General Markets         7

## 13. Largest Dictionaries

In [13]:
sector_summary.sort_values(

    "keywords",

    ascending=False

).head(10)

                     sector  keywords
1            Semiconductors        12
4                   Banking        10
0   Artificial Intelligence         9
3             Cybersecurity         8
6                   FinTech         8
21           Macroeconomics         8
12                   Energy         8
11               Automotive         8
22              Commodities         8
23          General Markets         7

## 14. Total Keywords

In [14]:
total_keywords = sum(

    len(v)

    for v in SECTOR_KEYWORDS.values()

)

print(total_keywords)

169

## 15. Check Duplicate Keywords

In [15]:
duplicates = (

    pd.Series(

        [

            k.lower()

            for values in SECTOR_KEYWORDS.values()

            for k in values

        ]

    )

    .value_counts()

)

duplicates = duplicates[duplicates > 1]

display(duplicates.head(20))

oil       2
gold      2
silver    2
Name: count, dtype: int64

## 16. Save Dictionary

In [16]:
with open(

    os.path.join(

        SECTOR_PATH,

        "sector_dictionary.pkl"

    ),

    "wb"

) as f:

    pickle.dump(

        SECTOR_KEYWORDS,

        f

    )

## 17. Validation

In [17]:
summary = pd.DataFrame({

    "Metric":[

        "Financial Sectors",

        "Unique Keywords"

    ],

    "Value":[

        len(SECTOR_KEYWORDS),

        total_keywords

    ]

})

display(summary)

              Metric  Value
0  Financial Sectors     24
1    Unique Keywords    169

# 3. Hybrid Sector Classification Engine

## 18. Load Topic Assignment

In [18]:
TOPIC_ASSIGNMENT_PATH = os.path.join(
    PROCESSED_PATH,
    "topics",
    "news_topics.parquet"
)

news_topics = pd.read_parquet(
    TOPIC_ASSIGNMENT_PATH
)

print(news_topics.shape)

display(news_topics.head())

(1640793, 5)

,news_id,headline,topic_id,topic_name,topic_confidence
0,1,Stocks That Hit 52-Week Highs On Friday,1,Market Movement 2,0.748863
1,2,Stocks That Hit 52-Week Highs On Wednesday,1,Market Movement 2,0.748856
2,3,71 Biggest Movers From Friday,10,News & Commentary 0,0.520242
3,4,46 Stocks Moving In Friday's Mid-Day Session,15,Earnings & Estimates 6,0.477931
4,5,B of A Securities Maintains Neutral on Agilent...,19,Analyst Ratings 0,0.788773

In [19]:
print(financial_df.columns.tolist())

['news_id', 'headline', 'url', 'publisher', 'published_date', 'ticker', 'source', 'year', 'month', 'day', 'weekday', 'hour', 'headline_length', 'word_count', 'has_time', 'original_headline', 'clean_character_count', 'clean_word_count', 'final_event', 'market_signal', 'final_confidence', 'classification_source', 'topic_id', 'topic_name', 'topic_confidence']

In [20]:
print([c for c in financial_df.columns if "topic" in c])

['topic_id', 'topic_name', 'topic_confidence']

In [21]:
# financial_df = financial_df.rename(
#     columns={
#         "topic_id_x": "topic_id",
#         "topic_name_x": "topic_name",
#         "topic_confidence_x": "topic_confidence"
#     }
# )

# financial_df = financial_df.drop(
#     columns=[
#         "topic_id_y",
#         "topic_name_y",
#         "topic_confidence_y"
#     ]
# )

# print(financial_df.shape)

# print(
#     financial_df[
#         [
#             "topic_id",
#             "topic_name",
#             "topic_confidence"
#         ]
#     ].head()
# )

## 19. Coverage check

In [22]:
missing = financial_df["topic_id"].isna().sum()

print("Missing Topics :", missing)

print(
    "Coverage :",
    round((1 - missing / len(financial_df)) * 100, 2),
    "%"
)

Missing Topics : 0
Coverage : 100.0 %

## 20. Merge entities

In [23]:
news_entities = (

    entity_table

    .groupby("news_id")

    .agg(

        entities=("entity", list),

        entity_labels=("entity_label", list)

    )

    .reset_index()

)

financial_df = financial_df.merge(

    news_entities,

    on="news_id",

    how="left"

)

## 21. EVENT_TO_SECTOR

In [24]:
EVENT_TO_SECTOR = {

    "Earnings": "General Markets",
    "Analyst Rating": "Financial Services",
    "Market Movement": "General Markets",
    "IPO": "Financial Services",
    "Funding": "Financial Services",
    "Credit Rating": "Financial Services",
    "Monetary Policy": "Macroeconomics",
    "Economic Data": "Macroeconomics",
    "Merger & Acquisition": "Corporate",
    "Executive Change": "Corporate",
    "Product Launch": "Technology",
    "Cybersecurity": "Cybersecurity",
    "Cryptocurrency": "Cryptocurrency",
    "Commodity": "Commodities",
    "Dividend": "Financial Services",
    "Revenue Guidance": "General Markets",
    "Share Buyback": "Financial Services",
    "Stock Split": "Financial Services",
    "Regulatory Approval": "Healthcare",
    "Bankruptcy": "Financial Services",
    "Fraud": "Financial Services",
    "Litigation": "General Markets",
    "Technical Analysis": "General Markets",
    "Trading Halt": "General Markets",
    "Layoffs": "Corporate",
    "Partnership": "Corporate",
    "ESG": "General Markets",
    "Insider Trading": "Financial Services",
    "Other": "General Markets"

}

## 22. TOPIC_TO_SECTOR

In [25]:
TOPIC_TO_SECTOR = {

    "Earnings & Estimates": "General Markets",

    "Market Movement": "General Markets",

    "Corporate Actions": "Corporate",

    "Healthcare & Pharma": "Healthcare",

    "Financial Institutions": "Banking",

    "Energy & Commodities": "Energy",

    "Analyst Ratings": "Financial Services",

    "News & Commentary": "General Markets"

}

## 23. Verify

In [26]:
print(len(EVENT_TO_SECTOR))
print(len(TOPIC_TO_SECTOR))

29
8

## 23. Fill missing lists

In [27]:
financial_df["entities"] = financial_df["entities"].apply(

    lambda x: x if isinstance(x, list) else []

)

financial_df["entity_labels"] = financial_df["entity_labels"].apply(

    lambda x: x if isinstance(x, list) else []

)

## 24. Build Keyword Lookup

In [28]:
def keyword_sector_scores(text):

    scores = {}

    if pd.isna(text):
        return scores

    text = str(text).lower()

    for sector, keywords in SECTOR_KEYWORDS.items():

        count = 0

        for keyword in keywords:

            if keyword.lower() in text:

                count += 1

        if count > 0:

            scores[sector] = count

    return scores

## 25. Event Score

In [29]:
def event_sector_score(event):

    if pd.isna(event):
        return {}

    sector = EVENT_TO_SECTOR.get(event)

    if sector is None:
        return {}

    return {

        sector: 2.5

    }

## 26. Topic Score

In [30]:
def topic_sector_score(topic):

    if pd.isna(topic):

        return {}

    for prefix, sector in TOPIC_TO_SECTOR.items():

        if topic.startswith(prefix):

            return {

                sector: 2.0

            }

    return {}

## 27. Entity Score

In [31]:
def entity_sector_score(entity_list):

    scores = {}

    if not isinstance(entity_list, list):

        return scores

    for entity in entity_list:

        entity = str(entity).lower()

        for sector, keywords in SECTOR_KEYWORDS.items():

            if entity in [

                k.lower()

                for k in keywords

            ]:

                scores[sector] = (

                    scores.get(sector, 0)

                    + 1.5

                )

    return scores

## 28. Hybrid Scoring Function

In [32]:
def combine_sector_scores(row):

    final_scores = {}

    headline_scores = keyword_sector_scores(

        row["headline"]

    )

    event_scores = event_sector_score(

        row["final_event"]

    )

    topic_scores = topic_sector_score(

        row["topic_name"]

    )

    entity_scores = entity_sector_score(

        row["entities"]

    )

    for source in [

        headline_scores,

        event_scores,

        topic_scores,

        entity_scores

    ]:

        for sector, score in source.items():

            final_scores[sector] = (

                final_scores.get(sector, 0)

                + score

            )

    return final_scores

## 29. Calculate Scores

In [33]:
tqdm.pandas()

financial_df["sector_scores"] = (

    financial_df

    .progress_apply(

        combine_sector_scores,

        axis=1

    )

)

  0%|          | 0/3215296 [00:00<?, ?it/s]

## 30. Assign Primary Sector

In [34]:
def choose_sector(score_dict):

    if len(score_dict) == 0:

        return "Other"

    return max(

        score_dict,

        key=score_dict.get

    )

In [35]:
financial_df["sector"] = (

    financial_df["sector_scores"]

    .apply(choose_sector)

)

## 31. Confidence

In [36]:
def sector_confidence(scores):

    if len(scores) == 0:

        return 0

    total = sum(scores.values())

    best = max(scores.values())

    return round(best / total, 3)

In [37]:
financial_df["sector_confidence"] = (

    financial_df["sector_scores"]

    .apply(

        sector_confidence

    )

)

## 32. Validation

In [38]:
print(

    financial_df.shape

)

display(

    financial_df[

        [

            "headline",

            "final_event",

            "topic_name",

            "sector",

            "sector_confidence"

        ]

    ].head(10)

)

(3215296, 30)

,headline,final_event,topic_name,sector,sector_confidence
0,Stocks That Hit 52-Week Highs On Friday,Market Movement,Market Movement 2,General Markets,1.000
1,Stocks That Hit 52-Week Highs On Wednesday,Market Movement,Market Movement 2,General Markets,1.000
2,71 Biggest Movers From Friday,Market Movement,News & Commentary 0,General Markets,1.000
3,46 Stocks Moving In Friday's Mid-Day Session,Market Movement,Earnings & Estimates 6,General Markets,1.000
4,B of A Securities Maintains Neutral on Agilent...,Analyst Rating,Analyst Ratings 0,Financial Services,0.818
5,"CFRA Maintains Hold on Agilent Technologies, L...",Analyst Rating,Analyst Ratings 0,Financial Services,0.818
6,"UBS Maintains Neutral on Agilent Technologies,...",Analyst Rating,Analyst Ratings 0,Financial Services,0.818
7,Agilent Technologies shares are trading higher...,Earnings,Earnings & Estimates 1,General Markets,1.000
8,Wells Fargo Maintains Overweight on Agilent Te...,Analyst Rating,Analyst Ratings 0,Financial Services,0.818
9,10 Biggest Price Target Changes For Friday,Analyst Rating,News & Commentary 0,Financial Services,0.556

#  4. Sector Intelligence Profiles

## 33. Sector News Statistics

In [39]:
sector_profile = (

    financial_df

    .groupby("sector")

    .agg(

        total_news=("news_id","count"),

        companies=("ticker","nunique"),

        publishers=("publisher","nunique"),

        avg_confidence=("sector_confidence","mean"),

        first_news=("published_date","min"),

        last_news=("published_date","max")

    )

    .reset_index()

)

display(sector_profile)

,sector,total_news,companies,publishers,avg_confidence,first_news,last_news
0,Artificial Intelligence,245,181,31,0.531547,2010-01-20 00:00:00+00:00,2020-05-29 00:00:00+00:00
1,Automotive,3562,794,112,0.384710,2009-08-17 00:00:00+00:00,2020-06-11 11:42:36+00:00
2,Banking,8158,2469,157,0.483236,2009-08-07 00:00:00+00:00,2020-06-11 21:12:35+00:00
3,Biotechnology,1443,440,47,0.351552,2009-08-17 00:00:00+00:00,2020-05-26 16:50:25+00:00
4,Cloud Computing,109,77,20,0.378917,2010-03-10 00:00:00+00:00,2020-04-14 00:00:00+00:00
5,Commodities,145125,4733,426,0.534210,2009-07-27 00:00:00+00:00,2020-06-11 20:51:33+00:00
6,Consumer Goods,446,201,47,0.374549,2009-12-08 00:00:00+00:00,2020-05-18 00:00:00+00:00
7,Corporate,305549,5990,450,0.623737,2009-07-27 00:00:00+00:00,2020-06-11 13:20:52+00:00
8,Cryptocurrency,13433,2512,185,0.582381,2009-02-14 00:00:00+00:00,2020-06-05 21:19:01+00:00
9,Cybersecurity,7102,1729,165,0.567708,2009-08-07 00:00:00+00:00,2020-06-08 14:28:00+00:00
10,Electric Vehicles,1217,505,68,0.388829,2009-10-26 00:00:00+00:00,2020-06-10 15:33:18+00:00
11,Energy,41244,2635,228,0.540438,2009-07-27 00:00:00+00:00,2020-06-10 20:44:00+00:00
12,FinTech,1517,563,80,0.344946,2009-10-19 00:00:00+00:00,2020-06-01 20:44:21+00:00
13,Financial Services,422428,6118,433,0.630588,2009-05-29 00:00:00+00:00,2020-06-11 20:30:31+00:00
14,General Markets,1624406,6551,769,0.824804,2009-05-27 00:00:00+00:00,2020-06-11 21:01:39+00:00
15,Healthcare,34898,2685,203,0.540388,2009-08-07 00:00:00+00:00,2020-06-11 21:11:20+00:00
16,Insurance,46,34,12,0.642348,2010-11-30 00:00:00+00:00,2020-02-13 00:00:00+00:00
17,Macroeconomics,34578,3422,238,0.540113,2009-08-09 00:00:00+00:00,2020-06-11 13:38:43+00:00
18,Media,2184,626,97,0.357502,2009-12-14 00:00:00+00:00,2020-06-10 11:34:40+00:00
19,Mining,78,48,19,0.368692,2009-08-10 00:00:00+00:00,2020-05-11 12:56:17+00:00
20,Other,1970,1159,56,0.000000,2009-08-17 00:00:00+00:00,2020-06-02 00:00:00+00:00
21,Pharmaceuticals,4223,716,101,0.370144,2009-09-10 00:00:00+00:00,2020-06-10 09:22:04+00:00
22,Real Estate,143,101,14,0.767552,2011-01-14 00:00:00+00:00,2020-05-02 00:00:00+00:00
23,Retail,3959,1127,88,0.352055,2009-11-27 00:00:00+00:00,2020-06-10 17:18:50+00:00
24,Semiconductors,3591,822,96,0.375772,2009-10-19 00:00:00+00:00,2020-06-02 17:20:06+00:00
25,Technology,553431,6443,755,0.561223,2009-04-27 00:00:00+00:00,2020-06-11 19:25:36+00:00
26,Telecommunications,200,83,17,0.386525,2009-11-11 00:00:00+00:00,2020-04-01 00:00:00+00:00
27,Transportation,11,10,5,0.385455,2012-02-17 00:00:00+00:00,2019-06-03 00:00:00+00:00

## 34. Market Signal Distribution

In [40]:
signal_distribution = (

    financial_df

    .pivot_table(

        index="sector",

        columns="market_signal",

        values="news_id",

        aggfunc="count",

        fill_value=0

    )

)

display(signal_distribution.head())

market_signal            Bearish  Bullish  Mixed  Neutral
sector
Artificial Intelligence        2       14      0      229
Automotive                    41       99      7     3415
Banking                      146      492     43     7477
Biotechnology                  3       15      1     1424
Cloud Computing                0        8      0      101

## 35. Merge Signal Statistics

In [41]:
sector_profile = sector_profile.merge(

    signal_distribution,

    on="sector",

    how="left"

)

display(sector_profile.head())

,sector,total_news,companies,publishers,avg_confidence,first_news,last_news,Bearish,Bullish,Mixed,Neutral
0,Artificial Intelligence,245,181,31,0.531547,2010-01-20 00:00:00+00:00,2020-05-29 00:00:00+00:00,2,14,0,229
1,Automotive,3562,794,112,0.384710,2009-08-17 00:00:00+00:00,2020-06-11 11:42:36+00:00,41,99,7,3415
2,Banking,8158,2469,157,0.483236,2009-08-07 00:00:00+00:00,2020-06-11 21:12:35+00:00,146,492,43,7477
3,Biotechnology,1443,440,47,0.351552,2009-08-17 00:00:00+00:00,2020-05-26 16:50:25+00:00,3,15,1,1424
4,Cloud Computing,109,77,20,0.378917,2010-03-10 00:00:00+00:00,2020-04-14 00:00:00+00:00,0,8,0,101

## 36. Event Diversity

In [42]:
event_diversity = (

    financial_df

    .groupby("sector")["final_event"]

    .nunique()

    .reset_index(

        name="event_diversity"

    )

)

display(event_diversity)

                     sector  event_diversity
0   Artificial Intelligence               12
1                Automotive               29
2                   Banking               30
3             Biotechnology               22
4           Cloud Computing                9
5               Commodities                8
6            Consumer Goods               22
7                 Corporate                5
8            Cryptocurrency               19
9             Cybersecurity                8
10        Electric Vehicles               23
11                   Energy               29
12                  FinTech               28
13       Financial Services               11
14          General Markets               30
15               Healthcare               30
16                Insurance                7
17           Macroeconomics               13
18                    Media               25
19                   Mining               10
20                    Other                1
21          Pharmaceuticals               21
22              Real Estate               12
23                   Retail               30
24           Semiconductors               28
25               Technology                1
26       Telecommunications               19
27           Transportation                5

## 37. Topic Diversity

In [43]:
topic_diversity = (

    financial_df

    .groupby("sector")["topic_name"]

    .nunique()

    .reset_index(

        name="topic_diversity"

    )

)

display(topic_diversity)

                     sector  topic_diversity
0   Artificial Intelligence               11
1                Automotive               21
2                   Banking               21
3             Biotechnology               21
4           Cloud Computing               13
5               Commodities               21
6            Consumer Goods               21
7                 Corporate               21
8            Cryptocurrency               21
9             Cybersecurity               21
10        Electric Vehicles               21
11                   Energy               21
12                  FinTech               20
13       Financial Services               21
14          General Markets               21
15               Healthcare               21
16                Insurance               10
17           Macroeconomics               21
18                    Media               21
19                   Mining                9
20                    Other                2
21          Pharmaceuticals               21
22              Real Estate                7
23                   Retail               21
24           Semiconductors               21
25               Technology               21
26       Telecommunications               18
27           Transportation                5

## 38. Entity Diversity

In [44]:
entity_diversity = (

    entity_table

    .merge(

        financial_df[

            [

                "news_id",

                "sector"

            ]

        ],

        on="news_id",

        how="left"

    )

    .groupby("sector")["entity"]

    .nunique()

    .reset_index(

        name="unique_entities"

    )

)

display(entity_diversity)

                     sector  unique_entities
0   Artificial Intelligence              227
1                Automotive             2081
2                   Banking             5793
3             Biotechnology              504
4           Cloud Computing              114
5               Commodities            35460
6            Consumer Goods              311
7                 Corporate           163059
8            Cryptocurrency             4533
9             Cybersecurity             3603
10        Electric Vehicles              774
11                   Energy            16389
12                  FinTech             1117
13       Financial Services           158624
14          General Markets           471848
15               Healthcare            22611
16                Insurance               61
17           Macroeconomics             8251
18                    Media             1488
19                   Mining               79
20                    Other              618
21          Pharmaceuticals             3471
22              Real Estate               58
23                   Retail             1949
24           Semiconductors             1841
25               Technology           149112
26       Telecommunications              172
27           Transportation               29

## 39. Merge Everything

In [45]:
sector_profile = (

    sector_profile

    .merge(

        event_diversity,

        on="sector",

        how="left"

    )

    .merge(

        topic_diversity,

        on="sector",

        how="left"

    )

    .merge(

        entity_diversity,

        on="sector",

        how="left"

    )

)

display(sector_profile.head())

,sector,total_news,companies,publishers,avg_confidence,first_news,last_news,Bearish,Bullish,Mixed,Neutral,event_diversity,topic_diversity,unique_entities
0,Artificial Intelligence,245,181,31,0.531547,2010-01-20 00:00:00+00:00,2020-05-29 00:00:00+00:00,2,14,0,229,12,11,227
1,Automotive,3562,794,112,0.384710,2009-08-17 00:00:00+00:00,2020-06-11 11:42:36+00:00,41,99,7,3415,29,21,2081
2,Banking,8158,2469,157,0.483236,2009-08-07 00:00:00+00:00,2020-06-11 21:12:35+00:00,146,492,43,7477,30,21,5793
3,Biotechnology,1443,440,47,0.351552,2009-08-17 00:00:00+00:00,2020-05-26 16:50:25+00:00,3,15,1,1424,22,21,504
4,Cloud Computing,109,77,20,0.378917,2010-03-10 00:00:00+00:00,2020-04-14 00:00:00+00:00,0,8,0,101,9,13,114

## 40. Coverage Score

In [46]:
sector_profile["coverage_score"] = (

    np.log1p(

        sector_profile["total_news"]

    )

    *

    np.log1p(

        sector_profile["companies"]

    )

)

## 41. Sector Activity Score

In [47]:
sector_profile["activity_score"] = (

    sector_profile["coverage_score"]

    *

    sector_profile["avg_confidence"]

)

## 42. Sort

In [48]:
sector_profile = sector_profile.sort_values(

    "activity_score",

    ascending=False

)

display(

    sector_profile.head(20)

)

,sector,total_news,companies,publishers,avg_confidence,first_news,last_news,Bearish,Bullish,Mixed,Neutral,event_diversity,topic_diversity,unique_entities,coverage_score,activity_score
14,General Markets,1624406,6551,769,0.824804,2009-05-27 00:00:00+00:00,2020-06-11 21:01:39+00:00,59204,132017,23679,1409506,30,21,471848,125.667358,103.650926
13,Financial Services,422428,6118,433,0.630588,2009-05-29 00:00:00+00:00,2020-06-11 20:30:31+00:00,12546,187896,3196,218790,11,21,158624,112.945973,71.222402
7,Corporate,305549,5990,450,0.623737,2009-07-27 00:00:00+00:00,2020-06-11 13:20:52+00:00,1934,5628,146,297841,5,21,163059,109.854770,68.520529
25,Technology,553431,6443,755,0.561223,2009-04-27 00:00:00+00:00,2020-06-11 19:25:36+00:00,231,5985,24,547191,1,21,149112,115.985516,65.093748
5,Commodities,145125,4733,426,0.534210,2009-07-27 00:00:00+00:00,2020-06-11 20:51:33+00:00,5571,7447,903,131204,8,21,35460,100.580145,53.730885
17,Macroeconomics,34578,3422,238,0.540113,2009-08-09 00:00:00+00:00,2020-06-11 13:38:43+00:00,0,29,0,34549,13,21,8251,85.053102,45.938322
11,Energy,41244,2635,228,0.540438,2009-07-27 00:00:00+00:00,2020-06-10 20:44:00+00:00,1852,2715,399,36278,29,21,16389,83.711315,45.240780
15,Healthcare,34898,2685,203,0.540388,2009-08-07 00:00:00+00:00,2020-06-11 21:11:20+00:00,571,10018,144,24165,30,21,22611,82.591841,44.631677
8,Cryptocurrency,13433,2512,185,0.582381,2009-02-14 00:00:00+00:00,2020-06-05 21:19:01+00:00,84,178,5,13166,19,21,4533,74.421115,43.341460
9,Cybersecurity,7102,1729,165,0.567708,2009-08-07 00:00:00+00:00,2020-06-08 14:28:00+00:00,850,155,42,6055,8,21,3603,66.120746,37.537293
2,Banking,8158,2469,157,0.483236,2009-08-07 00:00:00+00:00,2020-06-11 21:12:35+00:00,146,492,43,7477,30,21,5793,70.361483,34.001173
1,Automotive,3562,794,112,0.384710,2009-08-17 00:00:00+00:00,2020-06-11 11:42:36+00:00,41,99,7,3415,29,21,2081,54.617874,21.012027
24,Semiconductors,3591,822,96,0.375772,2009-10-19 00:00:00+00:00,2020-06-02 17:20:06+00:00,34,117,6,3434,28,21,1841,54.955377,20.650703
23,Retail,3959,1127,88,0.352055,2009-11-27 00:00:00+00:00,2020-06-10 17:18:50+00:00,11,72,0,3876,30,21,1949,58.221616,20.497215
21,Pharmaceuticals,4223,716,101,0.370144,2009-09-10 00:00:00+00:00,2020-06-10 09:22:04+00:00,122,495,13,3593,21,21,3471,54.892269,20.318043
18,Media,2184,626,97,0.357502,2009-12-14 00:00:00+00:00,2020-06-10 11:34:40+00:00,17,43,4,2120,25,21,1488,49.526828,17.705932
22,Real Estate,143,101,14,0.767552,2011-01-14 00:00:00+00:00,2020-05-02 00:00:00+00:00,13,3,0,127,12,7,58,22.985251,17.642386
10,Electric Vehicles,1217,505,68,0.388829,2009-10-26 00:00:00+00:00,2020-06-10 15:33:18+00:00,13,55,4,1145,23,21,774,44.239328,17.201538
12,FinTech,1517,563,80,0.344946,2009-10-19 00:00:00+00:00,2020-06-01 20:44:21+00:00,16,74,0,1427,28,20,1117,46.405216,16.007291
3,Biotechnology,1443,440,47,0.351552,2009-08-17 00:00:00+00:00,2020-05-26 16:50:25+00:00,3,15,1,1424,22,21,504,44.298851,15.573364

# 5. Sector Risk Intelligence Engine

## 43. Company Sector Distribution

In [49]:
company_sector_distribution = (

    financial_df

    .groupby(

        [

            "ticker",

            "sector"

        ]

    )

    .size()

    .reset_index(

        name="news_count"

    )

)

display(company_sector_distribution.head())

  ticker                   sector  news_count
0      A  Artificial Intelligence           0
1      A               Automotive           0
2      A                  Banking           3
3      A            Biotechnology           0
4      A          Cloud Computing           0

## 44. Calculate percentages.

In [50]:
company_totals = (

    company_sector_distribution

    .groupby("ticker")["news_count"]

    .sum()

    .reset_index(

        name="total_news"

    )

)

company_sector_distribution = (

    company_sector_distribution

    .merge(

        company_totals,

        on="ticker"

    )

)

company_sector_distribution["sector_share"] = (

    company_sector_distribution["news_count"]

    /

    company_sector_distribution["total_news"]

)

## 45. Merge company analytics.

In [51]:
company_sector_distribution = (

    company_sector_distribution

    .merge(

        company_analytics,

        on="ticker",

        how="left"

    )

)

print(company_sector_distribution.shape)

display(company_sector_distribution.head())

(185332, 74)

,ticker,sector,news_count,total_news_x,sector_share,total_news_y,first_news,latest_news,unique_publishers,avg_headline_length,...,normalized_risk_score,risk_level,event_diversity,market_stability_score,activity_score,composite_score,overall_rank,cluster,company_fingerprint,risk_explanation
0,A,Artificial Intelligence,0,2328,0.000000,2328,2009-04-29 00:00:00+00:00,2020-06-05 14:30:54+00:00,126,67.441581,...,24.23,Low,29,95.61,38.71,74.52,78,4,"Bullish, Diversified",Fraud: 3 | Bankruptcy: 1 | Cybersecurity: 6 | ...
1,A,Automotive,0,2328,0.000000,2328,2009-04-29 00:00:00+00:00,2020-06-05 14:30:54+00:00,126,67.441581,...,24.23,Low,29,95.61,38.71,74.52,78,4,"Bullish, Diversified",Fraud: 3 | Bankruptcy: 1 | Cybersecurity: 6 | ...
2,A,Banking,3,2328,0.001289,2328,2009-04-29 00:00:00+00:00,2020-06-05 14:30:54+00:00,126,67.441581,...,24.23,Low,29,95.61,38.71,74.52,78,4,"Bullish, Diversified",Fraud: 3 | Bankruptcy: 1 | Cybersecurity: 6 | ...
3,A,Biotechnology,0,2328,0.000000,2328,2009-04-29 00:00:00+00:00,2020-06-05 14:30:54+00:00,126,67.441581,...,24.23,Low,29,95.61,38.71,74.52,78,4,"Bullish, Diversified",Fraud: 3 | Bankruptcy: 1 | Cybersecurity: 6 | ...
4,A,Cloud Computing,0,2328,0.000000,2328,2009-04-29 00:00:00+00:00,2020-06-05 14:30:54+00:00,126,67.441581,...,24.23,Low,29,95.61,38.71,74.52,78,4,"Bullish, Diversified",Fraud: 3 | Bankruptcy: 1 | Cybersecurity: 6 | ...

## 46. Weighted Sector Intelligence.

In [52]:
sector_risk = (

    company_sector_distribution

    .groupby("sector")

    .agg(

        companies=(

            "ticker",

            "nunique"

        ),

        weighted_company_risk=(

            "normalized_risk_score",

            lambda x: np.average(

                x,

                weights=

                company_sector_distribution.loc[

                    x.index,

                    "sector_share"

                ]

            )

        ),

        weighted_company_score=(

            "composite_score",

            lambda x: np.average(

                x,

                weights=

                company_sector_distribution.loc[

                    x.index,

                    "sector_share"

                ]

            )

        ),

        weighted_market_stability=(

            "market_stability_score",

            lambda x: np.average(

                x,

                weights=

                company_sector_distribution.loc[

                    x.index,

                    "sector_share"

                ]

            )

        )

    )

    .reset_index()

)

display(sector_risk)

,sector,companies,weighted_company_risk,weighted_company_score,weighted_market_stability
0,Artificial Intelligence,6619,36.450779,61.198044,96.101407
1,Automotive,6619,37.936553,64.750819,92.979666
2,Banking,6619,36.107652,61.545457,94.708029
3,Biotechnology,6619,35.422531,62.183229,95.497244
4,Cloud Computing,6619,38.476041,61.970639,94.088854
5,Commodities,6619,37.259902,58.993467,94.196712
6,Consumer Goods,6619,34.309996,64.057181,95.744226
7,Corporate,6619,36.196193,60.397335,95.276937
8,Cryptocurrency,6619,38.115246,56.754336,97.705655
9,Cybersecurity,6619,41.415138,61.611815,94.306589
10,Electric Vehicles,6619,36.338231,62.035428,92.771527
11,Energy,6619,36.335388,60.816228,92.011686
12,FinTech,6619,36.550876,65.873933,94.132289
13,Financial Services,6619,35.154853,60.863006,94.761747
14,General Markets,6619,36.021004,60.402772,94.918737
15,Healthcare,6619,35.113592,62.191356,94.733794
16,Insurance,6619,37.072945,58.837825,95.128985
17,Macroeconomics,6619,38.621904,57.725877,97.845609
18,Media,6619,36.620591,66.497901,94.311659
19,Mining,6619,36.918947,59.471938,95.102292
20,Other,6619,36.395201,59.183700,96.192652
21,Pharmaceuticals,6619,34.757312,62.706914,94.755672
22,Real Estate,6619,34.660806,61.182060,96.437895
23,Retail,6619,36.287706,63.483007,95.235489
24,Semiconductors,6619,35.911474,63.540321,95.742066
25,Technology,6619,36.718451,59.057320,96.303134
26,Telecommunications,6619,36.777860,61.704878,95.963293
27,Transportation,6619,34.624512,66.258566,93.291977

In [53]:
sector_profile = (

    sector_profile

    .merge(

        sector_risk,

        on="sector",

        how="left"

    )

)

display(sector_profile.head())

,sector,total_news,companies_x,publishers,avg_confidence,first_news,last_news,Bearish,Bullish,Mixed,Neutral,event_diversity,topic_diversity,unique_entities,coverage_score,activity_score,companies_y,weighted_company_risk,weighted_company_score,weighted_market_stability
0,General Markets,1624406,6551,769,0.824804,2009-05-27 00:00:00+00:00,2020-06-11 21:01:39+00:00,59204,132017,23679,1409506,30,21,471848,125.667358,103.650926,6619,36.021004,60.402772,94.918737
1,Financial Services,422428,6118,433,0.630588,2009-05-29 00:00:00+00:00,2020-06-11 20:30:31+00:00,12546,187896,3196,218790,11,21,158624,112.945973,71.222402,6619,35.154853,60.863006,94.761747
2,Corporate,305549,5990,450,0.623737,2009-07-27 00:00:00+00:00,2020-06-11 13:20:52+00:00,1934,5628,146,297841,5,21,163059,109.854770,68.520529,6619,36.196193,60.397335,95.276937
3,Technology,553431,6443,755,0.561223,2009-04-27 00:00:00+00:00,2020-06-11 19:25:36+00:00,231,5985,24,547191,1,21,149112,115.985516,65.093748,6619,36.718451,59.057320,96.303134
4,Commodities,145125,4733,426,0.534210,2009-07-27 00:00:00+00:00,2020-06-11 20:51:33+00:00,5571,7447,903,131204,8,21,35460,100.580145,53.730885,6619,37.259902,58.993467,94.196712

In [54]:
display(

    sector_profile[
        [
            "sector",
            "activity_score",
            "weighted_company_score",
            "weighted_market_stability",
            "avg_confidence"
        ]
    ]

)

,sector,activity_score,weighted_company_score,weighted_market_stability,avg_confidence
0,General Markets,103.650926,60.402772,94.918737,0.824804
1,Financial Services,71.222402,60.863006,94.761747,0.630588
2,Corporate,68.520529,60.397335,95.276937,0.623737
3,Technology,65.093748,59.057320,96.303134,0.561223
4,Commodities,53.730885,58.993467,94.196712,0.534210
5,Macroeconomics,45.938322,57.725877,97.845609,0.540113
6,Energy,45.240780,60.816228,92.011686,0.540438
7,Healthcare,44.631677,62.191356,94.733794,0.540388
8,Cryptocurrency,43.341460,56.754336,97.705655,0.582381
9,Cybersecurity,37.537293,61.611815,94.306589,0.567708
10,Banking,34.001173,61.545457,94.708029,0.483236
11,Automotive,21.012027,64.750819,92.979666,0.384710
12,Semiconductors,20.650703,63.540321,95.742066,0.375772
13,Retail,20.497215,63.483007,95.235489,0.352055
14,Pharmaceuticals,20.318043,62.706914,94.755672,0.370144
15,Media,17.705932,66.497901,94.311659,0.357502
16,Real Estate,17.642386,61.182060,96.437895,0.767552
17,Electric Vehicles,17.201538,62.035428,92.771527,0.388829
18,FinTech,16.007291,65.873933,94.132289,0.344946
19,Biotechnology,15.573364,62.183229,95.497244,0.351552
20,Artificial Intelligence,15.228704,61.198044,96.101407,0.531547
21,Consumer Goods,12.133156,64.057181,95.744226,0.374549
22,Telecommunications,9.082554,61.704878,95.963293,0.386525
23,Insurance,8.792852,58.837825,95.128985,0.642348
24,Cloud Computing,7.759708,61.970639,94.088854,0.378917
25,Mining,6.269652,59.471938,95.102292,0.368692
26,Transportation,2.296749,66.258566,93.291977,0.385455
27,Other,0.000000,59.183700,96.192652,0.000000

## 47. Sector Intelligence Score

In [56]:
sector_profile["sector_intelligence_score"] = (

      sector_profile["activity_score"] * 0.35

    + sector_profile["weighted_company_score"] * 0.30

    + sector_profile["weighted_market_stability"] * 0.20

    + sector_profile["avg_confidence"] * 100 * 0.15

)

## 48. Rank Sectors

In [57]:
sector_profile = (

    sector_profile

    .sort_values(

        "sector_intelligence_score",

        ascending=False

    )

    .reset_index(drop=True)

)

sector_profile["sector_rank"] = np.arange(

    1,

    len(sector_profile) + 1

)

## 49. Risk Category

In [58]:
def sector_risk_level(score):

    if score < 20:
        return "Very Low"

    elif score < 40:
        return "Low"

    elif score < 60:
        return "Medium"

    elif score < 80:
        return "High"

    else:
        return "Very High"


sector_profile["sector_risk_level"] = (

    sector_profile["weighted_company_risk"]

    .apply(sector_risk_level)

)

display(

    sector_profile[

        [

            "sector",

            "weighted_company_risk",

            "sector_risk_level"

        ]

    ].head()

)

               sector  weighted_company_risk sector_risk_level
0     General Markets              36.021004               Low
1  Financial Services              35.154853               Low
2           Corporate              36.196193               Low
3          Technology              36.718451               Low
4         Commodities              37.259902               Low

## 49. Market Stability Category

In [59]:
def stability_category(score):

    if score >= 95:
        return "Very Stable"

    elif score >= 85:
        return "Stable"

    elif score >= 70:
        return "Moderate"

    else:
        return "Volatile"


sector_profile["market_stability_category"] = (

    sector_profile["weighted_market_stability"]

    .apply(stability_category)

)

display(

    sector_profile[

        [

            "sector",

            "weighted_market_stability",

            "market_stability_category"

        ]

    ].head()

)

               sector  weighted_market_stability market_stability_category
0     General Markets                  94.918737                    Stable
1  Financial Services                  94.761747                    Stable
2           Corporate                  95.276937               Very Stable
3          Technology                  96.303134               Very Stable
4         Commodities                  94.196712                    Stable

## 50. Company Intelligence Category

In [60]:
def company_strength(score):

    if score >= 80:
        return "Excellent"

    elif score >= 65:
        return "Strong"

    elif score >= 50:
        return "Average"

    else:
        return "Weak"


sector_profile["company_strength"] = (

    sector_profile["weighted_company_score"]

    .apply(company_strength)

)

display(

    sector_profile[

        [

            "sector",

            "weighted_company_score",

            "company_strength"

        ]

    ].head()

)

               sector  weighted_company_score company_strength
0     General Markets               60.402772          Average
1  Financial Services               60.863006          Average
2           Corporate               60.397335          Average
3          Technology               59.057320          Average
4         Commodities               58.993467          Average

## 51. Sector Risk Fingerprint

In [64]:
def build_sector_risk_fingerprint(row):

    tags = []

    if row["sector_risk_level"] in ["Very Low", "Low"]:
        tags.append("Low Risk")

    elif row["sector_risk_level"] == "Medium":
        tags.append("Moderate Risk")

    else:
        tags.append("High Risk")

    if row["market_stability_category"] == "Very Stable":
        tags.append("Stable Market")

    elif row["market_stability_category"] == "Stable":
        tags.append("Balanced Market")

    if row["company_strength"] in ["Strong", "Excellent"]:
        tags.append("Strong Companies")

    if row["event_diversity"] >= 20:
        tags.append("Highly Diversified")

    if row["coverage_score"] >= 100:
        tags.append("High Coverage")

    return ", ".join(tags)


sector_profile["sector_risk_fingerprint"] = (

    sector_profile

    .apply(

        build_sector_risk_fingerprint,

        axis=1

    )

)

display(

    sector_profile[

        [

            "sector",

            "sector_risk_fingerprint"

        ]

    ].head(10)

)

               sector                            sector_risk_fingerprint
0     General Markets  Low Risk, Balanced Market, Highly Diversified,...
1  Financial Services           Low Risk, Balanced Market, High Coverage
2           Corporate             Low Risk, Stable Market, High Coverage
3          Technology             Low Risk, Stable Market, High Coverage
4         Commodities           Low Risk, Balanced Market, High Coverage
5          Healthcare      Low Risk, Balanced Market, Highly Diversified
6      Macroeconomics                            Low Risk, Stable Market
7              Energy      Low Risk, Balanced Market, Highly Diversified
8      Cryptocurrency                            Low Risk, Stable Market
9       Cybersecurity                     Moderate Risk, Balanced Market

## 52. Sector Intelligence Summary

In [65]:
sector_profile["risk_summary"] = (

    "Risk: "

    + sector_profile["sector_risk_level"]

    + " | Company Strength: "

    + sector_profile["company_strength"]

    + " | Market: "

    + sector_profile["market_stability_category"]

    + " | Companies: "

    + sector_profile["companies_x"].astype(str)

)

## 53. Validation

In [66]:
display(

    sector_profile[

        [

            "sector_rank",

            "sector",

            "sector_intelligence_score",

            "sector_risk_level",

            "company_strength",

            "market_stability_category",

            "sector_risk_fingerprint",

            "risk_summary"

        ]

    ].head(20)

)

,sector_rank,sector,sector_intelligence_score,sector_risk_level,company_strength,market_stability_category,sector_risk_fingerprint,risk_summary
0,1,General Markets,85.754461,Low,Average,Stable,"Low Risk, Balanced Market, Highly Diversified,...",Risk: Low | Company Strength: Average | Market...
1,2,Financial Services,71.597915,Low,Average,Stable,"Low Risk, Balanced Market, High Coverage",Risk: Low | Company Strength: Average | Market...
2,3,Corporate,70.512834,Low,Average,Very Stable,"Low Risk, Stable Market, High Coverage",Risk: Low | Company Strength: Average | Market...
3,4,Technology,68.178981,Low,Average,Very Stable,"Low Risk, Stable Market, High Coverage",Risk: Low | Company Strength: Average | Market...
4,5,Commodities,63.356337,Low,Average,Stable,"Low Risk, Balanced Market, High Coverage",Risk: Low | Company Strength: Average | Market...
5,6,Healthcare,61.331079,Low,Average,Stable,"Low Risk, Balanced Market, Highly Diversified",Risk: Low | Company Strength: Average | Market...
6,7,Macroeconomics,61.066999,Low,Average,Very Stable,"Low Risk, Stable Market",Risk: Low | Company Strength: Average | Market...
7,8,Energy,60.588049,Low,Average,Stable,"Low Risk, Balanced Market, Highly Diversified",Risk: Low | Company Strength: Average | Market...
8,9,Cryptocurrency,60.472661,Low,Average,Very Stable,"Low Risk, Stable Market",Risk: Low | Company Strength: Average | Market...
9,10,Cybersecurity,58.998539,Medium,Average,Stable,"Moderate Risk, Balanced Market",Risk: Medium | Company Strength: Average | Mar...
10,11,Banking,56.554188,Low,Average,Stable,"Low Risk, Balanced Market, Highly Diversified",Risk: Low | Company Strength: Average | Market...
11,12,Real Estate,55.330319,Low,Average,Very Stable,"Low Risk, Stable Market",Risk: Low | Company Strength: Average | Market...
12,13,Automotive,51.146034,Low,Average,Stable,"Low Risk, Balanced Market, Highly Diversified",Risk: Low | Company Strength: Average | Market...
13,14,Semiconductors,51.074839,Low,Average,Very Stable,"Low Risk, Stable Market, Highly Diversified",Risk: Low | Company Strength: Average | Market...
14,15,Artificial Intelligence,50.882945,Low,Average,Very Stable,"Low Risk, Stable Market",Risk: Low | Company Strength: Average | Market...
15,16,Retail,50.546851,Low,Average,Very Stable,"Low Risk, Stable Market, Highly Diversified",Risk: Low | Company Strength: Average | Market...
16,17,Pharmaceuticals,50.426683,Low,Average,Stable,"Low Risk, Balanced Market, Highly Diversified",Risk: Low | Company Strength: Average | Market...
17,18,Media,50.371306,Low,Strong,Stable,"Low Risk, Balanced Market, Strong Companies, H...",Risk: Low | Company Strength: Strong | Market:...
18,19,Insurance,49.389860,Low,Average,Very Stable,"Low Risk, Stable Market",Risk: Low | Company Strength: Average | Market...
19,20,FinTech,49.365379,Low,Strong,Stable,"Low Risk, Balanced Market, Strong Companies, H...",Risk: Low | Company Strength: Strong | Market:...

# 6. Sector Relationship & Knowledge Graph

## 54. Build Sector × Company Matrix

In [67]:
sector_company_matrix = (

    financial_df

    .pivot_table(

        index="sector",

        columns="ticker",

        values="news_id",

        aggfunc="count",

        fill_value=0

    )

)

print(sector_company_matrix.shape)

display(

    sector_company_matrix.iloc[:5, :5]

)

(28, 6619)

ticker                   A  AA  AAC  AADR  AAL
sector
Artificial Intelligence  0   0    0     0    0
Automotive               0   4    0     0    0
Banking                  3   6    2     0    0
Biotechnology            0   0    0     0    0
Cloud Computing          0   0    0     0    0

## 55. Sector Similarity Matrix

In [68]:
from sklearn.metrics.pairwise import cosine_similarity

sector_similarity = pd.DataFrame(

    cosine_similarity(

        sector_company_matrix

    ),

    index=sector_company_matrix.index,

    columns=sector_company_matrix.index

)

print(sector_similarity.shape)

display(

    sector_similarity.iloc[:5,:5]

)

(28, 28)

sector,Artificial Intelligence,Automotive,Banking,Biotechnology,Cloud Computing
sector,,,,,
Artificial Intelligence,1.000000,0.069653,0.107503,0.024276,0.071194
Automotive,0.069653,1.000000,0.040470,0.011278,0.013098
Banking,0.107503,0.040470,1.000000,0.046756,0.052125
Biotechnology,0.024276,0.011278,0.046756,1.000000,0.003360
Cloud Computing,0.071194,0.013098,0.052125,0.003360,1.000000

## 56. Find Strong Sector Relationships

In [73]:
sector_edges = []

threshold = 0.55

for i in range(len(sector_similarity)):

    for j in range(i+1,len(sector_similarity)):

        sim = sector_similarity.iloc[i,j]

        if sim >= threshold:

            sector_edges.append({

                "sector_1":sector_similarity.index[i],

                "sector_2":sector_similarity.index[j],

                "similarity":round(sim,4)

            })

sector_edges = pd.DataFrame(

    sector_edges

)

print(sector_edges.shape)

display(

    sector_edges.head(20)

)

(10, 3)

             sector_1            sector_2  similarity
0       Biotechnology          Healthcare      0.5892
1           Corporate  Financial Services      0.8127
2           Corporate     General Markets      0.8343
3           Corporate          Technology      0.8035
4  Financial Services     General Markets      0.8773
5  Financial Services               Other      0.5531
6  Financial Services          Technology      0.7781
7     General Markets               Other      0.5783
8     General Markets          Technology      0.8910
9          Healthcare     Pharmaceuticals      0.7197

## 57. Shared Company Count

In [74]:
company_sets = {}

for sector in financial_df["sector"].unique():

    company_sets[sector] = set(

        financial_df.loc[

            financial_df["sector"]==sector,

            "ticker"

        ].unique()

    )

In [75]:
shared_companies = []

for s1 in company_sets:

    for s2 in company_sets:

        if s1 >= s2:

            continue

        overlap = len(

            company_sets[s1]

            &

            company_sets[s2]

        )

        if overlap>0:

            shared_companies.append({

                "sector_1":s1,

                "sector_2":s2,

                "shared_companies":overlap

            })

shared_companies = pd.DataFrame(

    shared_companies

)

display(

    shared_companies.head()

)

          sector_1         sector_2  shared_companies
0  General Markets       Healthcare              2685
1  General Markets       Technology              6402
2  General Markets  Pharmaceuticals               716
3  General Markets   Macroeconomics              3419
4  General Markets            Other              1159

## 58. Merge Similarity + Shared Companies

In [76]:
sector_network = (

    sector_edges

    .merge(

        shared_companies,

        on=[

            "sector_1",

            "sector_2"

        ],

        how="left"

    )

)

sector_network["shared_companies"] = (

    sector_network["shared_companies"]

    .fillna(0)

    .astype(int)

)

display(

    sector_network.head(20)

)

             sector_1            sector_2  similarity  shared_companies
0       Biotechnology          Healthcare      0.5892               409
1           Corporate  Financial Services      0.8127              5711
2           Corporate     General Markets      0.8343              5961
3           Corporate          Technology      0.8035              5897
4  Financial Services     General Markets      0.8773              6097
5  Financial Services               Other      0.5531              1150
6  Financial Services          Technology      0.7781              6023
7     General Markets               Other      0.5783              1159
8     General Markets          Technology      0.8910              6402
9          Healthcare     Pharmaceuticals      0.7197               639

## 59. Build the Graph

In [77]:
import networkx as nx

sector_graph = nx.Graph()

for _, row in sector_network.iterrows():

    sector_graph.add_edge(

        row["sector_1"],

        row["sector_2"],

        similarity=row["similarity"],

        shared_companies=row["shared_companies"]

    )

print("Nodes :", sector_graph.number_of_nodes())

print("Edges :", sector_graph.number_of_edges())

Nodes : 8
Edges : 10

## 60. Degree Centrality

In [78]:
degree = nx.degree_centrality(

    sector_graph

)

degree = pd.DataFrame({

    "sector": degree.keys(),

    "degree_centrality": degree.values()

})

degree = degree.sort_values(

    "degree_centrality",

    ascending=False

)

display(degree)

               sector  degree_centrality
3  Financial Services           0.571429
4     General Markets           0.571429
5          Technology           0.428571
2           Corporate           0.428571
6               Other           0.285714
1          Healthcare           0.285714
0       Biotechnology           0.142857
7     Pharmaceuticals           0.142857

## 61. Betweenness Centrality

In [79]:
betweenness = nx.betweenness_centrality(

    sector_graph,

    weight="similarity"

)

betweenness = pd.DataFrame({

    "sector": betweenness.keys(),

    "betweenness": betweenness.values()

})

betweenness = betweenness.sort_values(

    "betweenness",

    ascending=False

)

display(betweenness)

               sector  betweenness
3  Financial Services     0.095238
1          Healthcare     0.047619
0       Biotechnology     0.000000
2           Corporate     0.000000
4     General Markets     0.000000
5          Technology     0.000000
6               Other     0.000000
7     Pharmaceuticals     0.000000

## 62. Closeness Centrality

In [80]:
closeness = nx.closeness_centrality(

    sector_graph

)

closeness = pd.DataFrame({

    "sector": closeness.keys(),

    "closeness": closeness.values()

})

closeness = closeness.sort_values(

    "closeness",

    ascending=False

)

display(closeness)

               sector  closeness
3  Financial Services   0.571429
4     General Markets   0.571429
5          Technology   0.457143
2           Corporate   0.457143
6               Other   0.380952
1          Healthcare   0.285714
0       Biotechnology   0.190476
7     Pharmaceuticals   0.190476

## 63. Merge All Centralities

In [81]:
sector_network_metrics = (

    degree

    .merge(

        betweenness,

        on="sector"

    )

    .merge(

        closeness,

        on="sector"

    )

)

display(

    sector_network_metrics

)

               sector  degree_centrality  betweenness  closeness
0  Financial Services           0.571429     0.095238   0.571429
1     General Markets           0.571429     0.000000   0.571429
2          Technology           0.428571     0.000000   0.457143
3           Corporate           0.428571     0.000000   0.457143
4               Other           0.285714     0.000000   0.380952
5          Healthcare           0.285714     0.047619   0.285714
6       Biotechnology           0.142857     0.000000   0.190476
7     Pharmaceuticals           0.142857     0.000000   0.190476

## 64. Network Influence Score

In [82]:
sector_network_metrics["network_influence"] = (

      sector_network_metrics["degree_centrality"] * 0.40

    + sector_network_metrics["betweenness"] * 0.35

    + sector_network_metrics["closeness"] * 0.25

)

sector_network_metrics = (

    sector_network_metrics

    .sort_values(

        "network_influence",

        ascending=False

    )

    .reset_index(drop=True)

)

sector_network_metrics["network_rank"] = (

    np.arange(

        1,

        len(sector_network_metrics)+1

    )

)

display(

    sector_network_metrics

)

,sector,degree_centrality,betweenness,closeness,network_influence,network_rank
0,Financial Services,0.571429,0.095238,0.571429,0.404762,1
1,General Markets,0.571429,0.000000,0.571429,0.371429,2
2,Technology,0.428571,0.000000,0.457143,0.285714,3
3,Corporate,0.428571,0.000000,0.457143,0.285714,4
4,Other,0.285714,0.000000,0.380952,0.209524,5
5,Healthcare,0.285714,0.047619,0.285714,0.202381,6
6,Biotechnology,0.142857,0.000000,0.190476,0.104762,7
7,Pharmaceuticals,0.142857,0.000000,0.190476,0.104762,8

## 65. Community Detection (Sector Clusters)

In [83]:
from networkx.algorithms.community import greedy_modularity_communities

In [85]:
communities = list(
    greedy_modularity_communities(sector_graph)
)

print("Communities :", len(communities))

Communities : 2

In [86]:
community_table = []

for community_id, community in enumerate(communities):

    for sector in community:

        community_table.append({

            "sector": sector,

            "community": community_id,

            "community_size": len(community)

        })

community_table = pd.DataFrame(community_table)

display(community_table)

               sector  community  community_size
0     General Markets          0               5
1           Corporate          0               5
2          Technology          0               5
3  Financial Services          0               5
4               Other          0               5
5     Pharmaceuticals          1               3
6       Biotechnology          1               3
7          Healthcare          1               3

## 66. Cluster Summary

In [87]:
sector_profile = sector_profile.merge(

    community_table,

    on="sector",

    how="left"

)

In [88]:
cluster_summary = (

    sector_profile

    .groupby("community")

    .agg(

        sectors=("sector","count"),

        avg_intelligence=("sector_intelligence_score","mean"),

        avg_risk=("weighted_company_risk","mean"),

        strongest_sector=(

            "sector",

            lambda x: x.iloc[

                sector_profile.loc[x.index,"sector_intelligence_score"].argmax()

            ]

        )

    )

    .reset_index()

)

display(cluster_summary)

   community  sectors  avg_intelligence   avg_risk strongest_sector
0        0.0        5         66.607566  36.097140  General Markets
1        1.0        3         53.412047  35.097812       Healthcare

## 67. Sector Knowledge Cards

### Company Strength

In [89]:
sector_profile["company_strength"] = np.where(

    sector_profile["weighted_company_score"] >= 70,

    "Very Strong",

    np.where(

        sector_profile["weighted_company_score"] >= 60,

        "Strong",

        np.where(

            sector_profile["weighted_company_score"] >= 50,

            "Average",

            "Weak"

        )

    )

)

### Network Importance

In [91]:
sector_profile = sector_profile.merge(

    sector_network_metrics[

        [

            "sector",

            "network_rank",

            "network_influence"

        ]

    ],

    on="sector",

    how="left"

)

### Fill sectors that are isolated.

In [92]:
sector_profile["network_rank"] = sector_profile["network_rank"].fillna(0).astype(int)

sector_profile["network_influence"] = sector_profile["network_influence"].fillna(0)

### Knowledge Card

In [114]:
# sector_profile["community"] = (

#     sector_profile["community"]

#     .fillna("Independent")

# )

# sector_profile["community_size"] = (

#     sector_profile["community_size"]

#     .fillna(1)

#     .astype(int)

# )

# sector_profile["network_rank"] = (

#     sector_profile["network_rank"]

#     .fillna(0)

#     .astype(int)

# )

# sector_profile["network_influence"] = (

#     sector_profile["network_influence"]

#     .fillna(0)

# )
sector_profile["community"] = (

    sector_profile["community"]

    .fillna("Independent")

)

sector_profile["community_size"] = (

    sector_profile["community_size"]

    .fillna(1)

    .astype(int)

)

sector_profile["network_rank"] = (

    sector_profile["network_rank"]

    .fillna(0)

    .astype(int)

)

sector_profile["network_influence"] = (

    sector_profile["network_influence"]

    .fillna(0)

)

In [115]:
sector_profile["community_display"] = (

    sector_profile["community"]

    .astype(str)

)

sector_profile.loc[

    sector_profile["community_display"] == "Independent",

    "community_display"

] = "Independent"

sector_profile["rank_display"] = np.where(

    sector_profile["network_rank"] == 0,

    "Not Connected",

    sector_profile["network_rank"].astype(str)

)

sector_profile["influence_display"] = np.where(

    sector_profile["network_rank"] == 0,

    "0",

    sector_profile["network_influence"].round(3).astype(str)

)

In [116]:
sector_profile["knowledge_card"] = (

    "Community: "

    + sector_profile["community_display"]

    + " | "

    + "Rank: "

    + sector_profile["rank_display"]

    + " | "

    + "Influence: "

    + sector_profile["influence_display"]

    + " | "

    + "Risk: "

    + sector_profile["sector_risk_level"]

    + " | "

    + "Strength: "

    + sector_profile["company_strength"]

)

In [117]:
display(

    sector_profile[

        [

            "sector",

            "community",

            "network_rank",

            "network_influence",

            "knowledge_card"

        ]

    ].head(15)

)

,sector,community,network_rank,network_influence,knowledge_card
0,General Markets,0.0,2,0.371429,Community: 0.0 | Rank: 2 | Influence: 0.371 | ...
1,Financial Services,0.0,1,0.404762,Community: 0.0 | Rank: 1 | Influence: 0.405 | ...
2,Corporate,0.0,4,0.285714,Community: 0.0 | Rank: 4 | Influence: 0.286 | ...
3,Technology,0.0,3,0.285714,Community: 0.0 | Rank: 3 | Influence: 0.286 | ...
4,Commodities,Independent,0,0.000000,Community: Independent | Rank: Not Connected |...
5,Healthcare,1.0,6,0.202381,Community: 1.0 | Rank: 6 | Influence: 0.202 | ...
6,Macroeconomics,Independent,0,0.000000,Community: Independent | Rank: Not Connected |...
7,Energy,Independent,0,0.000000,Community: Independent | Rank: Not Connected |...
8,Cryptocurrency,Independent,0,0.000000,Community: Independent | Rank: Not Connected |...
9,Cybersecurity,Independent,0,0.000000,Community: Independent | Rank: Not Connected |...
10,Banking,Independent,0,0.000000,Community: Independent | Rank: Not Connected |...
11,Real Estate,Independent,0,0.000000,Community: Independent | Rank: Not Connected |...
12,Automotive,Independent,0,0.000000,Community: Independent | Rank: Not Connected |...
13,Semiconductors,Independent,0,0.000000,Community: Independent | Rank: Not Connected |...
14,Artificial Intelligence,Independent,0,0.000000,Community: Independent | Rank: Not Connected |...

## 68. Sector Relationship Table

In [118]:
sector_relationships = (

    sector_network

    .sort_values(

        [

            "similarity",

            "shared_companies"

        ],

        ascending=False

    )

    .reset_index(drop=True)

)

display(sector_relationships)

             sector_1            sector_2  similarity  shared_companies
0     General Markets          Technology      0.8910              6402
1  Financial Services     General Markets      0.8773              6097
2           Corporate     General Markets      0.8343              5961
3           Corporate  Financial Services      0.8127              5711
4           Corporate          Technology      0.8035              5897
5  Financial Services          Technology      0.7781              6023
6          Healthcare     Pharmaceuticals      0.7197               639
7       Biotechnology          Healthcare      0.5892               409
8     General Markets               Other      0.5783              1159
9  Financial Services               Other      0.5531              1150

## 69. Final Sector Master Table

In [119]:
sector_master = sector_profile[

    [

        "sector_rank",

        "sector",

        "community",

        "community_size",

        "network_rank",

        "network_influence",

        "sector_intelligence_score",

        "sector_risk_level",

        "company_strength",

        "market_stability_category",

        "sector_risk_fingerprint",

        "knowledge_card"

    ]

].copy()


sector_master["community"] = (

    sector_master["community"]

    .fillna("Independent")

)

sector_master["community_size"] = (

    sector_master["community_size"]

    .fillna(1)

    .astype(int)

)

sector_master["network_rank"] = (

    sector_master["network_rank"]

    .fillna(0)

    .astype(int)

)

sector_master["network_influence"] = (

    sector_master["network_influence"]

    .fillna(0)

)

display(

    sector_master.head(20)

)

,sector_rank,sector,community,community_size,network_rank,network_influence,sector_intelligence_score,sector_risk_level,company_strength,market_stability_category,sector_risk_fingerprint,knowledge_card
0,1,General Markets,0.0,5,2,0.371429,85.754461,Low,Strong,Stable,"Low Risk, Balanced Market, Highly Diversified,...",Community: 0.0 | Rank: 2 | Influence: 0.371 | ...
1,2,Financial Services,0.0,5,1,0.404762,71.597915,Low,Strong,Stable,"Low Risk, Balanced Market, High Coverage",Community: 0.0 | Rank: 1 | Influence: 0.405 | ...
2,3,Corporate,0.0,5,4,0.285714,70.512834,Low,Strong,Very Stable,"Low Risk, Stable Market, High Coverage",Community: 0.0 | Rank: 4 | Influence: 0.286 | ...
3,4,Technology,0.0,5,3,0.285714,68.178981,Low,Average,Very Stable,"Low Risk, Stable Market, High Coverage",Community: 0.0 | Rank: 3 | Influence: 0.286 | ...
4,5,Commodities,Independent,1,0,0.000000,63.356337,Low,Average,Stable,"Low Risk, Balanced Market, High Coverage",Community: Independent | Rank: Not Connected |...
5,6,Healthcare,1.0,3,6,0.202381,61.331079,Low,Strong,Stable,"Low Risk, Balanced Market, Highly Diversified",Community: 1.0 | Rank: 6 | Influence: 0.202 | ...
6,7,Macroeconomics,Independent,1,0,0.000000,61.066999,Low,Average,Very Stable,"Low Risk, Stable Market",Community: Independent | Rank: Not Connected |...
7,8,Energy,Independent,1,0,0.000000,60.588049,Low,Strong,Stable,"Low Risk, Balanced Market, Highly Diversified",Community: Independent | Rank: Not Connected |...
8,9,Cryptocurrency,Independent,1,0,0.000000,60.472661,Low,Average,Very Stable,"Low Risk, Stable Market",Community: Independent | Rank: Not Connected |...
9,10,Cybersecurity,Independent,1,0,0.000000,58.998539,Medium,Strong,Stable,"Moderate Risk, Balanced Market",Community: Independent | Rank: Not Connected |...
10,11,Banking,Independent,1,0,0.000000,56.554188,Low,Strong,Stable,"Low Risk, Balanced Market, Highly Diversified",Community: Independent | Rank: Not Connected |...
11,12,Real Estate,Independent,1,0,0.000000,55.330319,Low,Strong,Very Stable,"Low Risk, Stable Market",Community: Independent | Rank: Not Connected |...
12,13,Automotive,Independent,1,0,0.000000,51.146034,Low,Strong,Stable,"Low Risk, Balanced Market, Highly Diversified",Community: Independent | Rank: Not Connected |...
13,14,Semiconductors,Independent,1,0,0.000000,51.074839,Low,Strong,Very Stable,"Low Risk, Stable Market, Highly Diversified",Community: Independent | Rank: Not Connected |...
14,15,Artificial Intelligence,Independent,1,0,0.000000,50.882945,Low,Strong,Very Stable,"Low Risk, Stable Market",Community: Independent | Rank: Not Connected |...
15,16,Retail,Independent,1,0,0.000000,50.546851,Low,Strong,Very Stable,"Low Risk, Stable Market, Highly Diversified",Community: Independent | Rank: Not Connected |...
16,17,Pharmaceuticals,1.0,3,8,0.104762,50.426683,Low,Strong,Stable,"Low Risk, Balanced Market, Highly Diversified",Community: 1.0 | Rank: 8 | Influence: 0.105 | ...
17,18,Media,Independent,1,0,0.000000,50.371306,Low,Strong,Stable,"Low Risk, Balanced Market, Strong Companies, H...",Community: Independent | Rank: Not Connected |...
18,19,Insurance,Independent,1,0,0.000000,49.389860,Low,Average,Very Stable,"Low Risk, Stable Market",Community: Independent | Rank: Not Connected |...
19,20,FinTech,Independent,1,0,0.000000,49.365379,Low,Strong,Stable,"Low Risk, Balanced Market, Strong Companies, H...",Community: Independent | Rank: Not Connected |...

## 70. Save

In [120]:
sector_profile.to_parquet(

    os.path.join(

        SECTOR_PATH,

        "sector_profile.parquet"

    ),

    index=False

)

ArrowInvalid: ("Could not convert 'Independent' with type str: tried to convert to double", 'Conversion failed for column community with type object')

In [121]:
sector_network_metrics.to_parquet(

    os.path.join(

        SECTOR_PATH,

        "sector_network_metrics.parquet"

    ),

    index=False

)

In [122]:
sector_relationships.to_parquet(

    os.path.join(

        SECTOR_PATH,

        "sector_relationships.parquet"

    ),

    index=False

)

In [123]:
cluster_summary.to_parquet(

    os.path.join(

        SECTOR_PATH,

        "sector_clusters.parquet"

    ),

    index=False

)

In [125]:
print(sector_master["community"].dtype)

print(
    sector_master["community"]
    .apply(type)
    .value_counts()
)

object
community
<class 'str'>      20
<class 'float'>     8
Name: count, dtype: int64

In [126]:
sector_master["community"] = (

    sector_master["community"]

    .fillna("Independent")

    .astype(str)

)

sector_master["community_size"] = (

    sector_master["community_size"]

    .fillna(1)

    .astype(int)

)

sector_master["network_rank"] = (

    sector_master["network_rank"]

    .fillna(0)

    .astype(int)

)

sector_master["network_influence"] = (

    sector_master["network_influence"]

    .fillna(0)

    .astype(float)

)

In [127]:
sector_master.to_parquet(

    os.path.join(

        SECTOR_PATH,

        "sector_master.parquet"

    ),

    index=False

)

# 7. Sector Temporal Intelligence Engine

## 71. Create Monthly Sector Timeline

In [128]:
sector_timeline = (

    financial_df

    .groupby(

        [

            "sector",

            "year",

            "month"

        ]

    )

    .agg(

        news_count=("news_id", "count"),

        companies=("ticker", "nunique"),

        publishers=("publisher", "nunique"),

        avg_confidence=("sector_confidence", "mean")

    )

    .reset_index()

)

display(
    sector_timeline.head(20)
)

,sector,year,month,news_count,companies,publishers,avg_confidence
0,Artificial Intelligence,2010,1,1,1,1,1.0000
1,Artificial Intelligence,2010,5,1,1,1,1.0000
2,Artificial Intelligence,2010,9,2,2,1,1.0000
3,Artificial Intelligence,2010,10,6,6,1,1.0000
4,Artificial Intelligence,2010,11,2,2,2,1.0000
5,Artificial Intelligence,2011,5,1,1,1,1.0000
6,Artificial Intelligence,2011,10,1,1,1,1.0000
7,Artificial Intelligence,2011,11,2,1,1,1.0000
8,Artificial Intelligence,2012,5,2,1,2,0.7500
9,Artificial Intelligence,2012,6,1,1,1,1.0000
10,Artificial Intelligence,2012,8,1,1,1,1.0000
11,Artificial Intelligence,2013,3,1,1,1,1.0000
12,Artificial Intelligence,2013,11,2,2,2,0.4285
13,Artificial Intelligence,2014,7,2,2,1,1.0000
14,Artificial Intelligence,2014,11,1,1,1,1.0000
15,Artificial Intelligence,2015,1,3,3,1,1.0000
16,Artificial Intelligence,2015,5,1,1,1,1.0000
17,Artificial Intelligence,2015,7,1,1,1,1.0000
18,Artificial Intelligence,2015,8,1,1,1,1.0000
19,Artificial Intelligence,2015,9,4,3,2,0.7030

## 72. Create Date Column

In [129]:
sector_timeline["date"] = pd.to_datetime(

    dict(

        year=sector_timeline["year"],

        month=sector_timeline["month"],

        day=1

    )

)

display(

    sector_timeline.head()

)

,sector,year,month,news_count,companies,publishers,avg_confidence,date
0,Artificial Intelligence,2010,1,1,1,1,1.0,2010-01-01
1,Artificial Intelligence,2010,5,1,1,1,1.0,2010-05-01
2,Artificial Intelligence,2010,9,2,2,1,1.0,2010-09-01
3,Artificial Intelligence,2010,10,6,6,1,1.0,2010-10-01
4,Artificial Intelligence,2010,11,2,2,2,1.0,2010-11-01

## 73. Sort Chronologically

In [130]:
sector_timeline = (

    sector_timeline

    .sort_values(

        [

            "sector",

            "date"

        ]

    )

    .reset_index(drop=True)

)

display(

    sector_timeline.head(20)

)

,sector,year,month,news_count,companies,publishers,avg_confidence,date
0,Artificial Intelligence,2010,1,1,1,1,1.0000,2010-01-01
1,Artificial Intelligence,2010,5,1,1,1,1.0000,2010-05-01
2,Artificial Intelligence,2010,9,2,2,1,1.0000,2010-09-01
3,Artificial Intelligence,2010,10,6,6,1,1.0000,2010-10-01
4,Artificial Intelligence,2010,11,2,2,2,1.0000,2010-11-01
5,Artificial Intelligence,2011,5,1,1,1,1.0000,2011-05-01
6,Artificial Intelligence,2011,10,1,1,1,1.0000,2011-10-01
7,Artificial Intelligence,2011,11,2,1,1,1.0000,2011-11-01
8,Artificial Intelligence,2012,5,2,1,2,0.7500,2012-05-01
9,Artificial Intelligence,2012,6,1,1,1,1.0000,2012-06-01
10,Artificial Intelligence,2012,8,1,1,1,1.0000,2012-08-01
11,Artificial Intelligence,2013,3,1,1,1,1.0000,2013-03-01
12,Artificial Intelligence,2013,11,2,2,2,0.4285,2013-11-01
13,Artificial Intelligence,2014,7,2,2,1,1.0000,2014-07-01
14,Artificial Intelligence,2014,11,1,1,1,1.0000,2014-11-01
15,Artificial Intelligence,2015,1,3,3,1,1.0000,2015-01-01
16,Artificial Intelligence,2015,5,1,1,1,1.0000,2015-05-01
17,Artificial Intelligence,2015,7,1,1,1,1.0000,2015-07-01
18,Artificial Intelligence,2015,8,1,1,1,1.0000,2015-08-01
19,Artificial Intelligence,2015,9,4,3,2,0.7030,2015-09-01

## 74. Monthly Growth Rate

In [132]:
sector_timeline["previous_news"] = (

    sector_timeline

    .groupby("sector")["news_count"]

    .shift(1)

)

sector_timeline["growth_rate"] = (

    (

        sector_timeline["news_count"]

        -

        sector_timeline["previous_news"]

    )

    /

    sector_timeline["previous_news"]

)

sector_timeline["growth_rate"] = (

    sector_timeline["growth_rate"]

    .replace(

        [

            np.inf,

            -np.inf

        ],

        np.nan

    )

)

display(

    sector_timeline.head(20)

)

,sector,year,month,news_count,companies,publishers,avg_confidence,date,previous_news,growth_rate
0,Artificial Intelligence,2010,1,1,1,1,1.0000,2010-01-01,NaN,NaN
1,Artificial Intelligence,2010,5,1,1,1,1.0000,2010-05-01,1.0,0.000000
2,Artificial Intelligence,2010,9,2,2,1,1.0000,2010-09-01,1.0,1.000000
3,Artificial Intelligence,2010,10,6,6,1,1.0000,2010-10-01,2.0,2.000000
4,Artificial Intelligence,2010,11,2,2,2,1.0000,2010-11-01,6.0,-0.666667
5,Artificial Intelligence,2011,5,1,1,1,1.0000,2011-05-01,2.0,-0.500000
6,Artificial Intelligence,2011,10,1,1,1,1.0000,2011-10-01,1.0,0.000000
7,Artificial Intelligence,2011,11,2,1,1,1.0000,2011-11-01,1.0,1.000000
8,Artificial Intelligence,2012,5,2,1,2,0.7500,2012-05-01,2.0,0.000000
9,Artificial Intelligence,2012,6,1,1,1,1.0000,2012-06-01,2.0,-0.500000
10,Artificial Intelligence,2012,8,1,1,1,1.0000,2012-08-01,1.0,0.000000
11,Artificial Intelligence,2013,3,1,1,1,1.0000,2013-03-01,1.0,0.000000
12,Artificial Intelligence,2013,11,2,2,2,0.4285,2013-11-01,1.0,1.000000
13,Artificial Intelligence,2014,7,2,2,1,1.0000,2014-07-01,2.0,0.000000
14,Artificial Intelligence,2014,11,1,1,1,1.0000,2014-11-01,2.0,-0.500000
15,Artificial Intelligence,2015,1,3,3,1,1.0000,2015-01-01,1.0,2.000000
16,Artificial Intelligence,2015,5,1,1,1,1.0000,2015-05-01,3.0,-0.666667
17,Artificial Intelligence,2015,7,1,1,1,1.0000,2015-07-01,1.0,0.000000
18,Artificial Intelligence,2015,8,1,1,1,1.0000,2015-08-01,1.0,0.000000
19,Artificial Intelligence,2015,9,4,3,2,0.7030,2015-09-01,1.0,3.000000

## 75. Rolling Average (3 Months)

In [133]:
sector_timeline["rolling_news"] = (

    sector_timeline

    .groupby("sector")["news_count"]

    .transform(

        lambda x:

        x.rolling(

            3,

            min_periods=1

        ).mean()

    )

)

display(

    sector_timeline.head(20)

)

,sector,year,month,news_count,companies,publishers,avg_confidence,date,previous_news,growth_rate,rolling_news
0,Artificial Intelligence,2010,1,1,1,1,1.0000,2010-01-01,NaN,NaN,1.000000
1,Artificial Intelligence,2010,5,1,1,1,1.0000,2010-05-01,1.0,0.000000,1.000000
2,Artificial Intelligence,2010,9,2,2,1,1.0000,2010-09-01,1.0,1.000000,1.333333
3,Artificial Intelligence,2010,10,6,6,1,1.0000,2010-10-01,2.0,2.000000,3.000000
4,Artificial Intelligence,2010,11,2,2,2,1.0000,2010-11-01,6.0,-0.666667,3.333333
5,Artificial Intelligence,2011,5,1,1,1,1.0000,2011-05-01,2.0,-0.500000,3.000000
6,Artificial Intelligence,2011,10,1,1,1,1.0000,2011-10-01,1.0,0.000000,1.333333
7,Artificial Intelligence,2011,11,2,1,1,1.0000,2011-11-01,1.0,1.000000,1.333333
8,Artificial Intelligence,2012,5,2,1,2,0.7500,2012-05-01,2.0,0.000000,1.666667
9,Artificial Intelligence,2012,6,1,1,1,1.0000,2012-06-01,2.0,-0.500000,1.666667
10,Artificial Intelligence,2012,8,1,1,1,1.0000,2012-08-01,1.0,0.000000,1.333333
11,Artificial Intelligence,2013,3,1,1,1,1.0000,2013-03-01,1.0,0.000000,1.000000
12,Artificial Intelligence,2013,11,2,2,2,0.4285,2013-11-01,1.0,1.000000,1.333333
13,Artificial Intelligence,2014,7,2,2,1,1.0000,2014-07-01,2.0,0.000000,1.666667
14,Artificial Intelligence,2014,11,1,1,1,1.0000,2014-11-01,2.0,-0.500000,1.666667
15,Artificial Intelligence,2015,1,3,3,1,1.0000,2015-01-01,1.0,2.000000,2.000000
16,Artificial Intelligence,2015,5,1,1,1,1.0000,2015-05-01,3.0,-0.666667,1.666667
17,Artificial Intelligence,2015,7,1,1,1,1.0000,2015-07-01,1.0,0.000000,1.666667
18,Artificial Intelligence,2015,8,1,1,1,1.0000,2015-08-01,1.0,0.000000,1.000000
19,Artificial Intelligence,2015,9,4,3,2,0.7030,2015-09-01,1.0,3.000000,2.000000

## 76. Calculate Momentum Score

In [134]:
sector_timeline["previous_rolling"] = (

    sector_timeline

    .groupby("sector")["rolling_news"]

    .shift(1)

)

sector_timeline["momentum_score"] = (

    sector_timeline["rolling_news"]

    -

    sector_timeline["previous_rolling"]

)

sector_timeline["momentum_score"] = (

    sector_timeline["momentum_score"]

    .fillna(0)

)

display(

    sector_timeline[

        [

            "sector",

            "date",

            "rolling_news",

            "momentum_score"

        ]

    ].head(20)

)

                     sector       date  rolling_news  momentum_score
0   Artificial Intelligence 2010-01-01      1.000000        0.000000
1   Artificial Intelligence 2010-05-01      1.000000        0.000000
2   Artificial Intelligence 2010-09-01      1.333333        0.333333
3   Artificial Intelligence 2010-10-01      3.000000        1.666667
4   Artificial Intelligence 2010-11-01      3.333333        0.333333
5   Artificial Intelligence 2011-05-01      3.000000       -0.333333
6   Artificial Intelligence 2011-10-01      1.333333       -1.666667
7   Artificial Intelligence 2011-11-01      1.333333        0.000000
8   Artificial Intelligence 2012-05-01      1.666667        0.333333
9   Artificial Intelligence 2012-06-01      1.666667        0.000000
10  Artificial Intelligence 2012-08-01      1.333333       -0.333333
11  Artificial Intelligence 2013-03-01      1.000000       -0.333333
12  Artificial Intelligence 2013-11-01      1.333333        0.333333
13  Artificial Intelligence 2014-07-01      1.666667        0.333333
14  Artificial Intelligence 2014-11-01      1.666667        0.000000
15  Artificial Intelligence 2015-01-01      2.000000        0.333333
16  Artificial Intelligence 2015-05-01      1.666667       -0.333333
17  Artificial Intelligence 2015-07-01      1.666667        0.000000
18  Artificial Intelligence 2015-08-01      1.000000       -0.666667
19  Artificial Intelligence 2015-09-01      2.000000        1.000000

## 77. Detect Trend Direction

In [135]:
def trend_direction(x):

    if x > 0.25:

        return "Growing"

    elif x < -0.25:

        return "Declining"

    else:

        return "Stable"


sector_timeline["trend"] = (

    sector_timeline["momentum_score"]

    .apply(trend_direction)

)

display(

    sector_timeline[

        [

            "sector",

            "date",

            "news_count",

            "rolling_news",

            "momentum_score",

            "trend"

        ]

    ].head(20)

)

,sector,date,news_count,rolling_news,momentum_score,trend
0,Artificial Intelligence,2010-01-01,1,1.000000,0.000000,Stable
1,Artificial Intelligence,2010-05-01,1,1.000000,0.000000,Stable
2,Artificial Intelligence,2010-09-01,2,1.333333,0.333333,Growing
3,Artificial Intelligence,2010-10-01,6,3.000000,1.666667,Growing
4,Artificial Intelligence,2010-11-01,2,3.333333,0.333333,Growing
5,Artificial Intelligence,2011-05-01,1,3.000000,-0.333333,Declining
6,Artificial Intelligence,2011-10-01,1,1.333333,-1.666667,Declining
7,Artificial Intelligence,2011-11-01,2,1.333333,0.000000,Stable
8,Artificial Intelligence,2012-05-01,2,1.666667,0.333333,Growing
9,Artificial Intelligence,2012-06-01,1,1.666667,0.000000,Stable
10,Artificial Intelligence,2012-08-01,1,1.333333,-0.333333,Declining
11,Artificial Intelligence,2013-03-01,1,1.000000,-0.333333,Declining
12,Artificial Intelligence,2013-11-01,2,1.333333,0.333333,Growing
13,Artificial Intelligence,2014-07-01,2,1.666667,0.333333,Growing
14,Artificial Intelligence,2014-11-01,1,1.666667,0.000000,Stable
15,Artificial Intelligence,2015-01-01,3,2.000000,0.333333,Growing
16,Artificial Intelligence,2015-05-01,1,1.666667,-0.333333,Declining
17,Artificial Intelligence,2015-07-01,1,1.666667,0.000000,Stable
18,Artificial Intelligence,2015-08-01,1,1.000000,-0.666667,Declining
19,Artificial Intelligence,2015-09-01,4,2.000000,1.000000,Growing

### 78. Peak Activity Detection

In [136]:
sector_peak = (

    sector_timeline

    .loc[

        sector_timeline

        .groupby("sector")["news_count"]

        .idxmax()

    ]

    .reset_index(drop=True)

)

display(

    sector_peak[

        [

            "sector",

            "date",

            "news_count"

        ]

    ].head(20)

)

                     sector       date  news_count
0   Artificial Intelligence 2017-11-01          22
1                Automotive 2020-03-01          75
2                   Banking 2015-06-01         146
3             Biotechnology 2018-06-01          99
4           Cloud Computing 2016-10-01          10
5               Commodities 2019-08-01        2891
6            Consumer Goods 2013-02-01          31
7                 Corporate 2020-05-01        7331
8            Cryptocurrency 2017-12-01         570
9             Cybersecurity 2018-11-01         233
10        Electric Vehicles 2020-02-01          60
11                   Energy 2019-09-01         970
12                  FinTech 2017-06-01          48
13       Financial Services 2019-11-01        6988
14          General Markets 2019-10-01       30012
15               Healthcare 2018-08-01         779
16                Insurance 2018-03-01           5
17           Macroeconomics 2019-06-01        1021
18                    Media 2016-11-01          65
19                   Mining 2016-09-01          16

## 79. Overall Temporal Statistics

In [137]:
sector_temporal = (

    sector_timeline

    .groupby("sector")

    .agg(

        first_month=("date","min"),

        latest_month=("date","max"),

        active_months=("date","count"),

        average_news=("news_count","mean"),

        max_news=("news_count","max"),

        average_growth=("growth_rate","mean"),

        average_momentum=("momentum_score","mean")

    )

    .reset_index()

)

display(

    sector_temporal.head(20)

)

,sector,first_month,latest_month,active_months,average_news,max_news,average_growth,average_momentum
0,Artificial Intelligence,2010-01-01,2020-05-01,68,3.602941,22,0.500090,0.049020
1,Automotive,2009-08-01,2020-06-01,131,27.190840,75,0.283053,0.264631
2,Banking,2009-08-01,2020-06-01,131,62.274809,146,0.216331,0.279898
3,Biotechnology,2009-08-01,2020-05-01,104,13.875000,99,1.518083,0.429487
4,Cloud Computing,2010-03-01,2020-04-01,50,2.180000,10,0.680466,0.020000
5,Commodities,2009-07-01,2020-06-01,132,1099.431818,2891,0.849205,7.121212
6,Consumer Goods,2009-12-01,2020-05-01,88,5.068182,31,1.049125,-0.003788
7,Corporate,2009-07-01,2020-06-01,132,2314.765152,7331,0.778007,32.121212
8,Cryptocurrency,2009-02-01,2020-06-01,133,101.000000,570,0.261559,0.170426
9,Cybersecurity,2009-08-01,2020-06-01,130,54.630769,233,0.239196,0.346154
10,Electric Vehicles,2009-10-01,2020-06-01,106,11.481132,60,0.712834,0.163522
11,Energy,2009-07-01,2020-06-01,132,312.454545,970,0.252319,1.459596
12,FinTech,2009-10-01,2020-06-01,127,11.944882,48,0.577315,0.065617
13,Financial Services,2009-05-01,2020-06-01,134,3152.447761,6988,0.880631,35.139303
14,General Markets,2009-05-01,2020-06-01,134,12122.432836,30012,0.378743,109.460199
15,Healthcare,2009-08-01,2020-06-01,131,266.396947,779,0.093080,2.849873
16,Insurance,2010-11-01,2020-02-01,29,1.586207,5,0.252381,0.022989
17,Macroeconomics,2009-08-01,2020-06-01,131,263.954198,1021,0.169255,1.185751
18,Media,2009-12-01,2020-06-01,124,17.612903,65,0.376785,0.190860
19,Mining,2009-08-01,2020-05-01,34,2.294118,16,0.264520,-0.186275

## 80. Merge Peak Information

In [138]:
sector_temporal = (

    sector_temporal

    .merge(

        sector_peak[

            [

                "sector",

                "date",

                "news_count"

            ]

        ]

        .rename(

            columns={

                "date":"peak_month",

                "news_count":"peak_news"

            }

        ),

        on="sector",

        how="left"

    )

)

display(

    sector_temporal.head(20)

)

,sector,first_month,latest_month,active_months,average_news,max_news,average_growth,average_momentum,peak_month,peak_news
0,Artificial Intelligence,2010-01-01,2020-05-01,68,3.602941,22,0.500090,0.049020,2017-11-01,22
1,Automotive,2009-08-01,2020-06-01,131,27.190840,75,0.283053,0.264631,2020-03-01,75
2,Banking,2009-08-01,2020-06-01,131,62.274809,146,0.216331,0.279898,2015-06-01,146
3,Biotechnology,2009-08-01,2020-05-01,104,13.875000,99,1.518083,0.429487,2018-06-01,99
4,Cloud Computing,2010-03-01,2020-04-01,50,2.180000,10,0.680466,0.020000,2016-10-01,10
5,Commodities,2009-07-01,2020-06-01,132,1099.431818,2891,0.849205,7.121212,2019-08-01,2891
6,Consumer Goods,2009-12-01,2020-05-01,88,5.068182,31,1.049125,-0.003788,2013-02-01,31
7,Corporate,2009-07-01,2020-06-01,132,2314.765152,7331,0.778007,32.121212,2020-05-01,7331
8,Cryptocurrency,2009-02-01,2020-06-01,133,101.000000,570,0.261559,0.170426,2017-12-01,570
9,Cybersecurity,2009-08-01,2020-06-01,130,54.630769,233,0.239196,0.346154,2018-11-01,233
10,Electric Vehicles,2009-10-01,2020-06-01,106,11.481132,60,0.712834,0.163522,2020-02-01,60
11,Energy,2009-07-01,2020-06-01,132,312.454545,970,0.252319,1.459596,2019-09-01,970
12,FinTech,2009-10-01,2020-06-01,127,11.944882,48,0.577315,0.065617,2017-06-01,48
13,Financial Services,2009-05-01,2020-06-01,134,3152.447761,6988,0.880631,35.139303,2019-11-01,6988
14,General Markets,2009-05-01,2020-06-01,134,12122.432836,30012,0.378743,109.460199,2019-10-01,30012
15,Healthcare,2009-08-01,2020-06-01,131,266.396947,779,0.093080,2.849873,2018-08-01,779
16,Insurance,2010-11-01,2020-02-01,29,1.586207,5,0.252381,0.022989,2018-03-01,5
17,Macroeconomics,2009-08-01,2020-06-01,131,263.954198,1021,0.169255,1.185751,2019-06-01,1021
18,Media,2009-12-01,2020-06-01,124,17.612903,65,0.376785,0.190860,2016-11-01,65
19,Mining,2009-08-01,2020-05-01,34,2.294118,16,0.264520,-0.186275,2016-09-01,16

## 81. Assign Lifecycle Stage

In [139]:
def sector_lifecycle(row):

    if row["average_growth"] > 0.30:

        return "Emerging"

    elif row["average_growth"] > 0.10:

        return "Growing"

    elif row["average_growth"] > -0.10:

        return "Mature"

    else:

        return "Declining"


sector_temporal["lifecycle"] = (

    sector_temporal

    .apply(

        sector_lifecycle,

        axis=1

    )

)

display(

    sector_temporal[

        [

            "sector",

            "average_growth",

            "lifecycle"

        ]

    ]

)

                     sector  average_growth lifecycle
0   Artificial Intelligence        0.500090  Emerging
1                Automotive        0.283053   Growing
2                   Banking        0.216331   Growing
3             Biotechnology        1.518083  Emerging
4           Cloud Computing        0.680466  Emerging
5               Commodities        0.849205  Emerging
6            Consumer Goods        1.049125  Emerging
7                 Corporate        0.778007  Emerging
8            Cryptocurrency        0.261559   Growing
9             Cybersecurity        0.239196   Growing
10        Electric Vehicles        0.712834  Emerging
11                   Energy        0.252319   Growing
12                  FinTech        0.577315  Emerging
13       Financial Services        0.880631  Emerging
14          General Markets        0.378743  Emerging
15               Healthcare        0.093080    Mature
16                Insurance        0.252381   Growing
17           Macroeconomics        0.169255   Growing
18                    Media        0.376785  Emerging
19                   Mining        0.264520   Growing
20                    Other        0.805950  Emerging
21          Pharmaceuticals        0.376377  Emerging
22              Real Estate        1.248900  Emerging
23                   Retail        0.541295  Emerging
24           Semiconductors        0.443984  Emerging
25               Technology        0.416595  Emerging
26       Telecommunications        0.889023  Emerging
27           Transportation        0.125000   Growing

## 82. Trend Strength Score

In [140]:
sector_temporal["trend_strength"] = (

    sector_temporal["average_growth"].abs()

    *

    np.log1p(

        sector_temporal["average_news"]

    )

)

display(

    sector_temporal[

        [

            "sector",

            "trend_strength"

        ]

    ]

)

                     sector  trend_strength
0   Artificial Intelligence        0.763486
1                Automotive        0.945113
2                   Banking        0.897228
3             Biotechnology        4.098341
4           Cloud Computing        0.787219
5               Commodities        5.947370
6            Consumer Goods        1.891634
7                 Corporate        6.027607
8            Cryptocurrency        1.209703
9             Cybersecurity        0.961266
10        Electric Vehicles        1.799348
11                   Energy        1.450241
12                  FinTech        1.478332
13       Financial Services        7.094583
14          General Markets        3.561281
15               Healthcare        0.520199
16                Insurance        0.239810
17           Macroeconomics        0.944370
18                    Media        1.101666
19                   Mining        0.315345
20                    Other        2.296641
21          Pharmaceuticals        1.324313
22              Real Estate        1.875053
23                   Retail        1.887236
24           Semiconductors        1.492527
25               Technology        3.465592
26       Telecommunications        1.249382
27           Transportation        0.099813

## 83. Temporal Intelligence Score

In [141]:
sector_temporal["temporal_score"] = (

      sector_temporal["average_news"] * 0.35

    + sector_temporal["trend_strength"] * 0.30

    + sector_temporal["average_momentum"] * 15 * 0.20

    + sector_profile.set_index("sector")

        .loc[

            sector_temporal["sector"],

            "avg_confidence"

        ]

        .values

        *100

        *0.15

)

display(

    sector_temporal[

        [

            "sector",

            "temporal_score"

        ]

    ]

    .sort_values(

        "temporal_score",

        ascending=False

    )

)

                     sector  temporal_score
14          General Markets     4584.672532
25               Technology     1504.553209
13       Financial Services     1220.361825
7                 Corporate      917.695783
5               Commodities      415.962129
11                   Energy      122.279522
15               Healthcare      110.050436
17           Macroeconomics      104.326234
8            Cryptocurrency       44.959908
2                   Banking       30.153580
9             Cybersecurity       28.963234
23                   Retail       18.764197
21          Pharmaceuticals       18.066120
24           Semiconductors       16.432016
1                Automotive       16.364867
22              Real Estate       13.150193
3             Biotechnology       12.647499
18                    Media       12.430124
10        Electric Vehicles       10.881203
16                Insurance       10.331298
12                  FinTech        9.995248
0   Artificial Intelligence        9.610338
6            Consumer Goods        7.948230
26       Telecommunications        7.326536
4           Cloud Computing        6.742927
20                    Other        6.660067
27           Transportation        6.350651
19                   Mining        5.869106

## 84. Temporal Ranking

In [142]:
sector_temporal = (

    sector_temporal

    .sort_values(

        "temporal_score",

        ascending=False

    )

    .reset_index(drop=True)

)

sector_temporal["temporal_rank"] = (

    np.arange(

        1,

        len(sector_temporal)+1

    )

)

display(

    sector_temporal.head(20)

)

,sector,first_month,latest_month,active_months,average_news,max_news,average_growth,average_momentum,peak_month,peak_news,lifecycle,trend_strength,temporal_score,temporal_rank
0,General Markets,2009-05-01,2020-06-01,134,12122.432836,30012,0.378743,109.460199,2019-10-01,30012,Emerging,3.561281,4584.672532,1
1,Technology,2009-04-01,2020-06-01,135,4099.488889,8906,0.416595,20.091358,2017-01-01,8906,Emerging,3.465592,1504.553209,2
2,Financial Services,2009-05-01,2020-06-01,134,3152.447761,6988,0.880631,35.139303,2019-11-01,6988,Emerging,7.094583,1220.361825,3
3,Corporate,2009-07-01,2020-06-01,132,2314.765152,7331,0.778007,32.121212,2020-05-01,7331,Emerging,6.027607,917.695783,4
4,Commodities,2009-07-01,2020-06-01,132,1099.431818,2891,0.849205,7.121212,2019-08-01,2891,Emerging,5.947370,415.962129,5
5,Energy,2009-07-01,2020-06-01,132,312.454545,970,0.252319,1.459596,2019-09-01,970,Growing,1.450241,122.279522,6
6,Healthcare,2009-08-01,2020-06-01,131,266.396947,779,0.093080,2.849873,2018-08-01,779,Mature,0.520199,110.050436,7
7,Macroeconomics,2009-08-01,2020-06-01,131,263.954198,1021,0.169255,1.185751,2019-06-01,1021,Growing,0.944370,104.326234,8
8,Cryptocurrency,2009-02-01,2020-06-01,133,101.000000,570,0.261559,0.170426,2017-12-01,570,Growing,1.209703,44.959908,9
9,Banking,2009-08-01,2020-06-01,131,62.274809,146,0.216331,0.279898,2015-06-01,146,Growing,0.897228,30.153580,10
10,Cybersecurity,2009-08-01,2020-06-01,130,54.630769,233,0.239196,0.346154,2018-11-01,233,Growing,0.961266,28.963234,11
11,Retail,2009-11-01,2020-06-01,125,31.672000,126,0.541295,0.610667,2020-05-01,126,Emerging,1.887236,18.764197,12
12,Pharmaceuticals,2009-09-01,2020-06-01,129,32.736434,107,0.376377,0.219638,2018-11-01,107,Emerging,1.324313,18.066120,13
13,Semiconductors,2009-10-01,2020-06-01,129,27.837209,114,0.443984,0.201550,2019-01-01,114,Emerging,1.492527,16.432016,14
14,Automotive,2009-08-01,2020-06-01,131,27.190840,75,0.283053,0.264631,2020-03-01,75,Growing,0.945113,16.364867,15
15,Real Estate,2011-01-01,2020-05-01,41,3.487805,22,1.248900,-0.048780,2019-06-01,22,Emerging,1.875053,13.150193,16
16,Biotechnology,2009-08-01,2020-05-01,104,13.875000,99,1.518083,0.429487,2018-06-01,99,Emerging,4.098341,12.647499,17
17,Media,2009-12-01,2020-06-01,124,17.612903,65,0.376785,0.190860,2016-11-01,65,Emerging,1.101666,12.430124,18
18,Electric Vehicles,2009-10-01,2020-06-01,106,11.481132,60,0.712834,0.163522,2020-02-01,60,Emerging,1.799348,10.881203,19
19,Insurance,2010-11-01,2020-02-01,29,1.586207,5,0.252381,0.022989,2018-03-01,5,Growing,0.239810,10.331298,20

## 85. Seasonality Score

In [143]:
seasonality = (

    sector_timeline

    .groupby("sector")

    .agg(

        monthly_std=(

            "news_count",

            "std"

        ),

        monthly_mean=(

            "news_count",

            "mean"

        )

    )

    .reset_index()

)

seasonality["seasonality_score"] = (

    seasonality["monthly_std"]

    /

    seasonality["monthly_mean"]

)

display(

    seasonality.head()

)

                    sector  monthly_std  monthly_mean  seasonality_score
0  Artificial Intelligence     3.681903      3.602941           1.021916
1               Automotive    16.408776     27.190840           0.603467
2                  Banking    34.029863     62.274809           0.546447
3            Biotechnology    18.938679     13.875000           1.364950
4          Cloud Computing     2.115926      2.180000           0.970608

## 86. Merge Seasonality

In [144]:
sector_temporal = (

    sector_temporal

    .merge(

        seasonality[

            [

                "sector",

                "seasonality_score"

            ]

        ],

        on="sector",

        how="left"

    )

)

display(

    sector_temporal.head()

)

,sector,first_month,latest_month,active_months,average_news,max_news,average_growth,average_momentum,peak_month,peak_news,lifecycle,trend_strength,temporal_score,temporal_rank,seasonality_score
0,General Markets,2009-05-01,2020-06-01,134,12122.432836,30012,0.378743,109.460199,2019-10-01,30012,Emerging,3.561281,4584.672532,1,0.595443
1,Technology,2009-04-01,2020-06-01,135,4099.488889,8906,0.416595,20.091358,2017-01-01,8906,Emerging,3.465592,1504.553209,2,0.567278
2,Financial Services,2009-05-01,2020-06-01,134,3152.447761,6988,0.880631,35.139303,2019-11-01,6988,Emerging,7.094583,1220.361825,3,0.515658
3,Corporate,2009-07-01,2020-06-01,132,2314.765152,7331,0.778007,32.121212,2020-05-01,7331,Emerging,6.027607,917.695783,4,0.552466
4,Commodities,2009-07-01,2020-06-01,132,1099.431818,2891,0.849205,7.121212,2019-08-01,2891,Emerging,5.947370,415.962129,5,0.623124

## 87. Temporal Fingerprint

In [145]:
def temporal_fingerprint(row):

    tags = []

    if row["lifecycle"] == "Emerging":

        tags.append("Fast Growing")

    elif row["lifecycle"] == "Growing":

        tags.append("Growing")

    elif row["lifecycle"] == "Mature":

        tags.append("Mature")

    else:

        tags.append("Declining")

    if row["seasonality_score"] > 1:

        tags.append("Highly Seasonal")

    elif row["seasonality_score"] > 0.50:

        tags.append("Seasonal")

    else:

        tags.append("Consistent")

    if row["average_news"] > 1000:

        tags.append("High Activity")

    elif row["average_news"] > 300:

        tags.append("Medium Activity")

    else:

        tags.append("Low Activity")

    return ", ".join(tags)


sector_temporal["temporal_fingerprint"] = (

    sector_temporal

    .apply(

        temporal_fingerprint,

        axis=1

    )

)

display(

    sector_temporal[

        [

            "sector",

            "temporal_fingerprint"

        ]

    ]

)

                     sector                         temporal_fingerprint
0           General Markets        Fast Growing, Seasonal, High Activity
1                Technology        Fast Growing, Seasonal, High Activity
2        Financial Services        Fast Growing, Seasonal, High Activity
3                 Corporate        Fast Growing, Seasonal, High Activity
4               Commodities        Fast Growing, Seasonal, High Activity
5                    Energy           Growing, Seasonal, Medium Activity
6                Healthcare               Mature, Seasonal, Low Activity
7            Macroeconomics              Growing, Seasonal, Low Activity
8            Cryptocurrency              Growing, Seasonal, Low Activity
9                   Banking              Growing, Seasonal, Low Activity
10            Cybersecurity              Growing, Seasonal, Low Activity
11                   Retail         Fast Growing, Seasonal, Low Activity
12          Pharmaceuticals         Fast Growing, Seasonal, Low Activity
13           Semiconductors         Fast Growing, Seasonal, Low Activity
14               Automotive              Growing, Seasonal, Low Activity
15              Real Estate  Fast Growing, Highly Seasonal, Low Activity
16            Biotechnology  Fast Growing, Highly Seasonal, Low Activity
17                    Media         Fast Growing, Seasonal, Low Activity
18        Electric Vehicles  Fast Growing, Highly Seasonal, Low Activity
19                Insurance              Growing, Seasonal, Low Activity
20                  FinTech         Fast Growing, Seasonal, Low Activity
21  Artificial Intelligence  Fast Growing, Highly Seasonal, Low Activity
22           Consumer Goods  Fast Growing, Highly Seasonal, Low Activity
23       Telecommunications  Fast Growing, Highly Seasonal, Low Activity
24          Cloud Computing         Fast Growing, Seasonal, Low Activity
25                    Other  Fast Growing, Highly Seasonal, Low Activity
26           Transportation            Growing, Consistent, Low Activity
27                   Mining       Growing, Highly Seasonal, Low Activity

## 88. Temporal Knowledge Card

In [146]:
sector_temporal["temporal_card"] = (

    "Lifecycle: "

    + sector_temporal["lifecycle"]

    + " | Rank: "

    + sector_temporal["temporal_rank"].astype(str)

    + " | Peak: "

    + sector_temporal["peak_month"]

        .dt.strftime("%Y-%m")

    + " | Avg Monthly News: "

    + sector_temporal["average_news"]

        .round(1)

        .astype(str)

)

display(

    sector_temporal[

        [

            "sector",

            "temporal_card"

        ]

    ]

)

                     sector                                      temporal_card
0           General Markets  Lifecycle: Emerging | Rank: 1 | Peak: 2019-10 ...
1                Technology  Lifecycle: Emerging | Rank: 2 | Peak: 2017-01 ...
2        Financial Services  Lifecycle: Emerging | Rank: 3 | Peak: 2019-11 ...
3                 Corporate  Lifecycle: Emerging | Rank: 4 | Peak: 2020-05 ...
4               Commodities  Lifecycle: Emerging | Rank: 5 | Peak: 2019-08 ...
5                    Energy  Lifecycle: Growing | Rank: 6 | Peak: 2019-09 |...
6                Healthcare  Lifecycle: Mature | Rank: 7 | Peak: 2018-08 | ...
7            Macroeconomics  Lifecycle: Growing | Rank: 8 | Peak: 2019-06 |...
8            Cryptocurrency  Lifecycle: Growing | Rank: 9 | Peak: 2017-12 |...
9                   Banking  Lifecycle: Growing | Rank: 10 | Peak: 2015-06 ...
10            Cybersecurity  Lifecycle: Growing | Rank: 11 | Peak: 2018-11 ...
11                   Retail  Lifecycle: Emerging | Rank: 12 | Peak: 2020-05...
12          Pharmaceuticals  Lifecycle: Emerging | Rank: 13 | Peak: 2018-11...
13           Semiconductors  Lifecycle: Emerging | Rank: 14 | Peak: 2019-01...
14               Automotive  Lifecycle: Growing | Rank: 15 | Peak: 2020-03 ...
15              Real Estate  Lifecycle: Emerging | Rank: 16 | Peak: 2019-06...
16            Biotechnology  Lifecycle: Emerging | Rank: 17 | Peak: 2018-06...
17                    Media  Lifecycle: Emerging | Rank: 18 | Peak: 2016-11...
18        Electric Vehicles  Lifecycle: Emerging | Rank: 19 | Peak: 2020-02...
19                Insurance  Lifecycle: Growing | Rank: 20 | Peak: 2018-03 ...
20                  FinTech  Lifecycle: Emerging | Rank: 21 | Peak: 2017-06...
21  Artificial Intelligence  Lifecycle: Emerging | Rank: 22 | Peak: 2017-11...
22           Consumer Goods  Lifecycle: Emerging | Rank: 23 | Peak: 2013-02...
23       Telecommunications  Lifecycle: Emerging | Rank: 24 | Peak: 2014-09...
24          Cloud Computing  Lifecycle: Emerging | Rank: 25 | Peak: 2016-10...
25                    Other  Lifecycle: Emerging | Rank: 26 | Peak: 2012-08...
26           Transportation  Lifecycle: Growing | Rank: 27 | Peak: 2015-02 ...
27                   Mining  Lifecycle: Growing | Rank: 28 | Peak: 2016-09 ...

## 89. Merge with Sector Profile

In [147]:
sector_profile = (

    sector_profile

    .merge(

        sector_temporal[

            [

                "sector",

                "temporal_rank",

                "temporal_score",

                "lifecycle",

                "seasonality_score",

                "temporal_fingerprint",

                "temporal_card"

            ]

        ],

        on="sector",

        how="left"

    )

)

display(

    sector_profile.head()

)

,sector,total_news,companies_x,publishers,avg_confidence,first_news,last_news,Bearish,Bullish,Mixed,...,knowledge_card,community_display,rank_display,influence_display,temporal_rank,temporal_score,lifecycle,seasonality_score,temporal_fingerprint,temporal_card
0,General Markets,1624406,6551,769,0.824804,2009-05-27 00:00:00+00:00,2020-06-11 21:01:39+00:00,59204,132017,23679,...,Community: 0.0 | Rank: 2 | Influence: 0.371 | ...,0.0,2,0.371,1,4584.672532,Emerging,0.595443,"Fast Growing, Seasonal, High Activity",Lifecycle: Emerging | Rank: 1 | Peak: 2019-10 ...
1,Financial Services,422428,6118,433,0.630588,2009-05-29 00:00:00+00:00,2020-06-11 20:30:31+00:00,12546,187896,3196,...,Community: 0.0 | Rank: 1 | Influence: 0.405 | ...,0.0,1,0.405,3,1220.361825,Emerging,0.515658,"Fast Growing, Seasonal, High Activity",Lifecycle: Emerging | Rank: 3 | Peak: 2019-11 ...
2,Corporate,305549,5990,450,0.623737,2009-07-27 00:00:00+00:00,2020-06-11 13:20:52+00:00,1934,5628,146,...,Community: 0.0 | Rank: 4 | Influence: 0.286 | ...,0.0,4,0.286,4,917.695783,Emerging,0.552466,"Fast Growing, Seasonal, High Activity",Lifecycle: Emerging | Rank: 4 | Peak: 2020-05 ...
3,Technology,553431,6443,755,0.561223,2009-04-27 00:00:00+00:00,2020-06-11 19:25:36+00:00,231,5985,24,...,Community: 0.0 | Rank: 3 | Influence: 0.286 | ...,0.0,3,0.286,2,1504.553209,Emerging,0.567278,"Fast Growing, Seasonal, High Activity",Lifecycle: Emerging | Rank: 2 | Peak: 2017-01 ...
4,Commodities,145125,4733,426,0.534210,2009-07-27 00:00:00+00:00,2020-06-11 20:51:33+00:00,5571,7447,903,...,Community: Independent | Rank: Not Connected |...,Independent,Not Connected,0,5,415.962129,Emerging,0.623124,"Fast Growing, Seasonal, High Activity",Lifecycle: Emerging | Rank: 5 | Peak: 2019-08 ...

## 90. Save Outputs

In [150]:
sector_temporal.to_parquet(

    os.path.join(

        SECTOR_PATH,

        "sector_temporal.parquet"

    ),

    index=False

)

# Ensure the 'community' column is consistently string type before saving
sector_profile["community"] = sector_profile["community"].astype(str)

sector_profile.to_parquet(

    os.path.join(

        SECTOR_PATH,

        "sector_profile.parquet"

    ),

    index=False

)

print("sector_temporal.parquet saved")

print("sector_profile.parquet saved")

sector_temporal.parquet saved
sector_profile.parquet saved

# 8. Sector Recommendation & Opportunity Engine

## 91. Build Similar Sector Dictionary

In [151]:
sector_recommendations = (

    sector_relationships

    .sort_values(

        [

            "sector_1",

            "similarity"

        ],

        ascending=[

            True,

            False

        ]

    )

)

sector_recommendations = (

    sector_recommendations

    .groupby("sector_1")

    .agg(

        similar_sectors=(

            "sector_2",

            list

        ),

        similarity_scores=(

            "similarity",

            list

        )

    )

    .reset_index()

)

display(

    sector_recommendations.head()

)

,sector_1,similar_sectors,similarity_scores
0,Biotechnology,[Healthcare],[0.5892]
1,Corporate,"[General Markets, Financial Services, Technology]","[0.8343, 0.8127, 0.8035]"
2,Financial Services,"[General Markets, Technology, Other]","[0.8773, 0.7781, 0.5531]"
3,General Markets,"[Technology, Other]","[0.891, 0.5783]"
4,Healthcare,[Pharmaceuticals],[0.7197]

## 92. Number of Similar Sectors

In [152]:
sector_recommendations["recommendation_count"] = (

    sector_recommendations["similar_sectors"]

    .apply(len)

)

display(

    sector_recommendations[
        [

            "sector_1",

            "recommendation_count"

        ]

    ]

)

             sector_1  recommendation_count
0       Biotechnology                     1
1           Corporate                     3
2  Financial Services                     3
3     General Markets                     2
4          Healthcare                     1

## 93. Merge Intelligence Score

In [153]:
sector_recommendations = (

    sector_recommendations

    .merge(

        sector_profile[

            [

                "sector",

                "sector_intelligence_score",

                "sector_risk_level",

                "lifecycle"

            ]

        ],

        left_on="sector_1",

        right_on="sector",

        how="left"

    )

)

sector_recommendations = (

    sector_recommendations

    .drop(

        columns="sector"

    )

)

display(

    sector_recommendations.head()

)

,sector_1,similar_sectors,similarity_scores,recommendation_count,sector_intelligence_score,sector_risk_level,lifecycle
0,Biotechnology,[Healthcare],[0.5892],1,48.478380,Low,Emerging
1,Corporate,"[General Markets, Financial Services, Technology]","[0.8343, 0.8127, 0.8035]",3,70.512834,Low,Emerging
2,Financial Services,"[General Markets, Technology, Other]","[0.8773, 0.7781, 0.5531]",3,71.597915,Low,Emerging
3,General Markets,"[Technology, Other]","[0.891, 0.5783]",2,85.754461,Low,Emerging
4,Healthcare,[Pharmaceuticals],[0.7197],1,61.331079,Low,Mature

## 94. Opportunity Score

In [154]:
risk_bonus = {

    "Very Low": 15,

    "Low": 10,

    "Medium": 5,

    "High": 0,

    "Very High": -5

}

sector_recommendations["risk_bonus"] = (

    sector_recommendations["sector_risk_level"]

    .map(risk_bonus)

    .fillna(0)

)

growth_bonus = {

    "Emerging":20,

    "Growing":15,

    "Mature":8,

    "Declining":0

}

sector_recommendations["growth_bonus"] = (

    sector_recommendations["lifecycle"]

    .map(growth_bonus)

)

sector_recommendations["opportunity_score"] = (

      sector_recommendations["sector_intelligence_score"]

    + sector_recommendations["risk_bonus"]

    + sector_recommendations["growth_bonus"]

)

display(

    sector_recommendations

    .sort_values(

        "opportunity_score",

        ascending=False

    )

)

,sector_1,similar_sectors,similarity_scores,recommendation_count,sector_intelligence_score,sector_risk_level,lifecycle,risk_bonus,growth_bonus,opportunity_score
3,General Markets,"[Technology, Other]","[0.891, 0.5783]",2,85.754461,Low,Emerging,10,20,115.754461
2,Financial Services,"[General Markets, Technology, Other]","[0.8773, 0.7781, 0.5531]",3,71.597915,Low,Emerging,10,20,101.597915
1,Corporate,"[General Markets, Financial Services, Technology]","[0.8343, 0.8127, 0.8035]",3,70.512834,Low,Emerging,10,20,100.512834
4,Healthcare,[Pharmaceuticals],[0.7197],1,61.331079,Low,Mature,10,8,79.331079
0,Biotechnology,[Healthcare],[0.5892],1,48.478380,Low,Emerging,10,20,78.478380

## 95. Opportunity Rank

In [155]:
sector_recommendations = (

    sector_recommendations

    .sort_values(

        "opportunity_score",

        ascending=False

    )

    .reset_index(drop=True)

)

sector_recommendations["opportunity_rank"] = (

    np.arange(

        1,

        len(sector_recommendations)+1

    )

)

display(

    sector_recommendations.head(20)

)

,sector_1,similar_sectors,similarity_scores,recommendation_count,sector_intelligence_score,sector_risk_level,lifecycle,risk_bonus,growth_bonus,opportunity_score,opportunity_rank
0,General Markets,"[Technology, Other]","[0.891, 0.5783]",2,85.754461,Low,Emerging,10,20,115.754461,1
1,Financial Services,"[General Markets, Technology, Other]","[0.8773, 0.7781, 0.5531]",3,71.597915,Low,Emerging,10,20,101.597915,2
2,Corporate,"[General Markets, Financial Services, Technology]","[0.8343, 0.8127, 0.8035]",3,70.512834,Low,Emerging,10,20,100.512834,3
3,Healthcare,[Pharmaceuticals],[0.7197],1,61.331079,Low,Mature,10,8,79.331079,4
4,Biotechnology,[Healthcare],[0.5892],1,48.478380,Low,Emerging,10,20,78.478380,5

## 96. Diversification Score

In [156]:
sector_recommendations["diversification_score"] = (

    sector_recommendations["recommendation_count"]

    *

    sector_recommendations["similarity_scores"]

    .apply(np.mean)

)

display(

    sector_recommendations[
        [

            "sector_1",

            "diversification_score"

        ]

    ]
)

             sector_1  diversification_score
0     General Markets                 1.4693
1  Financial Services                 2.2085
2           Corporate                 2.4505
3          Healthcare                 0.7197
4       Biotechnology                 0.5892

## 97. Recommendation Category

In [157]:
def recommendation_category(score):

    if score >= 100:

        return "Strong Buy"

    elif score >= 75:

        return "Buy"

    elif score >= 50:

        return "Watch"

    else:

        return "Speculative"

sector_recommendations["recommendation"] = (

    sector_recommendations["opportunity_score"]

    .apply(

        recommendation_category

    )

)

display(

    sector_recommendations[
        [

            "sector_1",

            "recommendation",

            "opportunity_score"

        ]

    ]

)

             sector_1 recommendation  opportunity_score
0     General Markets     Strong Buy         115.754461
1  Financial Services     Strong Buy         101.597915
2           Corporate     Strong Buy         100.512834
3          Healthcare            Buy          79.331079
4       Biotechnology            Buy          78.478380

## 98. Recommendation Fingerprint

In [158]:
def recommendation_fingerprint(row):

    tags = []

    tags.append(row["recommendation"])

    tags.append(row["lifecycle"])

    tags.append(row["sector_risk_level"] + " Risk")

    if row["recommendation_count"] >= 5:

        tags.append("Highly Connected")

    elif row["recommendation_count"] >= 3:

        tags.append("Well Connected")

    else:

        tags.append("Niche")

    return ", ".join(tags)

sector_recommendations["recommendation_fingerprint"] = (

    sector_recommendations

    .apply(

        recommendation_fingerprint,

        axis=1

    )

)

display(

    sector_recommendations[
        [

            "sector_1",

            "recommendation_fingerprint"

        ]

    ]
)

             sector_1                      recommendation_fingerprint
0     General Markets           Strong Buy, Emerging, Low Risk, Niche
1  Financial Services  Strong Buy, Emerging, Low Risk, Well Connected
2           Corporate  Strong Buy, Emerging, Low Risk, Well Connected
3          Healthcare                    Buy, Mature, Low Risk, Niche
4       Biotechnology                  Buy, Emerging, Low Risk, Niche

## 99. Recommendation Card

In [159]:
sector_recommendations["recommendation_card"] = (

    "Rank: "

    + sector_recommendations["opportunity_rank"]

    .astype(str)

    + " | "

    + sector_recommendations["recommendation"]

    + " | "

    + "Opportunity Score: "

    + sector_recommendations["opportunity_score"]

    .round(2)

    .astype(str)

    + " | "

    + "Top Similar: "

    + sector_recommendations["similar_sectors"]

    .apply(

        lambda x: ", ".join(x[:3])

    )

)

display(

    sector_recommendations[
        [

            "sector_1",

            "recommendation_card"

        ]

    ]
)

             sector_1                                recommendation_card
0     General Markets  Rank: 1 | Strong Buy | Opportunity Score: 115....
1  Financial Services  Rank: 2 | Strong Buy | Opportunity Score: 101....
2           Corporate  Rank: 3 | Strong Buy | Opportunity Score: 100....
3          Healthcare  Rank: 4 | Buy | Opportunity Score: 79.33 | Top...
4       Biotechnology  Rank: 5 | Buy | Opportunity Score: 78.48 | Top...

## 100. Save Recommendation Dataset

In [161]:
sector_recommendations.to_parquet(

    os.path.join(

        SECTOR_PATH,

        "sector_recommendations.parquet"

    ),

    index=False

)

print("sector_recommendations.parquet saved")

sector_recommendations.parquet saved

## 101. Top Similar Sector

In [162]:
sector_recommendations["top_similar_sector"] = (

    sector_recommendations["similar_sectors"]

    .apply(

        lambda x: x[0] if len(x) > 0 else "None"

    )

)

display(

    sector_recommendations[

        [

            "sector_1",

            "top_similar_sector"

        ]

    ].head(20)

)

             sector_1 top_similar_sector
0     General Markets         Technology
1  Financial Services    General Markets
2           Corporate    General Markets
3          Healthcare    Pharmaceuticals
4       Biotechnology         Healthcare

## 102. Average Similarity

In [163]:
sector_recommendations["average_similarity"] = (

    sector_recommendations["similarity_scores"]

    .apply(

        lambda x: round(np.mean(x),4)

        if len(x)>0

        else 0

    )

)

display(

    sector_recommendations[

        [

            "sector_1",

            "average_similarity"

        ]

    ]

)

             sector_1  average_similarity
0     General Markets              0.7346
1  Financial Services              0.7362
2           Corporate              0.8168
3          Healthcare              0.7197
4       Biotechnology              0.5892

### 103. Recommendation Confidence

In [164]:
sector_recommendations["recommendation_confidence"] = (

      sector_recommendations["average_similarity"] * 50

    + sector_recommendations["sector_intelligence_score"] * 0.50

)

sector_recommendations["recommendation_confidence"] = (

    sector_recommendations["recommendation_confidence"]

    .round(2)

)

display(

    sector_recommendations[

        [

            "sector_1",

            "recommendation_confidence"

        ]

    ]

)

             sector_1  recommendation_confidence
0     General Markets                      79.61
1  Financial Services                      72.61
2           Corporate                      76.10
3          Healthcare                      66.65
4       Biotechnology                      53.70

## 104. Confidence Category

In [165]:
def confidence_category(score):

    if score >= 80:

        return "Very High"

    elif score >= 65:

        return "High"

    elif score >= 50:

        return "Medium"

    else:

        return "Low"


sector_recommendations["confidence_level"] = (

    sector_recommendations["recommendation_confidence"]

    .apply(

        confidence_category

    )

)

display(

    sector_recommendations[

        [

            "sector_1",

            "recommendation_confidence",

            "confidence_level"

        ]

    ]

)

             sector_1  recommendation_confidence confidence_level
0     General Markets                      79.61             High
1  Financial Services                      72.61             High
2           Corporate                      76.10             High
3          Healthcare                      66.65             High
4       Biotechnology                      53.70           Medium

## 105. Diversification Category

In [166]:
def diversification_level(count):

    if count >= 6:

        return "Highly Diversified"

    elif count >= 4:

        return "Diversified"

    elif count >= 2:

        return "Moderately Diversified"

    else:

        return "Focused"


sector_recommendations["diversification_level"] = (

    sector_recommendations["recommendation_count"]

    .apply(

        diversification_level

    )

)

display(

    sector_recommendations[

        [

            "sector_1",

            "recommendation_count",

            "diversification_level"

        ]

    ]

)

             sector_1  recommendation_count   diversification_level
0     General Markets                     2  Moderately Diversified
1  Financial Services                     3  Moderately Diversified
2           Corporate                     3  Moderately Diversified
3          Healthcare                     1                 Focused
4       Biotechnology                     1                 Focused

## 106. Recommendation Explanation

In [167]:
sector_recommendations["recommendation_summary"] = (

    "Recommendation: "

    + sector_recommendations["recommendation"]

    + " | "

    + "Confidence: "

    + sector_recommendations["confidence_level"]

    + " | "

    + "Diversification: "

    + sector_recommendations["diversification_level"]

)

display(

    sector_recommendations[

        [

            "sector_1",

            "recommendation_summary"

        ]

    ].head(20)

)

             sector_1                             recommendation_summary
0     General Markets  Recommendation: Strong Buy | Confidence: High ...
1  Financial Services  Recommendation: Strong Buy | Confidence: High ...
2           Corporate  Recommendation: Strong Buy | Confidence: High ...
3          Healthcare  Recommendation: Buy | Confidence: High | Diver...
4       Biotechnology  Recommendation: Buy | Confidence: Medium | Div...

## 107. Investment Theme

In [168]:
def investment_theme(row):

    if (

        row["recommendation"] == "Strong Buy"

        and

        row["sector_risk_level"] == "Low"

    ):

        return "Long Term Compounder"

    elif row["recommendation"] == "Buy":

        return "Growth Opportunity"

    elif row["recommendation"] == "Watch":

        return "Monitor"

    else:

        return "Speculative"


sector_recommendations["investment_theme"] = (

    sector_recommendations

    .apply(

        investment_theme,

        axis=1

    )

)

display(

    sector_recommendations[

        [

            "sector_1",

            "investment_theme"

        ]

    ]

)

             sector_1      investment_theme
0     General Markets  Long Term Compounder
1  Financial Services  Long Term Compounder
2           Corporate  Long Term Compounder
3          Healthcare    Growth Opportunity
4       Biotechnology    Growth Opportunity

## 108. Recommendation Strength

In [169]:
sector_recommendations["recommendation_strength"] = (

      sector_recommendations["opportunity_score"] * 0.60

    + sector_recommendations["recommendation_confidence"] * 0.40

)

sector_recommendations["recommendation_strength"] = (

    sector_recommendations["recommendation_strength"]

    .round(2)

)

display(

    sector_recommendations[

        [

            "sector_1",

            "recommendation_strength"

        ]

    ]

)

             sector_1  recommendation_strength
0     General Markets                   101.30
1  Financial Services                    90.00
2           Corporate                    90.75
3          Healthcare                    74.26
4       Biotechnology                    68.57

## 109. Final Recommendation Rank

In [170]:
sector_recommendations = (

    sector_recommendations

    .sort_values(

        "recommendation_strength",

        ascending=False

    )

    .reset_index(drop=True)

)

sector_recommendations["final_rank"] = (

    np.arange(

        1,

        len(sector_recommendations)+1

    )

)

display(

    sector_recommendations.head(20)

)

,sector_1,similar_sectors,similarity_scores,recommendation_count,sector_intelligence_score,sector_risk_level,lifecycle,risk_bonus,growth_bonus,opportunity_score,...,recommendation_card,top_similar_sector,average_similarity,recommendation_confidence,confidence_level,diversification_level,recommendation_summary,investment_theme,recommendation_strength,final_rank
0,General Markets,"[Technology, Other]","[0.891, 0.5783]",2,85.754461,Low,Emerging,10,20,115.754461,...,Rank: 1 | Strong Buy | Opportunity Score: 115....,Technology,0.7346,79.61,High,Moderately Diversified,Recommendation: Strong Buy | Confidence: High ...,Long Term Compounder,101.30,1
1,Corporate,"[General Markets, Financial Services, Technology]","[0.8343, 0.8127, 0.8035]",3,70.512834,Low,Emerging,10,20,100.512834,...,Rank: 3 | Strong Buy | Opportunity Score: 100....,General Markets,0.8168,76.10,High,Moderately Diversified,Recommendation: Strong Buy | Confidence: High ...,Long Term Compounder,90.75,2
2,Financial Services,"[General Markets, Technology, Other]","[0.8773, 0.7781, 0.5531]",3,71.597915,Low,Emerging,10,20,101.597915,...,Rank: 2 | Strong Buy | Opportunity Score: 101....,General Markets,0.7362,72.61,High,Moderately Diversified,Recommendation: Strong Buy | Confidence: High ...,Long Term Compounder,90.00,3
3,Healthcare,[Pharmaceuticals],[0.7197],1,61.331079,Low,Mature,10,8,79.331079,...,Rank: 4 | Buy | Opportunity Score: 79.33 | Top...,Pharmaceuticals,0.7197,66.65,High,Focused,Recommendation: Buy | Confidence: High | Diver...,Growth Opportunity,74.26,4
4,Biotechnology,[Healthcare],[0.5892],1,48.478380,Low,Emerging,10,20,78.478380,...,Rank: 5 | Buy | Opportunity Score: 78.48 | Top...,Healthcare,0.5892,53.70,Medium,Focused,Recommendation: Buy | Confidence: Medium | Div...,Growth Opportunity,68.57,5

## 110. Final Recommendation Master Table

In [184]:
recommendation_master = (

    sector_recommendations[

        [

            "final_rank",

            "sector_1",

            "recommendation",

            "recommendation_strength",

            "recommendation_confidence",

            "opportunity_score",

            "sector_risk_level",

            "confidence_level",

            "investment_theme",

            "top_similar_sector",

            "recommendation_fingerprint",

            "recommendation_card"

        ]

    ]

    .rename(

        columns={

            "sector_1":"sector"

        }

    )

)

display(

    recommendation_master.head(20)

)

,final_rank,sector,recommendation,recommendation_strength,recommendation_confidence,opportunity_score,sector_risk_level,confidence_level,investment_theme,top_similar_sector,recommendation_fingerprint,recommendation_card
0,1,General Markets,Strong Buy,101.30,79.61,115.754461,Low,High,Long Term Compounder,Technology,"Strong Buy, Emerging, Low Risk, Niche",Rank: 1 | Strong Buy | Opportunity Score: 115....
1,2,Corporate,Strong Buy,90.75,76.10,100.512834,Low,High,Long Term Compounder,General Markets,"Strong Buy, Emerging, Low Risk, Well Connected",Rank: 3 | Strong Buy | Opportunity Score: 100....
2,3,Financial Services,Strong Buy,90.00,72.61,101.597915,Low,High,Long Term Compounder,General Markets,"Strong Buy, Emerging, Low Risk, Well Connected",Rank: 2 | Strong Buy | Opportunity Score: 101....
3,4,Healthcare,Buy,74.26,66.65,79.331079,Low,High,Growth Opportunity,Pharmaceuticals,"Buy, Mature, Low Risk, Niche",Rank: 4 | Buy | Opportunity Score: 79.33 | Top...
4,5,Biotechnology,Buy,68.57,53.70,78.478380,Low,Medium,Growth Opportunity,Healthcare,"Buy, Emerging, Low Risk, Niche",Rank: 5 | Buy | Opportunity Score: 78.48 | Top...

In [185]:
all_sectors = sector_profile[["sector"]].copy()

recommendation_master = (

    all_sectors

    .merge(

        recommendation_master,

        on="sector",

        how="left"

    )

)

In [186]:
recommendation_master["recommendation"] = (

    recommendation_master["recommendation"]

    .fillna("Watch")

)

recommendation_master["recommendation_strength"] = (

    recommendation_master["recommendation_strength"]

    .fillna(

        recommendation_master["sector"]

        .map(

            sector_profile.set_index("sector")[

                "sector_intelligence_score"

            ]

        )

    )

)

recommendation_master["recommendation_confidence"] = (

    recommendation_master["recommendation_confidence"]

    .fillna(35)

)

recommendation_master["opportunity_score"] = (

    recommendation_master["opportunity_score"]

    .fillna(

        recommendation_master["recommendation_strength"]

    )

)

recommendation_master["sector_risk_level"] = (

    recommendation_master["sector_risk_level"]

    .fillna(

        recommendation_master["sector"]

        .map(

            sector_profile.set_index("sector")[

                "sector_risk_level"

            ]

        )

    )

)

recommendation_master["confidence_level"] = (

    recommendation_master["confidence_level"]

    .fillna("Low")

)

recommendation_master["investment_theme"] = (

    recommendation_master["investment_theme"]

    .fillna("Monitor")

)

recommendation_master["top_similar_sector"] = (

    recommendation_master["top_similar_sector"]

    .fillna("None")

)

recommendation_master["recommendation_fingerprint"] = (

    recommendation_master["recommendation_fingerprint"]

    .fillna(

        "Watch, Independent Sector"

    )

)

recommendation_master["recommendation_card"] = (

    recommendation_master["recommendation_card"]

    .fillna(

        "Independent sector with no strong similarity links."

    )

)

In [187]:
recommendation_master = (

    recommendation_master

    .sort_values(

        "recommendation_strength",

        ascending=False

    )

    .reset_index(drop=True)

)

recommendation_master["final_rank"] = (

    np.arange(

        1,

        len(recommendation_master)+1

    )

)

## 111. Recommendation Statistics

In [188]:
recommendation_summary = (

    recommendation_master

    .groupby("recommendation")

    .agg(

        sectors=("sector","count"),

        avg_strength=("recommendation_strength","mean"),

        avg_confidence=("recommendation_confidence","mean")

    )

    .reset_index()

)

display(recommendation_summary)

  recommendation  sectors  avg_strength  avg_confidence
0            Buy        2     71.415000       60.175000
1     Strong Buy        3     94.016667       76.106667
2          Watch       23     52.356101       35.000000

## 112. Investment Theme Summary

In [189]:
investment_summary = (

    recommendation_master

    .groupby("investment_theme")

    .agg(

        sectors=("sector","count"),

        average_strength=("recommendation_strength","mean")

    )

    .reset_index()

)

display(investment_summary)

       investment_theme  sectors  average_strength
0    Growth Opportunity        2         71.415000
1  Long Term Compounder        3         94.016667
2               Monitor       23         52.356101

## 113. Top Recommendation Dashboard

In [190]:
top_recommendations = (

    recommendation_master

    .sort_values(

        "recommendation_strength",

        ascending=False

    )

    .head(10)

)

display(top_recommendations)

,sector,final_rank,recommendation,recommendation_strength,recommendation_confidence,opportunity_score,sector_risk_level,confidence_level,investment_theme,top_similar_sector,recommendation_fingerprint,recommendation_card
0,General Markets,1,Strong Buy,101.300000,79.61,115.754461,Low,High,Long Term Compounder,Technology,"Strong Buy, Emerging, Low Risk, Niche",Rank: 1 | Strong Buy | Opportunity Score: 115....
1,Corporate,2,Strong Buy,90.750000,76.10,100.512834,Low,High,Long Term Compounder,General Markets,"Strong Buy, Emerging, Low Risk, Well Connected",Rank: 3 | Strong Buy | Opportunity Score: 100....
2,Financial Services,3,Strong Buy,90.000000,72.61,101.597915,Low,High,Long Term Compounder,General Markets,"Strong Buy, Emerging, Low Risk, Well Connected",Rank: 2 | Strong Buy | Opportunity Score: 101....
3,Healthcare,4,Buy,74.260000,66.65,79.331079,Low,High,Growth Opportunity,Pharmaceuticals,"Buy, Mature, Low Risk, Niche",Rank: 4 | Buy | Opportunity Score: 79.33 | Top...
4,Biotechnology,5,Buy,68.570000,53.70,78.478380,Low,Medium,Growth Opportunity,Healthcare,"Buy, Emerging, Low Risk, Niche",Rank: 5 | Buy | Opportunity Score: 78.48 | Top...
5,Technology,6,Watch,68.178981,35.00,68.178981,Low,Low,Monitor,None,"Watch, Independent Sector",Independent sector with no strong similarity l...
6,Commodities,7,Watch,63.356337,35.00,63.356337,Low,Low,Monitor,None,"Watch, Independent Sector",Independent sector with no strong similarity l...
7,Macroeconomics,8,Watch,61.066999,35.00,61.066999,Low,Low,Monitor,None,"Watch, Independent Sector",Independent sector with no strong similarity l...
8,Energy,9,Watch,60.588049,35.00,60.588049,Low,Low,Monitor,None,"Watch, Independent Sector",Independent sector with no strong similarity l...
9,Cryptocurrency,10,Watch,60.472661,35.00,60.472661,Low,Low,Monitor,None,"Watch, Independent Sector",Independent sector with no strong similarity l...

## 114. Save Recommendation Master

In [191]:
recommendation_master.to_parquet(

    os.path.join(

        SECTOR_PATH,

        "sector_recommendations.parquet"

    ),

    index=False

)

## 115. Save Summary Tables

In [192]:
recommendation_summary.to_parquet(

    os.path.join(

        SECTOR_PATH,

        "recommendation_summary.parquet"

    ),

    index=False

)

investment_summary.to_parquet(

    os.path.join(

        SECTOR_PATH,

        "investment_theme_summary.parquet"

    ),

    index=False

)

## 116. Report

In [193]:
section8_summary = pd.DataFrame({

    "Metric":[

        "Total Sectors",

        "Strong Buy",

        "Buy",

        "Watch",

        "Avoid",

        "Average Recommendation Strength",

        "Highest Recommendation Strength"

    ],

    "Value":[

        len(recommendation_master),

        (recommendation_master["recommendation"]=="Strong Buy").sum(),

        (recommendation_master["recommendation"]=="Buy").sum(),

        (recommendation_master["recommendation"]=="Watch").sum(),

        (recommendation_master["recommendation"]=="Avoid").sum(),

        round(

            recommendation_master["recommendation_strength"].mean(),

            2

        ),

        round(

            recommendation_master["recommendation_strength"].max(),

            2

        )

    ]

})

display(section8_summary)

                            Metric   Value
0                    Total Sectors   28.00
1                       Strong Buy    3.00
2                              Buy    2.00
3                            Watch   23.00
4                            Avoid    0.00
5  Average Recommendation Strength   58.18
6  Highest Recommendation Strength  101.30

# 9. Sector Search Engine & Knowledge Retrieval System

## 117. Build Search Corpus

In [194]:
sector_search = (

    sector_profile[

        [

            "sector",

            "sector_rank",

            "sector_intelligence_score",

            "sector_risk_level",

            "company_strength",

            "market_stability_category",

            "lifecycle",

            "temporal_fingerprint",

            "sector_risk_fingerprint",

            "knowledge_card",

            "temporal_card"

        ]

    ]

    .copy()

)

display(sector_search.head())

,sector,sector_rank,sector_intelligence_score,sector_risk_level,company_strength,market_stability_category,lifecycle,temporal_fingerprint,sector_risk_fingerprint,knowledge_card,temporal_card
0,General Markets,1,85.754461,Low,Strong,Stable,Emerging,"Fast Growing, Seasonal, High Activity","Low Risk, Balanced Market, Highly Diversified,...",Community: 0.0 | Rank: 2 | Influence: 0.371 | ...,Lifecycle: Emerging | Rank: 1 | Peak: 2019-10 ...
1,Financial Services,2,71.597915,Low,Strong,Stable,Emerging,"Fast Growing, Seasonal, High Activity","Low Risk, Balanced Market, High Coverage",Community: 0.0 | Rank: 1 | Influence: 0.405 | ...,Lifecycle: Emerging | Rank: 3 | Peak: 2019-11 ...
2,Corporate,3,70.512834,Low,Strong,Very Stable,Emerging,"Fast Growing, Seasonal, High Activity","Low Risk, Stable Market, High Coverage",Community: 0.0 | Rank: 4 | Influence: 0.286 | ...,Lifecycle: Emerging | Rank: 4 | Peak: 2020-05 ...
3,Technology,4,68.178981,Low,Average,Very Stable,Emerging,"Fast Growing, Seasonal, High Activity","Low Risk, Stable Market, High Coverage",Community: 0.0 | Rank: 3 | Influence: 0.286 | ...,Lifecycle: Emerging | Rank: 2 | Peak: 2017-01 ...
4,Commodities,5,63.356337,Low,Average,Stable,Emerging,"Fast Growing, Seasonal, High Activity","Low Risk, Balanced Market, High Coverage",Community: Independent | Rank: Not Connected |...,Lifecycle: Emerging | Rank: 5 | Peak: 2019-08 ...

## 118. Create Search Text

In [195]:
sector_search["search_text"] = (

      sector_search["sector"].astype(str)

    + " "

    + sector_search["sector_risk_level"].astype(str)

    + " "

    + sector_search["company_strength"].astype(str)

    + " "

    + sector_search["market_stability_category"].astype(str)

    + " "

    + sector_search["lifecycle"].astype(str)

    + " "

    + sector_search["temporal_fingerprint"].astype(str)

    + " "

    + sector_search["sector_risk_fingerprint"].astype(str)

)

display(

    sector_search[

        [

            "sector",

            "search_text"

        ]

    ].head()

)

               sector                                        search_text
0     General Markets  General Markets Low Strong Stable Emerging Fas...
1  Financial Services  Financial Services Low Strong Stable Emerging ...
2           Corporate  Corporate Low Strong Very Stable Emerging Fast...
3          Technology  Technology Low Average Very Stable Emerging Fa...
4         Commodities  Commodities Low Average Stable Emerging Fast G...

## 119. Add Recommendation Information

In [196]:
sector_search = sector_search.merge(

    recommendation_master[

        [

            "sector",

            "recommendation",

            "recommendation_strength",

            "investment_theme",

            "top_similar_sector"

        ]

    ],

    on="sector",

    how="left"

)

display(sector_search.head())

,sector,sector_rank,sector_intelligence_score,sector_risk_level,company_strength,market_stability_category,lifecycle,temporal_fingerprint,sector_risk_fingerprint,knowledge_card,temporal_card,search_text,recommendation,recommendation_strength,investment_theme,top_similar_sector
0,General Markets,1,85.754461,Low,Strong,Stable,Emerging,"Fast Growing, Seasonal, High Activity","Low Risk, Balanced Market, Highly Diversified,...",Community: 0.0 | Rank: 2 | Influence: 0.371 | ...,Lifecycle: Emerging | Rank: 1 | Peak: 2019-10 ...,General Markets Low Strong Stable Emerging Fas...,Strong Buy,101.300000,Long Term Compounder,Technology
1,Financial Services,2,71.597915,Low,Strong,Stable,Emerging,"Fast Growing, Seasonal, High Activity","Low Risk, Balanced Market, High Coverage",Community: 0.0 | Rank: 1 | Influence: 0.405 | ...,Lifecycle: Emerging | Rank: 3 | Peak: 2019-11 ...,Financial Services Low Strong Stable Emerging ...,Strong Buy,90.000000,Long Term Compounder,General Markets
2,Corporate,3,70.512834,Low,Strong,Very Stable,Emerging,"Fast Growing, Seasonal, High Activity","Low Risk, Stable Market, High Coverage",Community: 0.0 | Rank: 4 | Influence: 0.286 | ...,Lifecycle: Emerging | Rank: 4 | Peak: 2020-05 ...,Corporate Low Strong Very Stable Emerging Fast...,Strong Buy,90.750000,Long Term Compounder,General Markets
3,Technology,4,68.178981,Low,Average,Very Stable,Emerging,"Fast Growing, Seasonal, High Activity","Low Risk, Stable Market, High Coverage",Community: 0.0 | Rank: 3 | Influence: 0.286 | ...,Lifecycle: Emerging | Rank: 2 | Peak: 2017-01 ...,Technology Low Average Very Stable Emerging Fa...,Watch,68.178981,Monitor,None
4,Commodities,5,63.356337,Low,Average,Stable,Emerging,"Fast Growing, Seasonal, High Activity","Low Risk, Balanced Market, High Coverage",Community: Independent | Rank: Not Connected |...,Lifecycle: Emerging | Rank: 5 | Peak: 2019-08 ...,Commodities Low Average Stable Emerging Fast G...,Watch,63.356337,Monitor,None

## 120. Add Network Information

In [197]:
sector_search = sector_search.merge(

    sector_network_metrics[

        [

            "sector",

            "network_rank",

            "network_influence"

        ]

    ],

    on="sector",

    how="left"

)

display(sector_search.head())

,sector,sector_rank,sector_intelligence_score,sector_risk_level,company_strength,market_stability_category,lifecycle,temporal_fingerprint,sector_risk_fingerprint,knowledge_card,temporal_card,search_text,recommendation,recommendation_strength,investment_theme,top_similar_sector,network_rank,network_influence
0,General Markets,1,85.754461,Low,Strong,Stable,Emerging,"Fast Growing, Seasonal, High Activity","Low Risk, Balanced Market, Highly Diversified,...",Community: 0.0 | Rank: 2 | Influence: 0.371 | ...,Lifecycle: Emerging | Rank: 1 | Peak: 2019-10 ...,General Markets Low Strong Stable Emerging Fas...,Strong Buy,101.300000,Long Term Compounder,Technology,2.0,0.371429
1,Financial Services,2,71.597915,Low,Strong,Stable,Emerging,"Fast Growing, Seasonal, High Activity","Low Risk, Balanced Market, High Coverage",Community: 0.0 | Rank: 1 | Influence: 0.405 | ...,Lifecycle: Emerging | Rank: 3 | Peak: 2019-11 ...,Financial Services Low Strong Stable Emerging ...,Strong Buy,90.000000,Long Term Compounder,General Markets,1.0,0.404762
2,Corporate,3,70.512834,Low,Strong,Very Stable,Emerging,"Fast Growing, Seasonal, High Activity","Low Risk, Stable Market, High Coverage",Community: 0.0 | Rank: 4 | Influence: 0.286 | ...,Lifecycle: Emerging | Rank: 4 | Peak: 2020-05 ...,Corporate Low Strong Very Stable Emerging Fast...,Strong Buy,90.750000,Long Term Compounder,General Markets,4.0,0.285714
3,Technology,4,68.178981,Low,Average,Very Stable,Emerging,"Fast Growing, Seasonal, High Activity","Low Risk, Stable Market, High Coverage",Community: 0.0 | Rank: 3 | Influence: 0.286 | ...,Lifecycle: Emerging | Rank: 2 | Peak: 2017-01 ...,Technology Low Average Very Stable Emerging Fa...,Watch,68.178981,Monitor,None,3.0,0.285714
4,Commodities,5,63.356337,Low,Average,Stable,Emerging,"Fast Growing, Seasonal, High Activity","Low Risk, Balanced Market, High Coverage",Community: Independent | Rank: Not Connected |...,Lifecycle: Emerging | Rank: 5 | Peak: 2019-08 ...,Commodities Low Average Stable Emerging Fast G...,Watch,63.356337,Monitor,None,NaN,NaN

## 121. Fill Missing Values

In [198]:
sector_search["recommendation"] = (

    sector_search["recommendation"]

    .fillna("No Recommendation")

)

sector_search["investment_theme"] = (

    sector_search["investment_theme"]

    .fillna("None")

)

sector_search["top_similar_sector"] = (

    sector_search["top_similar_sector"]

    .fillna("None")

)

sector_search["network_rank"] = (

    sector_search["network_rank"]

    .fillna(0)

    .astype(int)

)

sector_search["network_influence"] = (

    sector_search["network_influence"]

    .fillna(0)

)

## 122. Verify Search Dataset

In [199]:
print(sector_search.shape)

display(

    sector_search.head(20)

)

(28, 18)

,sector,sector_rank,sector_intelligence_score,sector_risk_level,company_strength,market_stability_category,lifecycle,temporal_fingerprint,sector_risk_fingerprint,knowledge_card,temporal_card,search_text,recommendation,recommendation_strength,investment_theme,top_similar_sector,network_rank,network_influence
0,General Markets,1,85.754461,Low,Strong,Stable,Emerging,"Fast Growing, Seasonal, High Activity","Low Risk, Balanced Market, Highly Diversified,...",Community: 0.0 | Rank: 2 | Influence: 0.371 | ...,Lifecycle: Emerging | Rank: 1 | Peak: 2019-10 ...,General Markets Low Strong Stable Emerging Fas...,Strong Buy,101.300000,Long Term Compounder,Technology,2,0.371429
1,Financial Services,2,71.597915,Low,Strong,Stable,Emerging,"Fast Growing, Seasonal, High Activity","Low Risk, Balanced Market, High Coverage",Community: 0.0 | Rank: 1 | Influence: 0.405 | ...,Lifecycle: Emerging | Rank: 3 | Peak: 2019-11 ...,Financial Services Low Strong Stable Emerging ...,Strong Buy,90.000000,Long Term Compounder,General Markets,1,0.404762
2,Corporate,3,70.512834,Low,Strong,Very Stable,Emerging,"Fast Growing, Seasonal, High Activity","Low Risk, Stable Market, High Coverage",Community: 0.0 | Rank: 4 | Influence: 0.286 | ...,Lifecycle: Emerging | Rank: 4 | Peak: 2020-05 ...,Corporate Low Strong Very Stable Emerging Fast...,Strong Buy,90.750000,Long Term Compounder,General Markets,4,0.285714
3,Technology,4,68.178981,Low,Average,Very Stable,Emerging,"Fast Growing, Seasonal, High Activity","Low Risk, Stable Market, High Coverage",Community: 0.0 | Rank: 3 | Influence: 0.286 | ...,Lifecycle: Emerging | Rank: 2 | Peak: 2017-01 ...,Technology Low Average Very Stable Emerging Fa...,Watch,68.178981,Monitor,None,3,0.285714
4,Commodities,5,63.356337,Low,Average,Stable,Emerging,"Fast Growing, Seasonal, High Activity","Low Risk, Balanced Market, High Coverage",Community: Independent | Rank: Not Connected |...,Lifecycle: Emerging | Rank: 5 | Peak: 2019-08 ...,Commodities Low Average Stable Emerging Fast G...,Watch,63.356337,Monitor,None,0,0.000000
5,Healthcare,6,61.331079,Low,Strong,Stable,Mature,"Mature, Seasonal, Low Activity","Low Risk, Balanced Market, Highly Diversified",Community: 1.0 | Rank: 6 | Influence: 0.202 | ...,Lifecycle: Mature | Rank: 7 | Peak: 2018-08 | ...,"Healthcare Low Strong Stable Mature Mature, Se...",Buy,74.260000,Growth Opportunity,Pharmaceuticals,6,0.202381
6,Macroeconomics,7,61.066999,Low,Average,Very Stable,Growing,"Growing, Seasonal, Low Activity","Low Risk, Stable Market",Community: Independent | Rank: Not Connected |...,Lifecycle: Growing | Rank: 8 | Peak: 2019-06 |...,Macroeconomics Low Average Very Stable Growing...,Watch,61.066999,Monitor,None,0,0.000000
7,Energy,8,60.588049,Low,Strong,Stable,Growing,"Growing, Seasonal, Medium Activity","Low Risk, Balanced Market, Highly Diversified",Community: Independent | Rank: Not Connected |...,Lifecycle: Growing | Rank: 6 | Peak: 2019-09 |...,"Energy Low Strong Stable Growing Growing, Seas...",Watch,60.588049,Monitor,None,0,0.000000
8,Cryptocurrency,9,60.472661,Low,Average,Very Stable,Growing,"Growing, Seasonal, Low Activity","Low Risk, Stable Market",Community: Independent | Rank: Not Connected |...,Lifecycle: Growing | Rank: 9 | Peak: 2017-12 |...,Cryptocurrency Low Average Very Stable Growing...,Watch,60.472661,Monitor,None,0,0.000000
9,Cybersecurity,10,58.998539,Medium,Strong,Stable,Growing,"Growing, Seasonal, Low Activity","Moderate Risk, Balanced Market",Community: Independent | Rank: Not Connected |...,Lifecycle: Growing | Rank: 11 | Peak: 2018-11 ...,Cybersecurity Medium Strong Stable Growing Gro...,Watch,58.998539,Monitor,None,0,0.000000
10,Banking,11,56.554188,Low,Strong,Stable,Growing,"Growing, Seasonal, Low Activity","Low Risk, Balanced Market, Highly Diversified",Community: Independent | Rank: Not Connected |...,Lifecycle: Growing | Rank: 10 | Peak: 2015-06 ...,"Banking Low Strong Stable Growing Growing, Sea...",Watch,56.554188,Monitor,None,0,0.000000
11,Real Estate,12,55.330319,Low,Strong,Very Stable,Emerging,"Fast Growing, Highly Seasonal, Low Activity","Low Risk, Stable Market",Community: Independent | Rank: Not Connected |...,Lifecycle: Emerging | Rank: 16 | Peak: 2019-06...,Real Estate Low Strong Very Stable Emerging Fa...,Watch,55.330319,Monitor,None,0,0.000000
12,Automotive,13,51.146034,Low,Strong,Stable,Growing,"Growing, Seasonal, Low Activity","Low Risk, Balanced Market, Highly Diversified",Community: Independent | Rank: Not Connected |...,Lifecycle: Growing | Rank: 15 | Peak: 2020-03 ...,"Automotive Low Strong Stable Growing Growing, ...",Watch,51.146034,Monitor,None,0,0.000000
13,Semiconductors,14,51.074839,Low,Strong,Very Stable,Emerging,"Fast Growing, Seasonal, Low Activity","Low Risk, Stable Market, Highly Diversified",Community: Independent | Rank: Not Connected |...,Lifecycle: Emerging | Rank: 14 | Peak: 2019-01...,Semiconductors Low Strong Very Stable Emerging...,Watch,51.074839,Monitor,None,0,0.000000
14,Artificial Intelligence,15,50.882945,Low,Strong,Very Stable,Emerging,"Fast Growing, Highly Seasonal, Low Activity","Low Risk, Stable Market",Community: Independent | Rank: Not Connected |...,Lifecycle: Emerging | Rank: 22 | Peak: 2017-11...,Artificial Intelligence Low Strong Very Stable...,Watch,50.882945,Monitor,None,0,0.000000
15,Retail,16,50.546851,Low,Strong,Very Stable,Emerging,"Fast Growing, Seasonal, Low Activity","Low Risk, Stable Market, Highly Diversified",Community: Independent | Rank: Not Connected |...,Lifecycle: Emerging | Rank: 12 | Peak: 2020-05...,Retail Low Strong Very Stable Emerging Fast Gr...,Watch,50.546851,Monitor,None,0,0.000000
16,Pharmaceuticals,17,50.426683,Low,Strong,Stable,Emerging,"Fast Growing, Seasonal, Low Activity","Low Risk, Balanced Market, Highly Diversified",Community: 1.0 | Rank: 8 | Influence: 0.105 | ...,Lifecycle: Emerging | Rank: 13 | Peak: 2018-11...,Pharmaceuticals Low Strong Stable Emerging Fas...,Watch,50.426683,Monitor,None,8,0.104762
17,Media,18,50.371306,Low,Strong,Stable,Emerging,"Fast Growing, Seasonal, Low Activity","Low Risk, Balanced Market, Strong Companies, H...",Community: Independent | Rank: Not Connected |...,Lifecycle: Emerging | Rank: 18 | Peak: 2016-11...,"Media Low Strong Stable Emerging Fast Growing,...",Watch,50.371306,Monitor,None,0,0.000000
18,Insurance,19,49.389860,Low,Average,Very Stable,Growing,"Growing, Seasonal, Low Activity","Low Risk, Stable Market",Community: Independent | Rank: Not Connected |...,Lifecycle: Growing | Rank: 20 | Peak: 2018-03 ...,Insurance Low Average Very Stable Growing Grow...,Watch,49.389860,Monitor,None,0,0.000000
19,FinTech,20,49.365379,Low,Strong,Stable,Emerging,"Fast Growing, Seasonal, Low Activity","Low Risk, Balanced Market, Strong Companies, H...",Community: Independent | Rank: Not Connected |...,Lifecycle: Emerging | Rank: 21 | Peak: 2017-06...,FinTech Low Strong Stable Emerging Fast Growin...,Watch,49.365379,Monitor,None,0,0.000000

## 123. Build Keyword Dictionary

In [200]:
sector_keywords = {}

for sector, keywords in SECTOR_KEYWORDS.items():

    sector_keywords[sector] = [

        k.lower()

        for k in keywords

    ]

display(

    pd.DataFrame({

        "sector": sector_keywords.keys(),

        "keywords": [

            len(v)

            for v in sector_keywords.values()

        ]

    })

)

                     sector  keywords
0   Artificial Intelligence         9
1            Semiconductors        12
2           Cloud Computing         7
3             Cybersecurity         8
4                   Banking        10
5                 Insurance         5
6                   FinTech         8
7                Healthcare         6
8             Biotechnology         6
9           Pharmaceuticals         5
10        Electric Vehicles         6
11               Automotive         8
12                   Energy         8
13                   Mining         6
14                   Retail         7
15           Consumer Goods         6
16       Telecommunications         5
17                    Media         7
18              Real Estate         5
19           Transportation         6
20           Cryptocurrency         6
21           Macroeconomics         8
22              Commodities         8
23          General Markets         7

## 124. Add Sector Name as Keyword

In [214]:
for sector in sector_keywords:

    sector_keywords[sector] = list(

        dict.fromkeys(

            sector_keywords[sector]

        )

    )

print(

    "Total sectors :",

    len(sector_keywords)

)

print(

    "Example:\n",

    sector_keywords["Artificial Intelligence"][:15]

)

Total sectors : 24
Example:
 ['artificial intelligence', 'ai', 'machine learning', 'deep learning', 'llm', 'chatgpt', 'generative ai', 'neural network', 'foundation model']

## 125. Build Reverse Keyword Index

In [215]:
keyword_index = {}

for sector, keywords in sector_keywords.items():

    for keyword in keywords:

        keyword_index.setdefault(

            keyword,

            []

        ).append(

            sector

        )

print(

    "Unique keywords:",

    len(keyword_index)

)

display(

    pd.DataFrame({

        "keyword": list(keyword_index.keys())[:20],

        "sector": list(keyword_index.values())[:20]

    })

)

Unique keywords: 177

                    keyword                     sector
0   artificial intelligence  [Artificial Intelligence]
1                        ai  [Artificial Intelligence]
2          machine learning  [Artificial Intelligence]
3             deep learning  [Artificial Intelligence]
4                       llm  [Artificial Intelligence]
5                   chatgpt  [Artificial Intelligence]
6             generative ai  [Artificial Intelligence]
7            neural network  [Artificial Intelligence]
8          foundation model  [Artificial Intelligence]
9                      chip           [Semiconductors]
10                    chips           [Semiconductors]
11            semiconductor           [Semiconductors]
12                      gpu           [Semiconductors]
13                      cpu           [Semiconductors]
14                processor           [Semiconductors]
15                    wafer           [Semiconductors]
16                      fab           [Semiconductors]
17                     tsmc           [Semiconductors]
18                   nvidia           [Semiconductors]
19                      amd           [Semiconductors]

## 126. Search Keyword Statistics

In [216]:
keyword_stats = pd.DataFrame({

    "Metric":[

        "Total Sectors",

        "Unique Search Keywords",

        "Average Keywords per Sector"

    ],

    "Value":[

        len(sector_keywords),

        len(keyword_index),

        round(

            np.mean(

                [

                    len(v)

                    for v in sector_keywords.values()

                ]

            ),

            2

        )

    ]

})

display(keyword_stats)

                        Metric  Value
0                Total Sectors   24.0
1       Unique Search Keywords  177.0
2  Average Keywords per Sector    7.5

## 127. Save Keyword Dictionary

In [217]:
with open(

    os.path.join(

        SECTOR_PATH,

        "sector_keyword_dictionary.pkl"

    ),

    "wb"

) as f:

    pickle.dump(

        sector_keywords,

        f

    )

with open(

    os.path.join(

        SECTOR_PATH,

        "keyword_index.pkl"

    ),

    "wb"

) as f:

    pickle.dump(

        keyword_index,

        f

    )

## 128. Test the Search Index

In [218]:
test_queries = [

    "ai",

    "bank",

    "oil",

    "cloud",

    "bitcoin",

    "tesla",

    "insurance",

    "healthcare",

    "chip",

    "amazon"

]

test_results = pd.DataFrame({

    "query": test_queries,

    "matched_sector":[

        keyword_index.get(

            q,

            []

        )

        for q in test_queries

    ]

})

display(test_results)

        query             matched_sector
0          ai  [Artificial Intelligence]
1        bank                  [Banking]
2         oil      [Energy, Commodities]
3       cloud          [Cloud Computing]
4     bitcoin           [Cryptocurrency]
5       tesla        [Electric Vehicles]
6   insurance                [Insurance]
7  healthcare               [Healthcare]
8        chip           [Semiconductors]
9      amazon                   [Retail]

## 129. Build Search Function

In [219]:
def search_sector(query):

    query = str(query).lower().strip()

    matched = []

    for keyword, sectors in keyword_index.items():

        if query in keyword:

            matched.extend(sectors)

    matched = sorted(

        list(set(matched))

    )

    return matched

## 130. Test Partial Search

In [220]:
queries = [

    "intel",

    "gpu",

    "gold",

    "amazon",

    "bank",

    "health",

    "cloud",

    "bitcoin",

    "tes",

    "net"

]

search_results = pd.DataFrame({

    "query": queries,

    "results":[

        search_sector(q)

        for q in queries

    ]

})

display(search_results)

     query                                            results
0    intel          [Artificial Intelligence, Semiconductors]
1      gpu                                   [Semiconductors]
2     gold                     [Banking, Commodities, Mining]
3   amazon                                           [Retail]
4     bank                                          [Banking]
5   health                                       [Healthcare]
6    cloud                                  [Cloud Computing]
7  bitcoin                                   [Cryptocurrency]
8      tes                [Electric Vehicles, Macroeconomics]
9      net  [Artificial Intelligence, Media, Telecommunica...

## 131. Build Retrieval Function

In [221]:
def retrieve_sector_information(query):

    sectors = search_sector(query)

    if len(sectors) == 0:

        return pd.DataFrame()

    return (

        sector_search[

            sector_search["sector"]

            .isin(sectors)

        ]

        .sort_values(

            "sector_rank"

        )

    )

## 132. Test Retrieval Engine

In [222]:
display(

    retrieve_sector_information(

        "bank"

    )

)

,sector,sector_rank,sector_intelligence_score,sector_risk_level,company_strength,market_stability_category,lifecycle,temporal_fingerprint,sector_risk_fingerprint,knowledge_card,temporal_card,search_text,recommendation,recommendation_strength,investment_theme,top_similar_sector,network_rank,network_influence
10,Banking,11,56.554188,Low,Strong,Stable,Growing,"Growing, Seasonal, Low Activity","Low Risk, Balanced Market, Highly Diversified",Community: Independent | Rank: Not Connected |...,Lifecycle: Growing | Rank: 10 | Peak: 2015-06 ...,"Banking Low Strong Stable Growing Growing, Sea...",Watch,56.554188,Monitor,None,0,0.0

In [224]:
display(

    retrieve_sector_information(

        "cloud"

    )

)

display(

    retrieve_sector_information(

        "oil"

    )

)

display(

    retrieve_sector_information(

        "tesla"

    )

)

,sector,sector_rank,sector_intelligence_score,sector_risk_level,company_strength,market_stability_category,lifecycle,temporal_fingerprint,sector_risk_fingerprint,knowledge_card,temporal_card,search_text,recommendation,recommendation_strength,investment_theme,top_similar_sector,network_rank,network_influence
24,Cloud Computing,25,45.808622,Low,Strong,Stable,Emerging,"Fast Growing, Seasonal, Low Activity","Low Risk, Balanced Market",Community: Independent | Rank: Not Connected |...,Lifecycle: Emerging | Rank: 25 | Peak: 2016-10...,Cloud Computing Low Strong Stable Emerging Fas...,Watch,45.808622,Monitor,None,0,0.0

,sector,sector_rank,sector_intelligence_score,sector_risk_level,company_strength,market_stability_category,lifecycle,temporal_fingerprint,sector_risk_fingerprint,knowledge_card,temporal_card,search_text,recommendation,recommendation_strength,investment_theme,top_similar_sector,network_rank,network_influence
4,Commodities,5,63.356337,Low,Average,Stable,Emerging,"Fast Growing, Seasonal, High Activity","Low Risk, Balanced Market, High Coverage",Community: Independent | Rank: Not Connected |...,Lifecycle: Emerging | Rank: 5 | Peak: 2019-08 ...,Commodities Low Average Stable Emerging Fast G...,Watch,63.356337,Monitor,None,0,0.0
7,Energy,8,60.588049,Low,Strong,Stable,Growing,"Growing, Seasonal, Medium Activity","Low Risk, Balanced Market, Highly Diversified",Community: Independent | Rank: Not Connected |...,Lifecycle: Growing | Rank: 6 | Peak: 2019-09 |...,"Energy Low Strong Stable Growing Growing, Seas...",Watch,60.588049,Monitor,None,0,0.0

,sector,sector_rank,sector_intelligence_score,sector_risk_level,company_strength,market_stability_category,lifecycle,temporal_fingerprint,sector_risk_fingerprint,knowledge_card,temporal_card,search_text,recommendation,recommendation_strength,investment_theme,top_similar_sector,network_rank,network_influence
20,Electric Vehicles,21,49.017908,Low,Strong,Stable,Emerging,"Fast Growing, Highly Seasonal, Low Activity","Low Risk, Balanced Market, Highly Diversified",Community: Independent | Rank: Not Connected |...,Lifecycle: Emerging | Rank: 19 | Peak: 2020-02...,Electric Vehicles Low Strong Stable Emerging F...,Watch,49.017908,Monitor,None,0,0.0

## 133. Build Search Statistics

In [225]:
search_statistics = pd.DataFrame({

    "Metric":[

        "Searchable Sectors",

        "Search Keywords",

        "Search Documents"

    ],

    "Value":[

        len(sector_search),

        len(keyword_index),

        len(sector_search)

    ]

})

display(search_statistics)

               Metric  Value
0  Searchable Sectors     28
1     Search Keywords    177
2    Search Documents     28

## 134. Save Search Assets

In [226]:
sector_search.to_parquet(

    os.path.join(

        SECTOR_PATH,

        "sector_search.parquet"

    ),

    index=False

)

search_statistics.to_parquet(

    os.path.join(

        SECTOR_PATH,

        "search_statistics.parquet"

    ),

    index=False

)

## 135. Knowledge Retrieval & Final Knowledge Base

In [227]:
def get_sector_knowledge(sector_name):

    result = sector_search[
        sector_search["sector"] == sector_name
    ]

    if result.empty:

        return None

    row = result.iloc[0]

    return {

        "Sector": row["sector"],

        "Rank": row["sector_rank"],

        "Recommendation": row["recommendation"],

        "Recommendation Strength": round(

            row["recommendation_strength"],

            2

        ),

        "Risk": row["sector_risk_level"],

        "Lifecycle": row["lifecycle"],

        "Company Strength": row["company_strength"],

        "Market": row["market_stability_category"],

        "Fingerprint": row["sector_risk_fingerprint"],

        "Knowledge Card": row["knowledge_card"],

        "Temporal Card": row["temporal_card"]

    }

## 136. Test Knowledge Retrieval

In [228]:
knowledge = get_sector_knowledge(

    "Technology"

)

knowledge

{'Sector': 'Technology',
 'Rank': np.int64(4),
 'Recommendation': 'Watch',
 'Recommendation Strength': np.float64(68.18),
 'Risk': 'Low',
 'Lifecycle': 'Emerging',
 'Company Strength': 'Average',
 'Market': 'Very Stable',
 'Fingerprint': 'Low Risk, Stable Market, High Coverage',
 'Knowledge Card': 'Community: 0.0 | Rank: 3 | Influence: 0.286 | Risk: Low | Strength: Average',
 'Temporal Card': 'Lifecycle: Emerging | Rank: 2 | Peak: 2017-01 | Avg Monthly News: 4099.5'}

## 137. Retrieve Multiple Sectors

In [229]:
def knowledge_from_query(query):

    sectors = search_sector(query)

    output = []

    for sector in sectors:

        output.append(

            get_sector_knowledge(

                sector

            )

        )

    return output

## 138. Test Query Retrieval

In [230]:
knowledge_from_query(

    "cloud"

)

[{'Sector': 'Cloud Computing',
  'Rank': np.int64(25),
  'Recommendation': 'Watch',
  'Recommendation Strength': np.float64(45.81),
  'Risk': 'Low',
  'Lifecycle': 'Emerging',
  'Company Strength': 'Strong',
  'Market': 'Stable',
  'Fingerprint': 'Low Risk, Balanced Market',
  'Knowledge Card': 'Community: Independent | Rank: Not Connected | Influence: 0 | Risk: Low | Strength: Strong',
  'Temporal Card': 'Lifecycle: Emerging | Rank: 25 | Peak: 2016-10 | Avg Monthly News: 2.2'}]

In [231]:
knowledge_from_query(

    "oil"

)

knowledge_from_query(

    "tesla"

)

knowledge_from_query(

    "bank"

)

[{'Sector': 'Banking',
  'Rank': np.int64(11),
  'Recommendation': 'Watch',
  'Recommendation Strength': np.float64(56.55),
  'Risk': 'Low',
  'Lifecycle': 'Growing',
  'Company Strength': 'Strong',
  'Market': 'Stable',
  'Fingerprint': 'Low Risk, Balanced Market, Highly Diversified',
  'Knowledge Card': 'Community: Independent | Rank: Not Connected | Influence: 0 | Risk: Low | Strength: Strong',
  'Temporal Card': 'Lifecycle: Growing | Rank: 10 | Peak: 2015-06 | Avg Monthly News: 62.3'}]

## 139. Build Knowledge Summary Table

In [232]:
knowledge_summary = sector_search[

    [

        "sector",

        "sector_rank",

        "recommendation",

        "recommendation_strength",

        "sector_risk_level",

        "lifecycle",

        "investment_theme"

    ]

].copy()

display(

    knowledge_summary.head(20)

)

,sector,sector_rank,recommendation,recommendation_strength,sector_risk_level,lifecycle,investment_theme
0,General Markets,1,Strong Buy,101.300000,Low,Emerging,Long Term Compounder
1,Financial Services,2,Strong Buy,90.000000,Low,Emerging,Long Term Compounder
2,Corporate,3,Strong Buy,90.750000,Low,Emerging,Long Term Compounder
3,Technology,4,Watch,68.178981,Low,Emerging,Monitor
4,Commodities,5,Watch,63.356337,Low,Emerging,Monitor
5,Healthcare,6,Buy,74.260000,Low,Mature,Growth Opportunity
6,Macroeconomics,7,Watch,61.066999,Low,Growing,Monitor
7,Energy,8,Watch,60.588049,Low,Growing,Monitor
8,Cryptocurrency,9,Watch,60.472661,Low,Growing,Monitor
9,Cybersecurity,10,Watch,58.998539,Medium,Growing,Monitor
10,Banking,11,Watch,56.554188,Low,Growing,Monitor
11,Real Estate,12,Watch,55.330319,Low,Emerging,Monitor
12,Automotive,13,Watch,51.146034,Low,Growing,Monitor
13,Semiconductors,14,Watch,51.074839,Low,Emerging,Monitor
14,Artificial Intelligence,15,Watch,50.882945,Low,Emerging,Monitor
15,Retail,16,Watch,50.546851,Low,Emerging,Monitor
16,Pharmaceuticals,17,Watch,50.426683,Low,Emerging,Monitor
17,Media,18,Watch,50.371306,Low,Emerging,Monitor
18,Insurance,19,Watch,49.389860,Low,Growing,Monitor
19,FinTech,20,Watch,49.365379,Low,Emerging,Monitor

## 140. Save Knowledge Summary

In [233]:
knowledge_summary.to_parquet(

    os.path.join(

        SECTOR_PATH,

        "knowledge_summary.parquet"

    ),

    index=False

)

## 141. Create Complete Sector Knowledge Base

In [234]:
sector_knowledge_base = sector_search.merge(

    sector_master[
        [
            "sector",
            "community",
            "community_size"
        ]
    ],

    on="sector",

    how="left"

)

display(

    sector_knowledge_base.head()

)

,sector,sector_rank,sector_intelligence_score,sector_risk_level,company_strength,market_stability_category,lifecycle,temporal_fingerprint,sector_risk_fingerprint,knowledge_card,temporal_card,search_text,recommendation,recommendation_strength,investment_theme,top_similar_sector,network_rank,network_influence,community,community_size
0,General Markets,1,85.754461,Low,Strong,Stable,Emerging,"Fast Growing, Seasonal, High Activity","Low Risk, Balanced Market, Highly Diversified,...",Community: 0.0 | Rank: 2 | Influence: 0.371 | ...,Lifecycle: Emerging | Rank: 1 | Peak: 2019-10 ...,General Markets Low Strong Stable Emerging Fas...,Strong Buy,101.300000,Long Term Compounder,Technology,2,0.371429,0.0,5
1,Financial Services,2,71.597915,Low,Strong,Stable,Emerging,"Fast Growing, Seasonal, High Activity","Low Risk, Balanced Market, High Coverage",Community: 0.0 | Rank: 1 | Influence: 0.405 | ...,Lifecycle: Emerging | Rank: 3 | Peak: 2019-11 ...,Financial Services Low Strong Stable Emerging ...,Strong Buy,90.000000,Long Term Compounder,General Markets,1,0.404762,0.0,5
2,Corporate,3,70.512834,Low,Strong,Very Stable,Emerging,"Fast Growing, Seasonal, High Activity","Low Risk, Stable Market, High Coverage",Community: 0.0 | Rank: 4 | Influence: 0.286 | ...,Lifecycle: Emerging | Rank: 4 | Peak: 2020-05 ...,Corporate Low Strong Very Stable Emerging Fast...,Strong Buy,90.750000,Long Term Compounder,General Markets,4,0.285714,0.0,5
3,Technology,4,68.178981,Low,Average,Very Stable,Emerging,"Fast Growing, Seasonal, High Activity","Low Risk, Stable Market, High Coverage",Community: 0.0 | Rank: 3 | Influence: 0.286 | ...,Lifecycle: Emerging | Rank: 2 | Peak: 2017-01 ...,Technology Low Average Very Stable Emerging Fa...,Watch,68.178981,Monitor,None,3,0.285714,0.0,5
4,Commodities,5,63.356337,Low,Average,Stable,Emerging,"Fast Growing, Seasonal, High Activity","Low Risk, Balanced Market, High Coverage",Community: Independent | Rank: Not Connected |...,Lifecycle: Emerging | Rank: 5 | Peak: 2019-08 ...,Commodities Low Average Stable Emerging Fast G...,Watch,63.356337,Monitor,None,0,0.000000,Independent,1

## 142. Fill Missing Values

In [235]:
sector_knowledge_base["community"] = (

    sector_knowledge_base["community"]

    .fillna("Independent")

)

sector_knowledge_base["community_size"] = (

    sector_knowledge_base["community_size"]

    .fillna(0)

    .astype(int)

)

sector_knowledge_base["top_similar_sector"] = (

    sector_knowledge_base["top_similar_sector"]

    .fillna("None")

)

sector_knowledge_base["investment_theme"] = (

    sector_knowledge_base["investment_theme"]

    .fillna("Monitor")

)

display(

    sector_knowledge_base.head()

)

,sector,sector_rank,sector_intelligence_score,sector_risk_level,company_strength,market_stability_category,lifecycle,temporal_fingerprint,sector_risk_fingerprint,knowledge_card,temporal_card,search_text,recommendation,recommendation_strength,investment_theme,top_similar_sector,network_rank,network_influence,community,community_size
0,General Markets,1,85.754461,Low,Strong,Stable,Emerging,"Fast Growing, Seasonal, High Activity","Low Risk, Balanced Market, Highly Diversified,...",Community: 0.0 | Rank: 2 | Influence: 0.371 | ...,Lifecycle: Emerging | Rank: 1 | Peak: 2019-10 ...,General Markets Low Strong Stable Emerging Fas...,Strong Buy,101.300000,Long Term Compounder,Technology,2,0.371429,0.0,5
1,Financial Services,2,71.597915,Low,Strong,Stable,Emerging,"Fast Growing, Seasonal, High Activity","Low Risk, Balanced Market, High Coverage",Community: 0.0 | Rank: 1 | Influence: 0.405 | ...,Lifecycle: Emerging | Rank: 3 | Peak: 2019-11 ...,Financial Services Low Strong Stable Emerging ...,Strong Buy,90.000000,Long Term Compounder,General Markets,1,0.404762,0.0,5
2,Corporate,3,70.512834,Low,Strong,Very Stable,Emerging,"Fast Growing, Seasonal, High Activity","Low Risk, Stable Market, High Coverage",Community: 0.0 | Rank: 4 | Influence: 0.286 | ...,Lifecycle: Emerging | Rank: 4 | Peak: 2020-05 ...,Corporate Low Strong Very Stable Emerging Fast...,Strong Buy,90.750000,Long Term Compounder,General Markets,4,0.285714,0.0,5
3,Technology,4,68.178981,Low,Average,Very Stable,Emerging,"Fast Growing, Seasonal, High Activity","Low Risk, Stable Market, High Coverage",Community: 0.0 | Rank: 3 | Influence: 0.286 | ...,Lifecycle: Emerging | Rank: 2 | Peak: 2017-01 ...,Technology Low Average Very Stable Emerging Fa...,Watch,68.178981,Monitor,None,3,0.285714,0.0,5
4,Commodities,5,63.356337,Low,Average,Stable,Emerging,"Fast Growing, Seasonal, High Activity","Low Risk, Balanced Market, High Coverage",Community: Independent | Rank: Not Connected |...,Lifecycle: Emerging | Rank: 5 | Peak: 2019-08 ...,Commodities Low Average Stable Emerging Fast G...,Watch,63.356337,Monitor,None,0,0.000000,Independent,1

## 143. Create Complete Search Description

In [236]:
sector_knowledge_base["complete_description"] = (

      sector_knowledge_base["sector"]

    + " | "

    + sector_knowledge_base["recommendation"]

    + " | "

    + sector_knowledge_base["sector_risk_level"]

    + " Risk | "

    + sector_knowledge_base["company_strength"]

    + " Companies | "

    + sector_knowledge_base["market_stability_category"]

    + " Market | "

    + sector_knowledge_base["lifecycle"]

    + " | "

    + sector_knowledge_base["investment_theme"]

)

display(

    sector_knowledge_base[
        [
            "sector",
            "complete_description"
        ]
    ].head()

)

               sector                               complete_description
0     General Markets  General Markets | Strong Buy | Low Risk | Stro...
1  Financial Services  Financial Services | Strong Buy | Low Risk | S...
2           Corporate  Corporate | Strong Buy | Low Risk | Strong Com...
3          Technology  Technology | Watch | Low Risk | Average Compan...
4         Commodities  Commodities | Watch | Low Risk | Average Compa...

## 144. Knowledge Base Statistics

In [237]:
knowledge_stats = pd.DataFrame(

    {

        "Metric":[

            "Total Sectors",

            "Communities",

            "Recommendations",

            "Knowledge Cards",

            "Temporal Cards"

        ],

        "Value":[

            sector_knowledge_base.shape[0],

            sector_knowledge_base["community"].nunique(),

            sector_knowledge_base["recommendation"].nunique(),

            sector_knowledge_base["knowledge_card"].notna().sum(),

            sector_knowledge_base["temporal_card"].notna().sum()

        ]

    }

)

display(

    knowledge_stats

)

            Metric  Value
0    Total Sectors     28
1      Communities      3
2  Recommendations      3
3  Knowledge Cards     28
4   Temporal Cards     28

## 145. Save Knowledge Base

In [238]:
sector_knowledge_base.to_parquet(

    os.path.join(

        SECTOR_PATH,

        "sector_knowledge_base.parquet"

    ),

    index=False

)

## 146. Save Search Index

In [240]:
keyword_df = pd.DataFrame({
    "keyword": keyword_index.keys(),
    "sectors": keyword_index.values()
})

keyword_df.to_parquet(
    os.path.join(
        SECTOR_PATH,
        "sector_keyword_index.parquet"
    ),
    index=False
)

## 147. Save Knowledge Statistics

In [241]:
knowledge_stats.to_csv(

    os.path.join(

        SECTOR_PATH,

        "knowledge_statistics.csv"

    ),

    index=False

)

## 148. Final Dataset Summary

In [243]:
final_summary = pd.DataFrame(

    {

        "Dataset":[

            "Sector Profile",

            "Sector Master",

            "Network Metrics",

            "Temporal Analysis",

            "Recommendation Engine",

            "Knowledge Base",

            "Keyword Index"

        ],

        "Rows":[

            sector_profile.shape[0],

            sector_master.shape[0],

            sector_network_metrics.shape[0],

            sector_temporal.shape[0],

            recommendation_master.shape[0],

            sector_knowledge_base.shape[0],

            keyword_df.shape[0]

        ]

    }

)

display(

    final_summary

)

                 Dataset  Rows
0         Sector Profile    28
1          Sector Master    28
2        Network Metrics     8
3      Temporal Analysis    28
4  Recommendation Engine    28
5         Knowledge Base    28
6          Keyword Index   177

## 149. Save Final Summary

In [244]:
final_summary.to_csv(

    os.path.join(

        SECTOR_PATH,

        "sector_pipeline_summary.csv"

    ),

    index=False

)